<div class="nav settings">
  <p>Opções:</p>
  <ul>
    <li class="item"><a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . 1) : ($this->url(array('page' => 1, 'format' => 'html', 'count' => 10)))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="10 itens por páginas" class="<?php echo (($this->itemCountPerPage == 10) ? 'current' : ''); ?>">10<i> itens por páginas</i></a></li>
    <li class="item"><a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . 1) : ($this->url(array('page' => 1, 'format' => 'html', 'count' => 50)))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="50 itens por páginas" class="<?php echo (($this->itemCountPerPage == 50) ? 'current' : ''); ?>">50<i> itens por páginas</i></a></li>
    <li class="item"><a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . 1) : ($this->url(array('page' => 1, 'format' => 'html', 'count' => 150)))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="150 itens por páginas" class="<?php echo (($this->itemCountPerPage == 150) ? 'current' : ''); ?>">150<i> itens por páginas</i></a></li>
  </ul>
</div>
<?php
if ($this->totalItemCount > 0):
?>
<div class="nav navigation">
  <p>Navegue por:</p>
  <ul>
    <li class="previous">
<?php
  if (isset($this->previous)):
    if (!$this->hidPrevious):
?>
      <a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . $this->previous) : ($this->url(array('page' => $this->previous, 'format' => 'html')))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="Página anterior"><i>Página anterior</i></a>
<?php
    endif;
  else:
?>
      <span><i>Página anterior</i></span>
<?php
  endif;
?>
    </li>
<?php
  if ($this->firstPageInRange > 1):
?>
    <li class="item"><a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . 1) : ($this->url(array('page' => 1, 'format' => 'html')))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="Página 1"><i>Página </i>1</a></li>
<?php
    if (($this->firstPageInRange - 1) != 1):
?>
    <li class="item gap"><span>...</span></li>
<?php
    endif;
  endif;
  if (!$this->hidRange and ($this->pageCount != 0)):
    foreach ($this->pagesInRange as $page):
?>
    <li class="item"><a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . $page) : ($this->url(array('page' => $page, 'format' => 'html')))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="Página <?php echo $page; ?>" class="<?php echo (($page == $this->current) ? 'current' : ''); ?>"><i>Página </i><?php echo $page; ?></a></li>
<?php
    endforeach;
  endif;
  if (($this->lastPageInRange != $this->pageCount) and ($this->pageCount != 0)):
    if ((($this->lastPageInRange + 1) !=  $this->pageCount) and ($this->pageCount != 0)):
?>
    <li class="item gap"><span>...</span></li>
<?php
    endif;
?>
    <li class="item"><a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . $this->pageCount) : ($this->url(array('page' => $this->pageCount, 'format' => 'html')))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="Página <?php echo $this->pageCount; ?>"><i>Página </i><?php echo $this->pageCount; ?></a></li>
<?php
  endif;
?>
    <li class="next">
<?php
  if (isset($this->next)):
    if (!$this->hidNext):
?>
      <a href="<?php echo (isset($this->link) ? ($this->link . "/page/" . $this->next) : ($this->url(array('page' => $this->next, 'format' => 'html')))) . (isset($_SERVER['QUERY_STRING']) ? ('?' . $_SERVER['QUERY_STRING']) : ''); ?>#lista" title="Próxima página"><i>Próxima página</i></a>
<?php
    endif;
  else:
?>
      <span><i>Próxima página</i></span>
<?php
  endif;
?>
    </li>
  </ul>
</div>
<?php
endif;
if (isset($this->jsScrollTo) and $this->request()->isXmlHttpRequest()):
?>
<script type="text/javascript">
/*
$(document).ready(function() {
    if ($('<?php //echo $this->jsScrollTo ?>').size())
    setTimeout(function(){
        $('html,body').animate({scrollTop: $('<?php echo $this->jsScrollTo ?>').offset().top}, 700);
    }, 400);
});
*/
</script>
<?php
endif;
?>
