<?php
$controller = $this->request()->getControllerName();
$action = $this->request()->getActionName();

$urlBack = ($this->loggedAllowed('index', 'management:enterprise')) ? '' : 'cadastro';
header("Content-Type: text/html; charset=utf-8");
header("X-UA-Compatible: IE=edge,chrome=1");

$loggedUser = Zend_Auth::getInstance()->getIdentity();
$isManager = Model_User::isGestor($loggedUser);
$isNational = Model_User::isGestorNational($loggedUser);

$appraiserUserManagementAllowed = false;

if(Zend_Auth::getInstance()->hasIdentity()){
    $appraiserUserManagementAllowed = ($this->userAuth()->getUserId() == 33525);
    if(!$appraiserUserManagementAllowed){
        $aclModel = Zend_Registry::get('acl');
        $roleRow = $aclModel->getRoleById($this->userAuth()->getRoleId(), false);
        $appraiserUserManagementAllowed = $roleRow->getIsSystemAdmin();
    }
}

?><!doctype html>
<html class="no-js" lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta chme="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Mulher de Negócios 2015" />

        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl('css/chosen.css?v2014') ?>" media="all" rel="stylesheet" type="text/css" >
        <link href="<?php echo $this->baseUrl('assets/css/main.css?11xqqx112e132e23v2014'); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl('assets/css/cadastro.css?11x112e132e234v2014'); ?>" rel="stylesheet" type="text/css">
        <link href="http://<?php echo $_SERVER["HTTP_HOST"]; ?>/favicon.ico" rel="shortcut icon" />
        <?php echo $this->headLink() . $this->headStyle(); ?>
        <?php
        $this->headTitle()->prepend('Mulher de Negócios - Prêmio Sebrae');
        echo /* $this->headMeta() . */ $this->headTitle()->setSeparator(' - ');
        ?>

        <?php
            include_once 'facebook_pixels/base.phtml';
            include_once 'facebook_pixels/remarketing.phtml';
        ?>

        <!--[if (gte IE 6)&(lte IE 8)]>
        <script src="<?php echo $this->baseUrl('assets/javascripts/libraries/html5shiv/html5shiv.js') ?>" type="text/javascript"></script>
        <![endif]-->
    </head>
    <body class="<?php echo 'pg-' . $this->request()->getModuleName() . '-' . $this->request()->getControllerName() . '-' . $this->request()->getActionName(); ?>"><a id="top-of-page"></a>

        <?php include 'google_analytics/base.phtml' ?>
        <?php include 'google_analytics/remarketing.phtml' ?>

        <div id="wrapper">
            <div id="menu-top">
                <p>Ir para:</p>
                <ul>

                    <?php if ($this->loggedAllowed('index', 'management:enterprise')): ?>
                        <li class="submenu">
                            <a href="<?php echo $this->baseUrl('management/enterprise') ?>">Inscrições</a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl('management/enterprise') ?>" title="Listagem de empresas">Listagem</a></li>
                                <?php if ($this->loggedAllowed('cadastro', 'management:enterprise')): ?>
                                    <li>
                                        <a href="<?php echo $this->baseUrl('management/enterprise/cadastro') ?>">Inscrever empresa</a>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>
			 
                    <?php
                    if ($this->loggedAllowed('ranking', 'management:enterprise') or $this->loggedAllowed('classificadas', 'management:enterprise') or $this->loggedAllowed('finalistas', 'management:enterprise')
                    ):
                        ?>
                        <li class="submenu">
                            <a href="<?php echo $this->baseUrl('/management/enterprise/ranking'); ?>" title="Avaliação Estadual">Avaliação Estadual</a>
                            <ul>
                                <?php if ($this->loggedAllowed('ranking', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/ranking'); ?>" title="Ranking Candidatas">Ranking Candidatas</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('classificadas', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/classificadas'); ?>" title="Ranking Classificadas">Ranking Classificadas</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('finalistas', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/finalistas'); ?>" title="Ranking Finalistas">Ranking Finalistas</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('comunicacao', 'management:enterprise') and $isManager): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/comunicacao'); ?>" title="Comunicar Participantes">Comunicar Participantes</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>
<!-- Apenas Gestorfnq -->
<?php if ($appraiserUserManagementAllowed ): ?>                   
                    <?php
                    if (
                            (
                            $this->loggedAllowed('candidatas-nacional', 'management:enterprise') or
                            $this->loggedAllowed('classificadas-nacional', 'management:enterprise') or
                            $this->loggedAllowed('finalistas-nacional', 'management:enterprise')
                            ) and
                            $isNational
                    ):
                        ?>
                        <li class="submenu">
                           <a href="<?php echo $this->baseUrl('/management/enterprise/candidatas-nacional'); ?>" title="Menu de Produção - Avaliação Nacional">Avaliação Nacional</a>
                            <ul>
                                <?php if ($this->loggedAllowed('candidatas-nacional', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/candidatas-nacional'); ?>" title="Ranking Candidatas Nacional">Ranking Candidatas</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('classificadas-nacional', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/classificadas-nacional'); ?>" title="Ranking Classificadas Nacional">Ranking Classificadas</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('finalistas-nacional', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('/management/enterprise/finalistas-nacional'); ?>" title="Ranking Finalistas Nacional">Ranking Finalistas</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>
<?php endif; ?>				
                    <?php
                    if (
                            $this->loggedAllowed('report-global', 'management:enterprise') or
                            $this->loggedAllowed('report-regional', 'management:enterprise') or
                            $this->loggedAllowed('report-categoria', 'management:enterprise') or
                            $this->loggedAllowed('report-regional', 'management:enterprise') or
                            $this->loggedAllowed('report-inscricoes', 'management:enterprise') or
                            $this->loggedAllowed('report-status-appraiser', 'management:enterprise') or
                            $this->loggedAllowed('report-status-verificador', 'management:enterprise') or
                            $this->loggedAllowed('report-categoria-premio', 'management:enterprise')
                    ):
                        ?>
                        <li class="submenu"><a href="#" onClick="return false;" class="cancel-modal">Relatórios</a>

                            <ul>
                                <?php if ($this->loggedAllowed('report-categoria', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-categoria') ?>">Participantes por Setor</a></li>
                                <?php endif; ?>
                                <!--<?php if ($this->loggedAllowed('report-digitador', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-digitador') ?>">Participantes por Digitador</a></li>
                                <?php endif; ?>-->
                                <?php if ($this->loggedAllowed('report-regional', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-regional') ?>">Participantes por Escritório Regional</a></li>
                                <?php endif; ?>
                                <!--<?php if ($this->loggedAllowed('report-inscricoes', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-inscricoes') ?>">Preenchimento de Inscrições</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('report-global', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-global') ?>">Panorama das Respostas</a></li>
                                <?php endif; ?>-->
                                <?php if ($this->loggedAllowed('report-status-appraiser', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-status-appraiser') ?>">Status da Avaliação</a>                               </li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('report-status-verificador', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-status-verificador') ?>">Status da Verificação</a></li>
                                <?php endif; ?>
                                <?php if ($this->loggedAllowed('report-categoria-premio', 'management:enterprise')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/enterprise/report-categoria-premio') ?>">Participantes por Categoria</a></li>
  <?php endif; ?>

                            </ul>

                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('index', 'management:user')): ?>
                        <li class="submenu"><a href="<?php echo $this->baseUrl('management/user') ?>" title="Usuários">Usuários</a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl('management/user') ?>" title="Listagem de usuários">Listagem</a></li>
                                <?php if ($this->loggedAllowed('insert', 'management:user')): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/user/insert') ?>" title="Criar usuário">Criar usuário</a></li>
    <?php endif; ?>
                                <?php if ($appraiserUserManagementAllowed ): ?>
                                    <li><a href="<?php echo $this->baseUrl('management/appraiser-user') ?>" title="Aprovação de Avaliadores/Verificadores">Aprovação de Avaliadores/Verificadores</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('index', 'management:regional')): ?>
                        <li class="submenu">
                            <a href="<?php echo $this->baseUrl('management/regional') ?>">Regionais</a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl('management/regional') ?>" title="Listagem de regionais">Listagem</a></li>
    <?php if ($this->loggedAllowed('insert', 'management:regional')): ?>
                                    <li class="">
                                        <a href="<?php echo $this->baseUrl('management/regional/insert') ?>">Criar regional</a>
                                    </li>
    <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('index', 'management:glossary')): ?>
                        <li class="submenu">
                            <a href="<?php echo $this->baseUrl('management/glossary'); ?>">Glossário</a>
                            <ul>
    <?php if ($this->loggedAllowed('insert', 'management:glossary')): ?>
                                    <li class="">
                                        <a href="<?php echo $this->baseUrl('management/glossary/insert') ?>">Criar termo</a>
                                    </li>
    <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('index', 'management:configuration')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/configuration') ?>">Configurações</a>
                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('index', 'management:role')): ?>
                        <li class="submenu">
                            <a href="<?php echo $this->baseUrl('management/role') ?>">Perfis Sistema</a>  <?php // leia-se: Papeis    ?>
                            <ul>
    <?php if ($this->loggedAllowed('insert', 'management:role')): ?>
                                    <li class="">
                                        <a href="<?php echo $this->baseUrl('management/role/insert') ?>">Criar perfil</a> <?php // leia-se: Criar papel    ?>
                                    </li>
    <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('index', 'management:group')): ?>
                        <li class="link <?php echo $controller == 'group' ? 'current' : ''; ?>">
                            <a href="<?php echo $this->baseUrl('management/group') ?>">Grupo</a>
                            <ul>
    <?php if ($this->loggedAllowed('insert', 'management:group')): ?>
                                    <li class="">
                                        <a href="<?php echo $this->baseUrl('management/group/insert') ?>">Criar Grupo</a>
                                    </li>
    <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>

<?php if ($this->loggedAllowed('files', 'management:enterprise')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/enterprise/files') ?>">Espaço do Gestor</a>
                        </li>
<?php endif; ?>
                </ul>
            </div>

            <div class="container12">
                <div class="header">
                    <h1 id="logo"><a href="<?php echo $this->baseUrl('/questionnaire'); ?>" title="Prêmio Sebrae Mulher de Negócios">Prêmio Sebrae Mulher de Negócios</a></h1>
<!--                     <div id="breadcrumb"> -->
<!--                         <p>Você está em:</p> -->
<!--                         <ul> -->
<!--                             <li><a href="" title="Mulher de Neg&oacute;cios 2015"><span>Mulher de Neg&oacute;cios 2015</span></a></li> -->
                            <?php /* ?>
//                             <li class="current"><span><i>Avaliação</i></span></li>
//                             <?php */ ?>
<!--                         </ul> -->
<!--                     </div> -->

<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                        <div id="profile">
                            <dl>
                                <dt><b><?php echo $this->userAuth()->getFirstName(); ?></b></dt>
                                <dd><?php echo $this->userAuth()->getRoleLongDescription(); ?></dd>
                            </dl>
                            <ul>
                                <li class="logout"><a href="<?php echo $this->baseUrl('login/logout'); ?>" title="Sair">Sair</a></li>
                            </ul>
                        </div>
<?php endif; ?>
                </div>
