    </div>
  </div>
<div class="footer">
	<div class="inner-footer">
		<div id="signature">
			<p><!--<a href="" class="vorttex" name="Vorttex Tecnologia" tabindex="-1">Vorttex Tecnologia</a>--> 	&copy; <strong> - 2015</strong> Todos os direitos reservados.</p>
		</div>

        <figure style="float:left;width: 50%;margin: 30px 0px 0px 50px">
            <img style="width:670px" src="<?php echo $this->baseUrl('portal-assets/images/logos_psmn.png'); ?>" class="float--right" alt="logos">
        </figure>

	</div>
</div>
        <div id="search-cnae" style="display:none;">
          <div id="signup-ct">
            <div id="signup-header" style="padding: 14px 18px 10px">
              <h2 style="font-size: 1.6em">Buscar CNAE</h2>
              <!--p>ache pelo nome ou número</p-->
              <a class="modal_close" href="#">X</a>
            </div>
            <div class="modal-form-area">
              <form action="?" name="cnae" method="GET" class="form-default"  id="form-search-cnae">
                <input type="hidden" name="envia" value="s">
                <label class="label-1-2" style="float: left; width: 425px;">
                  <span class="info">Encontre pelo número CNAE ou parte do nome</span>
                  <input type="text" id="busca-cnae" name="busca" value="" required minlength="3" autocomplete="false" class="input">
                </label>
                <button id="busca-cnae-button" type="submit" id="modal-button-search-cnae" class="btn-submit">Buscar</button>
              </form>
              <div style="padding-top: 1px" id="cnae-list-container"></div>
            </div>
          </div>
        </div>
<div id="overlay1" class="ui-widget-overlay" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%;
    z-index: 9999;
    background: #86A9A9 50% 50% repeat; opacity: .15;filter:Alpha(Opacity=15);
    background-image: url('<?php echo $this->baseUrl('img/jui/ui-bg_diagonals-thick_100_aaaaaa_40x40.png') ?>')"></div>
<script type="text/javascript">
//<![CDATA[
    var BASE_URL = '<?php echo $this->baseUrl() ?>';
    var APPLICATION_ENV = '<?php echo APPLICATION_ENV ?>'
//]]>
</script>

<?php if (in_array(APPLICATION_ENV, array('production', 'staging'))): ?>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php endif; ?>
<script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('js/jquery-1.9.1.min.js') ?>"><\/script>')</script>
<script src="<?php echo $this->baseUrl('js/jquery-migrate-1.1.0.js') ?>"></script>
<script src="<?php echo $this->baseUrl('assets/javascripts/vendors/underscore.js') ?>"></script>

<script src="<?php echo $this->baseUrl('js/kickstart.js?v2') ?>"></script>
<!--
<script src="<?php echo $this->baseUrl('assets/javascripts/common.js') ?>"></script>
<script data-main="/assets/javascripts/common.js" src="/assets/javascripts/libs/require/require.js"></script>
-->
<?php echo $this->headScript() ?>

<?php if (in_array(APPLICATION_ENV, array('production', 'staging'))): ?>
<script>
    var _gaq = _gaq || [];  _gaq.push(['_setAccount', 'UA-52715647-1']);  _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    (function() {
    var h ='br-sebrae.netmng.com';
    var a = '2415';
    var t = document.createElement('script');
    t.type = 'text/javascript'; t.async = true;
    var p = 'https:'==document.location.protocol?'https://':'http://';
    var m = document.referrer.match(/https?:\/\/([a-z]+\.[a-z\.]+)/i);
    var r = (m && m[1] != document.location.hostname) ? ('&ref=' + escape(document.referrer)) : '';
    t.src = p + h + '/?async=1&aid=' + a + r;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
})();
</script>
<?php endif; ?>
</body>
</html>