<?php
$request = $this->request();
$controller = $request->getControllerName();
$action = $request->getActionName();

header("Content-Type: text/html; charset=utf-8");
header("X-UA-Compatible: IE=edge,chrome=1");
?>
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt-br"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta chme="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Mulher de Negócios tem como objetivo identificar, selecionar e premiar os relatos de vida de mulheres empreendedoras, as quais transformaram seus sonhos em realidade e cuja história de vida hoje é exemplo para outras que possuem o mesmo sonho. " />

	<link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <link href="<?php echo $this->baseUrl('portal-assets/css/style.css?adasdv2014') ?>" media="all" rel="stylesheet" type="text/css" >
    <link rel="stylesheet" href="<?php echo $this->baseUrl('portal-assets/js/vendor/jquery/plugin/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css?v2014') ?>" media="all" type="text/css">

    <!--[if (gte IE 6)&(lte IE 8)]>
        <script src="<?php echo $this->baseUrl('assets/javascripts/libraries/html5shiv/html5shiv.js') ?>" type="text/javascript"></script>
    <![endif]-->
    
    <?php echo $this->headLink() . $this->headStyle(). "\n";
        $this->headTitle()->prepend('Mulher de Negócios - Prêmio Sebrae');
        echo /*$this->headMeta() .*/ $this->headTitle()->setSeparator(' - ');
    ?><link href="/favicon.ico" rel="shortcut icon" />

    <?php
      include_once 'facebook_pixels/base.phtml';
      include_once 'facebook_pixels/remarketing.phtml';
    ?>
</head>
<body>
    <?php include 'google_analytics/base.phtml' ?>
    <?php include 'google_analytics/remarketing.phtml' ?>