    <div id="overlay1" class="ui-widget-overlay"></div> 
    <footer role="contentinfo" class="theFooter cf">
        <section class="wrapper cf">
            <!--<a href="http://www.vorttex.com.br/" id="footer-vorttex-logo" target="_blank">Vorttex</a>-->
            <figure>
                <img style="width:35%" src="<?php echo $this->baseUrl('portal-assets/images/logos_psmn.png'); ?>" class="float--right" alt="logos">
            </figure>
        </section>
    </footer>
<script type="text/javascript">
//<![CDATA[
    var BASE_URL = '<?php echo $this->baseUrl() ?>';
    var APPLICATION_ENV = '<?php echo APPLICATION_ENV ?>'
//]]>
</script>
<?php if (APPLICATION_ENV != 'development'): ?>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php endif; ?>
<script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('js/jquery-1.9.1.min.js') ?>"><\/script>')</script>
<script src="<?php echo $this->baseUrl('js/jquery-migrate-1.1.0.js') ?>"></script>
<script src="<?php echo $this->baseUrl('js/kickstart.js?v2') ?>"></script>

    <!-- Selectivizr -->
    <!--[if (gte IE 6)&(lte IE 8)]>
        <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/selectivizr.js'); ?>" type="text/javascript"></script>
    <![endif]-->

    <!-- GreenSock -->
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/greensock/plugins/CSSPlugin.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/greensock/easing/EasePack.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/greensock/TweenLite.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/greensock/jquery.gsap.min.js'); ?>"></script>
    <!-- plugins -->
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/jquery/plugin/rf/jquery.rf.slideshow.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/jquery/plugin/rf/jquery.rf.slideshownav.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('portal-assets/js/vendor/jquery/plugin/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js'); ?>"></script>

    <!-- scripts -->
    <script src="<?php echo $this->baseUrl('portal-assets/js/helper.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('portal-assets/js/main.js'); ?>"></script>
    
    <script>
        //<![CDATA[
        $.fn.ready(function() {
            try {
                $('.senha').hide();
                $('#auth_login').off('keypress').off('keydown').off('keyup').on('keyup', function(e){
                    var $username = $(e.target),
                        $val = this.value.replace(/\D/g,''),
                        $len = $val.length;
                    if ($len >= 2 && (parseInt($val) || $val === '00') && !$username.hasClass('masked')) {
                        $username.addClass('masked').inputmask("mask", {"mask": "999.999.999-99"});
                    } else if ($len < 2 && $username.hasClass('masked')) {
                        $username.removeClass('masked').inputmask('remove');
                    }
                });
                
                $('#frmLogin').on('submit', function(e){
                    e.preventDefault();
                    var $form = $(this);
                    //cache false
                    $.post(
                        $form.attr('action') + 'format/json/', $form.serialize(),
                        function(data) {
                            if (typeof data.cpfValid !== 'undefined' && !data.cpfValid) {
                                alert('CPF inválido.');
                                return;
                            }
                            if (typeof data.existe !== 'undefined' && data.existe && $('.senha:visible').size() === 0) {
                                $('.senha').show();
                                $('input.senha').focus();
                                return;
                            }
                            if (data.messageError) {
                                alert(data.messageError);
                                return;
                            }
                            if ((data.existe && data.urlForward) || (data.cpfValid && !data.existe)) {
                                window.location.assign(data.urlForward);
                                window.location.href = data.urlForward;
                            }
                        }
                    )
                });

            } catch(e) {
                if (APPLICATION_ENV != 'development') {
                    console.log(e);
                    document.write ("Outer catch caught <br/>");
                    Sescoop.error(e.message);
                    return;
                }
                throw e;
            }
        });
        //]]>
    </script> 

<?php echo $this->headScript() ?>

<?php if (in_array(APPLICATION_ENV, array('production', 'staging'))): ?>
    <script>
        var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-52715647-1']); _gaq.push(['_trackPageview']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
        (function() {
        var h ='br-sebrae.netmng.com';
        var a = '2415';
        var t = document.createElement('script');
        t.type = 'text/javascript'; t.async = true;
        var p = 'https:'==document.location.protocol?'https://':'http://';
        var m = document.referrer.match(/https?:\/\/([a-z]+\.[a-z\.]+)/i);
        var r = (m && m[1] != document.location.hostname) ? ('&ref=' + escape(document.referrer)) : '';
        t.src = p + h + '/?async=1&aid=' + a + r;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
        })();
    </script>
<?php endif; ?>
</body>
</html>