<?php
$this->headScript()->appendFile($this->baseUrl('js/management/avaliacao_PontosFortes.js?xxxe1'));

$addressEnterprise = $this->enterprise->findAddressEnterprise()->current();
$enterpriseState = $addressEnterprise->findParentState();
$model_apevaluationverificador = new Model_ApeEvaluationVerificador();


$blocoAnterior = ''; 
$criterioAnterior = '';
$qsts = array();
$blocos = array();
$criterios = array(); 

 

//Questoes
foreach ($this->questoes as $k => $questao):
    $bloco = $questao->getBloco();
    $criterio = $questao->getCriterio();
    if ($bloco != $blocoAnterior) {
        $qsts[$bloco] = array(
            'BlockName' => Vtx_Util_PsmnAvaliacao::BlocosAvaliacao($bloco), 'Criterions' => array()
        );
    }
    if ($criterio != $criterioAnterior) {
        $qsts[$bloco]['Criterions'][$criterio] = array(
            'CriterionValue' => Vtx_Util_PsmnAvaliacao::CriteriosAvaliacao($bloco, $criterio),
            'Questions' => array()
        );
    }
    $qsts[$bloco]['Criterions'][$criterio]['Questions'][$questao->getId()] = $questao;
    $blocoAnterior = $bloco;
    $criterioAnterior = $criterio;
endforeach;
?>

<h1 class="title">
	<a name="anchor"></a>VERIFICADOR - Critério de Avaliação
</h1>


<?php if ($this->finalizacaoErro): ?>
<h3
	style="color: #ED7C4C; font: bold 19px 'Lato'; margin-bottom: 22px; margin-top: 28px; background-color: #FCFC8D">Avaliação
	salva, porém não foi possível finalizá-la. Faltam respostas em '4.
	Avaliação' ou comentários, verifique.</h3>
<?php elseif ($this->conclusaoErro): ?>
<h3
	style="color: #ED7C4C; font: bold 19px 'Lato'; margin-bottom: 22px; margin-top: 28px; background-color: #FCFC8D">Avaliação
	salva, porém não foi possível finalizá-la. Uma observação é obrigatória
	no final da página.</h3>
<?php endif; ?>
<form action="" method="POST" id="frmAvaliacao" class="avaliacao">

	<fieldset>
		<input type="hidden" id="" name="" value="" />
	</fieldset>
	<fieldset>
		<div class="list-table-20">
			<label class="label-control">CNPJ</label> <span class="label-value"><?php echo $this->enterprise->getFormattedCnpj(); ?></span>
		</div>

		<div class="list-table-20">
			<label class="label-control">Candidata</label> <span
				class="label-value"><?php echo $this->president->getName(); ?></span>
		</div>

		<div class="list-table-20">
			<label class="label-control">Estado</label> <span class="label-value"><?php echo $enterpriseState->getUf(); ?></span>
		</div>

		<div class="list-table-20">
			<label class="label-control">Categoria</label> <span
				class="label-value"><?php if ($this->enterprise->getCategoryAwardId()) echo Vtx_Util_Array::categoriaPsmn($this->enterprise->getCategoryAwardId()) ?></span>
		</div>

	</fieldset>
	<a id="verRelato"
		href="<?php echo $this->baseUrl('management/verificacao/report/enterprise-id-key/' . $this->enterprise->getIdKey()); ?>#report"
		target="_blank" title="Ver relato"><span>Ver<i> relatório interno</i></span></a>

	<h2 class="subtitle" style="">
		Critérios, requisitos e itens <span>Necessário salvar os dados no
			final da página.</span>
	</h2>


	<div id="avaliacaoRelato" class="inner-content" style="margin-top: 0">
		<ul class="root">

			<li class="macro">
				<p class="title">
					<b style="margin-top: 15px" class="topic">Verificação</b> <span
						class="score">Nota: <i class="total"> </i>
					</span>
				</p>
				<ul>
					<li class="micro">
						<ol class="answers">                   
                    <?php foreach ($this->questionsAvaliacao as $questionAvaliacao): ?>
                    
                      <li data-weight="20" id="question-1"
								class="question">
								<div style="width: 410px;min-height: 54px; 
                          <?php echo (isset($this->evaluationQuestionsError[$questionAvaliacao->getId()])? 'background-color: #FCFC8D"' : ''); ?>" class="texto">
                                <?php echo $questionAvaliacao->getValue(); ?>
                          </div>
								<div class="answer-option"
									style="min-height: 54px; width: 110px;">
                               <?php
                               
                               //echo $this->enterprise->getId();
                               //var_dump($this->respostas[$questionAvaliacao->getId()]);exit;
                                //$checked = "";
                                //$resposta = $model_apevaluationverificador->verificaRespostaCriterio($this->enterprise->getId(),$this->respostas[$questionAvaliacao->getId()],null);
                               // $checked = (isset($resposta) and $resposta[$this->respostas[$questionAvaliacao->getId()]] == 'F')? ' checked="checked"' : '';  
                                ?>                         
                                <?php
                                   $checked = (isset($this->respostas[$questionAvaliacao->getId()]['QuestionCheckerId']) && $this->respostas[$questionAvaliacao->getId()]['Resposta'] == 'F')? ' checked' : '';
                                ?>                                
                              <input <?php echo $checked; ?>
										type="radio" data-percentage="10" class="option radio"
										id="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-F"
										name="ansAvaliacao[<?php echo $questionAvaliacao->getId(); ?>]"
										value="F"> <label class="label-inline radio checked"
										for="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-F"
										style="background: none !important;"> Ponto forte </label>
								</div>
								<div class="answer-option"
									style="min-height: 54px; width: 170px; border-right: none">
                                <?php
                                    $checked = (isset($this->respostas[$questionAvaliacao->getId()]) and $this->respostas[$questionAvaliacao->getId()]['Resposta'] == 'M')? ' checked' : '';
                                ?>
                              <input <?php echo $checked; ?>
										type="radio" data-percentage="0" class="option radio"
										id="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-M"
										name="ansAvaliacao[<?php echo $questionAvaliacao->getId(); ?>]"
										value="M"> <label class="label-inline radio"
										for="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-M">
										Oportunidade de melhoria </label>
								</div>

							</li>
                   <?php endforeach; ?>
                </ol>
					</li>

				</ul>
			</li>

		</ul>
		</li>
		</ul>
		<div class="complement" style="margin-top: 15px">
			<h2 class="subtitle">
				<label for="conclusao" style="font: bold 18px 'Lato'; margin-bottom: 22px; margin-top: 28px;<?php if ($this->conclusaoErro): ?>  background-color: #FCFC8D<?php endif; ?>">Comentários
					gerais</label>
			</h2>
			<textarea id="conclusao" name="conclusao"
				style="width: 100%; height: 135px"><?php echo isset($this->conclusao)? $this->conclusao : ''; ?></textarea>
		</div>
		<div class="complement">
			<button class="large btn-submit" type="submit"
				style="background-color: #7D5977; margin-right: 10px">
				<b>Salvar</b>
			</button>
		</div>
	</div>
</form>
