<?php
$this->headScript()
  ->appendFile($this->baseUrl('js/management/avaliacao.js?xxxe1'));

$addressEnterprise = $this->enterprise->findAddressEnterprise()->current();
$enterpriseState = $addressEnterprise->findParentState();

$blocoAnterior = ''; 
$criterioAnterior = '';
$qsts = array();
$blocos = array();
$criterios = array(); 
$respostas = array(); 
$avaliadorResposta = $this->verificacaoAvaliador;
 

//echo('<pre>');
//print_r($this->questoes);
//echo('</pre>');	exit;



//print_r($this->verificacaoAvaliador);exit;

function resposta($array,$value) {
   $filtered = false;
   $member = "AvaliacaoPerguntaId";
 
   foreach($array as $k => $v) {

      if($v["AvaliacaoPerguntaId"] == $value)
         $filtered = $v["Resposta"];
   }

    return $filtered;
}

function comentario($array,$value) {
   $filtered = false;
   $member = "CriterioNumber";

   foreach($array as $k => $v) {

      if($v["CriterioNumber"] == $value)
         $filtered = $v["Comment"];
   }

    return $filtered;
}


//echo('<pre>');
//13_r($this->verificacaoAvaliador);
//echo('</pre>');
//	exit;

//Questoes
foreach ($this->questoes as $k => $questao):
	    $questaoLetra = $questao->getQuestaoLetra();    
	    $bloco = $questao->getBloco();
	    $criterio = $questao->getCriterio();

    if ($bloco != $blocoAnterior) {
        $qsts[$bloco] = array(
            'BlockName' => Vtx_Util_PsmnAvaliacao::BlocosAvaliacao($bloco), 'Criterions' => array()
        );
    }
    if ($criterio != $criterioAnterior) {
        $qsts[$bloco]['Criterions'][$criterio] = array(
            'CriterionValue' => Vtx_Util_PsmnAvaliacao::CriteriosAvaliacao($bloco, $criterio),
            'Questions' => array()
        );
    }
    $qsts[$bloco]['Criterions'][$criterio]['Questions'][$questao->getId()] = $questao;
    $blocoAnterior = $bloco;
    $criterioAnterior = $criterio;
  
endforeach;        
?>

<?php
?>
<h1 class="title"><a name="anchor"></a>VERIFICADOR - Avaliação do Relato</h1>
<form action="" method="POST" id="frmAvaliacao" class="avaliacao">

  <fieldset>
    <input type="hidden" id="" name="" value="" />
  </fieldset>
  <fieldset>
    <div class="list-table-20">
      <label class="label-control">CNPJ</label>
      <span class="label-value"><?php echo $this->enterprise->getFormattedCnpj(); ?></span>
    </div>

    <div class="list-table-20">
      <label class="label-control">Candidata</label>
      <span class="label-value"><?php echo $this->president->getName(); ?></span>
    </div>

    <div class="list-table-20">
      <label class="label-control">Estado</label>
      <span class="label-value"><?php echo $enterpriseState->getUf(); ?></span>
    </div>

    <div class="list-table-20">
      <label class="label-control">Categoria</label>
      <span class="label-value"><?php if ($this->enterprise->getCategoryAwardId()) echo Vtx_Util_Array::categoriaPsmn($this->enterprise->getCategoryAwardId()) ?></span>
    </div>

  </fieldset>
    <a id="verRelato" href="<?php echo $this->baseUrl('management/verificacao/report/enterprise-id-key/' . $this->enterprise->getIdKey()); ?>#report" target="_blank" title="Ver relato"><span>Ver<i> relatório interno</i></span></a>
    
  <h2 class="subtitle" style="">Critérios, requisitos e itens     <span>Necessário salvar os dados no final da página.</span></h2>

  <div id="avaliacaoRelato"class="inner-content" style="margin-top: 0">
    <ul class="root">
    
 <?php foreach ($qsts as $blockId => $bloco): ?>
    <li class="macro closed">
        <p class="title">
          <b class="topic" style="<?php echo (isset($this->questionsError[$blockId])? 'background-color: #FCFC8D"' : ''); ?>"><?php echo $bloco['BlockName']; ?></b>
          <a href="" class="help" title="<?php echo Vtx_Util_PsmnAvaliacao::CriteriosInfo($blockId, 0 ); ?>">Saiba mais</a>
          <span class="score">Nota: <i class="total">0</i></span>
          <a href="" class="toggle" title="Alternar">Alternar</a>
        </p>

        <ul>
        <?php foreach ( $qsts[$blockId]['Criterions'] as $criterioId => $criterio): ?>
          <li class="micro closed">
            <p class="title">
              <b class="topic" style="<?php echo (isset($this->questionsError[$blockId][$criterioId])? 'background-color: #FCFC8D"' : ''); ?>"><?php echo $criterio['CriterionValue']; ?></b>
              <a href="" class="help" title="<?php echo Vtx_Util_PsmnAvaliacao::CriteriosInfo($blockId, $criterioId); ?>">Saiba mais</a>
              <span class="score">Nota: <i class="total">0</i></span>
              <a href="" class="toggle" title="Alternar">Alternar</a>
            </p>

            <ol class="answers">

        <?php
        $letras = array('A','B','C','D','E','F','G','H','I');
        $ii = 0;
        foreach ($qsts[$blockId]['Criterions'][$criterioId]['Questions'] as $questaoId => $questao):     
            ?>
          <li class="question" id="question-<?php echo $questaoId; ?>" data-weight="<?php echo $questao->getPeso(); ?>">
            <div class="texto" style="<?php echo (isset($this->questionsError[$blockId][$criterioId][$letras[$ii]])? 'background-color: #FCFC8D"' : ''); $ii++; ?>"><?php echo $questao->getQuestao(); ?></div>
            <div class="answer-option" style="font-size: 12px; text-align: left; border-right: none; width: 400px;">
                <?php echo nl2br($questao->getTopico()); ?>
            </div>
          <div class="answer-option">
		<b style="padding-left: 5px; width: 10%; color: #7D5977"> Resposta do Verificador</b>
	  </div>
          <div class="answer-option">

                  <?php
				  $idResposta  =null;
                  $idResposta = resposta($this->verificacaoAvaliador,$questaoId);
                  $checked = (isset($idResposta) and $idResposta == 'D') ? ' checked' : '';
                  ?>                                             
                <input <?php echo $checked; ?>
                    type="radio" data-percentage="0" class="option radio"
                    id="question-<?php echo $blockId; ?>-<?php echo $criterioId ; ?>-<?php echo $questaoId; ?>-a"
                    name="ans[<?php echo $questaoId; ?>]"
                    value="1">
                  <label style="background: none !important;" for="question-<?php echo $blockId; ?>-<?php echo $criterioId ; ?>-<?php echo $questaoId; ?>-a" class="label-inline radio">
                    Não Evidenciado
                  </label>
                  <?php // Dificilmente acontece ?>
                </div>
                <div class="answer-option">
                  <?php
				   $idResposta  ='';
                     $idResposta = resposta($this->verificacaoAvaliador,$questaoId);
				 
                  $checked = (!empty($idResposta) and $idResposta == 'A') ? ' checked' : '';
                  ?>
                  <input type="radio" value="2"<?php echo $checked;?> name="ans[<?php echo $questaoId; ?>]" id="question-<?php echo $blockId; ?>-<?php echo $criterioId ; ?>-<?php echo $questaoId; ?>-b" class="option radio" data-percentage="50" />
                  <label for="question-<?php echo $blockId; ?>-<?php echo $criterioId ; ?>-<?php echo $questaoId; ?>-b" class="label-inline radio">
                    Levemente Evidenciado
                  </label>
                  <?php // Ás vezes acontece ?>
                </div>
                <div class="answer-option">
                
                  <?php
				   $idResposta  ='';
                   $idResposta = resposta($this->verificacaoAvaliador,$questaoId);
                  $checked = (!empty($idResposta) and $idResposta == 'S') ? ' checked' : '';
                  ?>
                  <input type="radio" value="3" <?php echo $checked;?> name="ans[<?php echo $questaoId; ?>]" id="question-<?php echo $blockId; ?>-<?php echo $criterioId ; ?>-<?php echo $questaoId; ?>-c" class="option radio" data-percentage="100" />
                  
                  
                  <label for="question-<?php echo $blockId; ?>-<?php echo $criterioId ; ?>-<?php echo $questaoId; ?>-c" class="label-inline radio">
                    Fortemente Evidenciado
                  </label>
                  <?php // Sempre acontece ?>
                </div>
                  <div class="answer-report-mentions">
                  <dl class="report-mentions">                    
                  </dl>
                </div>              
         </li>
        <?php endforeach; ?>                
          <li class="">
            <div class="answer-option" style="text-align: left; border-right: none; width: 473px; background-color: #fff;  font-size: 17px; font-weight: bold;
                font-style: italic;
                text-align: left;
                width: 100%;">
                <b style=" padding-left: 10px; width: 100%/* color: rgb(237, 118, 69);*/"> Comentários (<?php echo $criterio['CriterionValue']; ?>)</b>
                <div class="texto" style="background-color: #fff;  width: 100%; margin-left: 0; border-right: none; ">
                    
                                        <textarea name="comments[<?php echo "$blockId$criterioId"; ?>]" style="width: 100%; height: 90px"><?php  $comment ='' ; $comment = comentario($this->comentarioVerificador,"$blockId$criterioId"); echo  (isset($comment)? $comment : ''); ?></textarea>
                                        
                </div>
            </div>
              </li>                     
            </ol>
          </li>
        <?php endforeach; ?>                   
        </ul>
      </li>
      <?php endforeach; ?>
    </ul>
        <div class="complement">
            <input id="finalizar" type="hidden" name="finalizar" value="0" />
            <button class="large btn-submit" type="submit" style="background-color: #7D5977; margin-right: 10px"><b>Salvar</b></button>     
         </div>
    </div>
</form>
