<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="">
    <h1 class="center">
        Questões ::
        <?php echo ($this->request()->getActionName() == 'insert')? 'Inserir' : 'Editar'; ?>
    </h1>
    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/criterion/'); ?>">Voltar</a>

    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>

    <form class="normal" method="POST" 
          action="<?php echo $this->baseUrl(($this->request()->getActionName() == 'insert')? 'management/question/insert' : 'management/question/edit/id/' . $this->questionRow->getId()); ?>">

            <input type="hidden" name="status" id="question_status" value="<?php if ($this->questionRowData) { echo $this->questionRowData['status']; } else { echo 'A'; } ?>">
            <input type="hidden" name="version" id="question_version" value="<?php if ($this->questionRowData) { echo $this->questionRowData['version']; } else { echo '1'; } ?>">

        <fieldset>
            <label for="parent_id">Critério: </label>
                <select name="parent_id" id="parent_id" class="fancy">
                    <?php foreach ($this->getAllCriterion as $key => $value) : ?>
                        <?php if ($this->questionRowData['parent_id'] == $value->getId()) : ?>
                            <option value="<?php echo $value->getId(); ?>" selected="selected"> <?php echo $value->getValue(); ?> </option>
                        <?php else : ?>
                            <option value="<?php echo $value->getId(); ?>"> <?php echo $value->getValue(); ?> </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />
            
            <label for="designation">Ordem: </label>
                <select name="designation" id="question_designation" class="fancy">
                    <?php foreach ($this->getDesignationQuestion as $key => $value) : ?>
                        <?php if ($this->questionRowData['designation'] == $value) : ?>
                            <option value="<?php echo $key; ?>" selected="selected"> <?php echo $value; ?> </option>
                        <?php else : ?>
                            <option value="<?php echo $key; ?>"> <?php echo $value; ?> </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />
            
            <label for="question_type_id">Tipo de questão: </label>
                <select name="question_type_id" id="question_question_type_id" class="fancy">
                    <?php foreach ($this->getAllQuestionType as $key => $value) : ?>
                    
                        <?php if ($this->questionRowData['question_type_id'] == $value->getId()) : ?>
                            <option value="<?php echo $value->getId();?>" selected="selected"> <?php echo $value->getDescription();?> </option>
                        <?php else : ?>
                            <option value="<?php echo $value->getId();?>"> <?php echo $value->getDescription();?> </option>
                        <?php endif; ?>
                    
                    <?php endforeach; ?>
                </select>
            <br class="clear" />
            
            <label for="value">Descrição: </label>
                <input type="text" name="value" id="question_value" value="<?php if ($this->questionRowData) { echo $this->questionRowData['value']; } ?>">
            <br class="clear" />
            
            <label>Texto de apoio: </label>
                <textarea name="supporting_text" id="question_supporting_text"><?php if ($this->questionRowData) { echo $this->questionRowData['supporting_text']; } ?></textarea>
        </fieldset>

        <div class="clear"> </div>
        <button type="submit" class="save">Finalizar</button>
        <div class="clear"> </div>
	</form>
</div>