
<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="">
   <h1 class="center">Cadastro de Pontuação de Questão/Alternativa</h1>
   <?php if ($this->crudMessageSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php 
                        echo $this->crudMessageSucess; 
                    ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
    
    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif;?>
    <form method="POST" action="<?php echo $this->baseUrl('management/score-definition/index'); ?>">
        <select name="question_id" id="id_question" class="fancy" onchange="javascript:this.form.submit();">
            <option value="">Escolha uma Questão</option>
            <?php foreach ($this->questions as $key => $value) : ?>
                <?php if (isset($this->dataForm['question_id']) && $this->dataForm['question_id'] == $value->getId()) : ?>
                    <option value="<?php echo $value->getId();?>" selected="selected"><?php echo $value->getDesignation()." - ".$value->getValue();?></option>
                <?php else : ?>
                    <option value="<?php echo $value->getId();?>"><?php echo $value->getDesignation()." - ".$value->getValue();?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    </form>
    <form method="POST" action="<?php echo $this->baseUrl('management/score-definition/edit'); ?>">
        <input type="hidden" name="question_id" id="id_question" value="<?php echo $this->dataForm['question_id']; ?>">
        <br class="clear" />
        <?php
        if(count($this->dataFormAlt) > 0) :
        ?>
        <table class="striped " border="0" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th> </th>
                    <th>Questão</th>
                    <th>Descrição</th>
                    <th>Pontuação</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if($this->dataFormAlt) :
                    foreach ($this->dataFormAlt as $key => $alternative):
                ?>
                    <tr>
                        <td><?php echo $alternative->getDesignation(); ?></td>
                        <td><?php echo $alternative->findParentQuestion()->getDesignation(); ?></td>
                        <td><?php echo $alternative->getValue(); ?></td>
                        <td>
                            <input type="text" name="<?php echo "score_alt_".$alternative->getId() ?>" id="<?php echo "score_alt_".$alternative->getId() ?>" style="width:50px" value="<?php echo $alternative->getScoreLevel(); ?>">
                        </td>
                    </tr>
                <?php 
                    endforeach; 
                endif;
                ?>
            </tbody>
        </table>
        <div class="clear"> </div>
        <button type="submit" class="save">Finalizar</button>
        <div class="clear"> </div>
        <?php
        endif;
        ?>
    </form>
    <br \>
    <br \>
    <br \>
    <br \>
    <br \>
    <br \>
</div>


