      <ul class="main-menu">
           <li class="active inscricao">
            <a class="link" href="javascript:void(0)">Inscri&ccedil;&atilde;o</a>
           </li>
           <li class="inactive relato">
            <a class="link" href="javascript:void(0)">Relato</a>
           </li>
           <li class="inactive questionario">
            <a class="link" href="javascript:void(0)">Questionario</a>
           </li>
         </ul>   
