<?php

$controller = $this->request()->getControllerName();
$action = $this->request()->getActionName();

//print_r($controller);
//print_r($action);


$idKey = ($this->enterpriseIdKey)?true:false;
$linkCadastro = ($idKey)?'edit/id_key/'.$this->enterpriseIdKey:'cadastro';
$request = $this->request();
$currentBlockIdNegocios = Zend_Registry::get('configDb')->qstn->currentBlockIdNegocios;
$programaId = Zend_Registry::get('configDb')->competitionId;
if ($idKey) {
    $arrEtapas = $this->terminoEtapas();
}

?>
<ul class="main-menu" style="left: -91px; top: 0">
<?php
if ($this->loggedAllowed('not-coop-responding', 'management:questionnaire')
    or $this->loggedAllowed('acompanhareport', 'management:report')): ?>

    <?php if ($idKey): ?>

            <?php
                if ($this->loggedAllowed('not-coop-responding', 'management:questionnaire')) {
                    $url = 'management/enterprise/'.$linkCadastro;
                } else {
                    $url = 'management/enterprise/acompanhacadastro/id_key/'.$this->enterpriseIdKey.'/programa_id/'.$programaId;
                }
            ?>
    
        <li class="<?php echo $controller == 'register'? 'active ' : ''; ?>inscricao">
            <a class="link" href="<?php echo $this->baseUrl($url);?>" title="Editar Dados da Candidata e da Empresa">Editar Dados
                <?php if ($idKey): ?><span class='warning done'></span><?php endif; ?></a>
        </li>
        
            <?php
                if ($this->loggedAllowed('not-coop-responding', 'management:questionnaire')) {
                    $url = 'management/questionnaire/not-coop-responding/enterprise-id-key/'
                        . $this->enterpriseIdKey.'/block/'
                        . Zend_Registry::get('configDb')->qstn->currentBlockIdEmpreendedorismo;
                } else {
                    $url = 'management/questionnaire/acompanhqstn/enterprise-id-key/'
                        . $this->enterpriseIdKey.'/block/'
                        . Zend_Registry::get('configDb')->qstn->currentBlockIdEmpreendedorismo;
                }
            ?>
        <?php /* ?>
        <li class="<?php echo ($controller == 'respond' and $currentBlockIdEmpreendedorismo == $request->getParam('block'))? 'active ' : ''; ?>questionario-empreendedorismo">
            <a class="link" href="<?php echo $this->baseUrl($url);?>" title="Questionário Empreendedorismo">Questionário Empreendedorismo 
                <?php if ($arrEtapas['empreendedorismo']) { echo "<span class='warning done'></span>"; } ?>
            </a>
        </li>
        <?php */ ?>
        
            <?php
                if ($this->loggedAllowed('not-coop-responding', 'management:questionnaire')) {
                    $url = 'management/questionnaire/not-coop-responding/enterprise-id-key/'
                        . $this->enterpriseIdKey.'/block/'
                        . Zend_Registry::get('configDb')->qstn->currentBlockIdNegocios;
                } else {
                    $url = 'management/questionnaire/acompanhqstn/enterprise-id-key/'
                        . $this->enterpriseIdKey.'/block/'
                        . Zend_Registry::get('configDb')->qstn->currentBlockIdNegocios;
                }
            ?>

        <li class="<?php echo ($controller == 'respond' and $currentBlockIdNegocios == $request->getParam('block'))? 'active ' : ''; ?>questionario-negocios">
            <a class="link" href="<?php echo $this->baseUrl($url);?>" title="Questionário Negócios">Questionário Negócios 
             <?php if ($arrEtapas['negocios']) { echo "<span class='warning done'></span>"; } ?>
            </a>
        </li>
        
        <li class="<?php echo $controller == 'report'? 'active ' : ''; ?>relato">
            <?php
                if ($this->loggedAllowed('not-coop-responding', 'management:questionnaire')) {
                    $url = 'management/report/index/';
                } else {
                    $url = 'management/report/acompanhareport/';
                }
            ?>
            <a class="link" href="<?php
                    echo $this->baseUrl($url . 'enterprise-id-key/' . $this->enterpriseIdKey.'/programa_id/'.$programaId);
            ?>" title="Enviar Relato">Relato

             <?php if ($arrEtapas['relato']) { echo "<span class='warning done'></span>"; } ?>
            </a>
        </li>
            <?php if ($this->loggedAllowed('not-coop-responding', 'management:questionnaire')): ?>
                <li class="<?php echo ($controller == 'devolutive' and !$request->getParam('block'))? 'active ' : ''; ?>devolutiva">
                    <a class="link" href="<?php echo $this->baseUrl('/questionnaire/respond/index/geraDevolutiva/1/enterprise-id-key/'.$this->enterpriseIdKey.'/programa_id/'.$programaId);?>/menu-admin/1" title="Obter Relatório de Devolutiva">Obter Relatório de Devolutiva 
                     <?php if ($arrEtapas['devolutiva']) { echo "<span class='warning done'></span>"; } ?>
                    </a>
                </li>
            <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
</ul>   