<?php
return;

$controller = $this->request()->getControllerName();
$action = $this->request()->getActionName();

?>
<nav id="menu" role="navigation" style="background-image: url('/portal-assets/images/pattern.jpg')">
    <ul class="sideMenu">
        
        <?php if ($this->loggedAllowed('index', 'management:enterprise')): ?>
            <li class="link <?php echo $controller == 'enterprise'? 'current' : ''; ?>">
               <a href="<?php echo $this->baseUrl('management/enterprise') ?>">Empresas</a>
               <ul class="ulTab1">
                    <?php if ($this->loggedAllowed('cadastro', 'management:enterprise')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/enterprise/cadastro') ?>">Inscrever empresa</a>
                        </li>
                    <?php endif; ?>
               </ul>
            </li>
        <?php endif; ?>
            
        <?php if ($this->loggedAllowed('index', 'management:user')): ?>
            <li class="link <?php echo $controller == 'user'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/user') ?>">Usuários</a>
               <ul class="ulTab1">
                   <?php if ($controller == 'user' and $this->loggedAllowed('insert', 'management:user')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/user/insert') ?>">Criar usuário</a>
                        </li>
                    <?php endif; ?>
               </ul>
            </li>
        <?php endif; ?>
            
        <?php if ($this->loggedAllowed('index', 'management:appraiser')): ?>
            <li class="link <?php echo $controller == 'appraiser'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/appraiser') ?>">Associação de Avaliadores</a>
            </li>
        <?php endif; ?>
        


        <?php if ($this->loggedAllowed('index', 'management:regional')): ?>
            <li class="link <?php echo $controller == 'regional'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/regional') ?>">Regionais<br>Acesso por Localidade</a>
               <ul class="ulTab1">
                   <?php if ($controller == 'regional' and $this->loggedAllowed('insert', 'management:regional')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/regional/insert') ?>">Criar regional</a>
                        </li>
                    <?php endif; ?>
               </ul>
            </li>
        <?php endif; ?>

            
        <?php if ($this->loggedAllowed('index', 'management:glossary')): ?>
            <li class="link <?php echo $controller == 'glossary'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/glossary'); ?>">Glossário</a>
               <ul class="ulTab1">
                   <?php if ($controller == 'glossary' and $this->loggedAllowed('insert', 'management:glossary')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/glossary/insert') ?>">Criar termo</a>
                        </li>
                    <?php endif; ?>
               </ul>
            </li>
        <?php endif; ?>

        <?php if ($this->loggedAllowed('index', 'management:configuration')): ?>
            <li class="link <?php echo $controller == 'configuration'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/configuration') ?>">Configurações</a>
            </li>
        <?php endif; ?>
            
        <?php if ($this->loggedAllowed('index', 'management:role')): ?>
            <li class="link <?php echo $controller == 'role'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/role') ?>">Perfis Sistema</a>  <?php // leia-se: Papeis   ?>
               <ul class="ulTab1">
                   <?php if ($controller == 'role' and $this->loggedAllowed('insert', 'management:role')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/role/insert') ?>">Criar perfil</a> <?php // leia-se: Criar papel   ?>
                        </li>
                    <?php endif; ?>
               </ul>
            </li>
        <?php endif; ?>

        <?php if ($this->loggedAllowed('index', 'management:group')): ?>
            <li class="link <?php echo $controller == 'group'? 'current' : ''; ?>">
                <a href="<?php echo $this->baseUrl('management/group') ?>">Grupo</a>
               <ul class="ulTab1">
                   <?php if ($controller == 'group' and $this->loggedAllowed('insert', 'management:group')): ?>
                        <li class="">
                            <a href="<?php echo $this->baseUrl('management/group/insert') ?>">Criar Grupo</a>
                        </li>
                    <?php endif; ?>
               </ul>
            </li>
        <?php endif; ?>
            
            
        <?php if ($this->loggedAllowed('index', 'management:questionnaire')): ?>
            <li class="link <?php echo $controller == 'questionnaire'? 'current' : ''; ?>">
               <a href="<?php echo $this->baseUrl('management/questionnaire') ?>">Questionários</a>
               <ul class="ulTab1">
                   <?php if ($this->loggedAllowed('insert', 'management:questionnaire')): ?>
                        <li class="link <?php echo $action == 'insert'? 'current' : ''; ?>">
                            <a href="<?php echo $this->baseUrl('management/questionnaire/insert') ?>">Criar questionário</a>
                        </li>
                    <?php endif; ?>
                        
                    <?php if ($controller == 'questionnaire' and ($action == 'edit' or $action == 'manage')): ?>
                        <li class="openned">
                           <a href="#">Edição <?php if ($this->questionnaireRowData) { echo $this->questionnaireRowData['title']; } ?></a>
                           <ul class="ulTab1" style="padding-left: 17px;">
                               <li class="<?php echo ($controller == 'questionnaire' and $action == 'edit')? 'current' : ''; ?>"><a href="<?php echo $this->baseUrl('management/questionnaire/edit/id/' . $this->questionnaireId) ?>">Dados</a></li>
                               <li class="<?php echo ($controller == 'questionnaire' and $action == 'manage')? 'current' : ''; ?>"><a href="<?php echo $this->baseUrl('management/questionnaire/manage/questionnaire_id/'  . $this->questionnaireId) ?>">Questões</a></li>
                            <!--<li class="<?php echo ($action == 'peso')? 'current' : ''; ?>"><a href="<?php echo $this->baseUrl('management/proto/peso/questionnaire_id/'  . $this->questionnaireId) ?>">Pesos</a></li>-->
                          <!--  <li class="<?php echo ($action == 'gabarito')? 'current' : ''; ?>"><a href="<?php echo $this->baseUrl('management/proto/gabarito/questionnaire_id/'  . $this->questionnaireId) ?>">Gabarito</a></li>-->
                               <!--<li><a href="#<?php //echo $this->baseUrl('management/proto') ?>">Eligibilidade</a></li>-->
                           </ul>
                       </li>
                    <?php endif; ?>
           
               </ul>
            </li>
        <?php endif; ?>
            
        <!-- li class="link <?php echo $controller == 'privilege'? 'current' : ''; ?>"><a href="#<?php // echo $this->baseUrl('management/privilege') ?>">Privilégios</a></li -->
        <!-- li class="link"><a href="#<?php //echo $this->baseUrl('management/resource') ?>">Recursos</a></li -->            
    </ul>   
</nav>