<?php
$this->headScript()->appendFile($this->baseUrl('js/management/appraiser/list.js?x1'));
?>
<table class="table">
	<caption></caption>
	<thead>
		<tr>
			<th style="padding: 30px 5px 40px">Empresa</th>
			<th>UF</th>
			<th class="appraisers-confirm">Classificar<br>Final.
			</th>
			<th class="appraisers" style="padding: 30px 5px 21px">Verificador</th>
			<th class="appraisers-cancel">Desclassificar</th>

			<th>Pontos<br>Gerais
			</th>
			<th>Pontuação<br>Gestão
			</th>
			<th>Média<br>Relato <br>do Avaliador
			</th>
			<th>Relat.<br>Interno <br>do Avaliador
			</th>

			<th style="padding: 30px 5px 21px;">Devolver P/<br>Avaliador
			</th>

			<th>Prêmio</th>
      <?php if ($competitionId == 2013) : ?>
      		<th>Pontos<br>Empreende.
			</th>
      <?php endif; ?>
      		<th>RAE</th>
		 	<th>Critério</br>de Avaliação</th>
		</tr>
	</thead>
<?php if (count($this->getAllEnterprise) >= 1): ?>
  <tbody>
<?php
$autotest = new Model_AnswerVerificador(); 
$enterpriseId = new Model_Enterprise();
$executionPontuacaoManager = new Manager_ExecutionPontuacao();
$Appraiser = new Model_Appraiser;

  foreach ($this->getAllEnterprise as $index => $enterprise):
  
  $enterpriseId->setTempVal($enterprise->getEnterpriseId(),'PontosVerificador_estadual',$enterprise->getPontosVerificador());
  $enterpriseId->setTempVal($enterprise->getEnterpriseId(),'NegociosTotal_estadual',$enterprise->getNegociosTotal());
  $enterpriseId->setTempVal($enterprise->getEnterpriseId(),'MediaPontos_estadual',$enterprise->getMediaPontos());

  $QtdPontosFortes = $enterprise->getQtdePontosFortes();
  
  if($QtdPontosFortes == 12)  $QtdPontosFortes = 20; 
  if($QtdPontosFortes == 11)  $QtdPontosFortes = 19;
  if($QtdPontosFortes == 10)  $QtdPontosFortes = 18;
  if($QtdPontosFortes == 9)   $QtdPontosFortes = 17;
  if($QtdPontosFortes == 8)   $QtdPontosFortes = 16;
  if($QtdPontosFortes == 7)   $QtdPontosFortes = 14;
  if($QtdPontosFortes == 6)   $QtdPontosFortes = 12;
  if($QtdPontosFortes == 5)   $QtdPontosFortes = 10;
  if($QtdPontosFortes == 4)   $QtdPontosFortes = 8;
  if($QtdPontosFortes == 3)   $QtdPontosFortes = 6;
  if($QtdPontosFortes == 2)   $QtdPontosFortes = 4;
  if($QtdPontosFortes == 1)   $QtdPontosFortes = 2;
  if($QtdPontosFortes == 0)   $QtdPontosFortes = 0;
    
    $raa = $enterprise->getDevolutivePath();
    try {
    	list ($root, $pasta, $key,$arquivo) = split("/",$raa);
    	$extension_pos = strrpos($arquivo, '.');
    	$fileName = substr($arquivo, 0, $extension_pos) . 'VR' . substr($arquivo, $extension_pos);
    	$raa = "/" . $pasta . "/" .$key . "/" . $fileName;
    	} catch (Excception $e) {}
    	
    $socialName = $enterprise->getSocialName();
    $fantasyName = $enterprise->getFantasyName();
    $CNPJ = trim($enterprise->getCnpj());
    //$CPF = trim($enterprise->getCpf());
    $CPF = '';
    $UF = trim($enterprise->getUf());
    $email = trim($enterprise->getEmailDefault());
    //$phone = trim($enterprise->getTelefone());
    $phone = trim($enterprise->getPhone());
    $percent = ($enterprise->getPA() ? ($enterprise->getPA() . "%") : "");
    
    $notaFinal = $this->baseUrl();
    
    $survey = $this->baseUrl('/management/verificacao/index/enterprise-id-key/'
        . $enterprise->getIdKey());
    
    $verificarCriterio = $this->baseUrl('/management/verificacao/criterioavaliacao/enterprise-id-key/'
        . $enterprise->getIdKey());
    
    $verificarquestionarioNegocio = $this->baseUrl('/management/verificacao/questionarionegocio/enterprise-id-key/'
        . $enterprise->getIdKey());
    
    $GerarRelatorio = $this->baseUrl();
    
//     $verificadores = array(
//       'confirm' => array(
//         'status' => (($enterprise->getClassificadoVerificacao() != null) ? $enterprise->getClassificadoVerificacao() : false),
//         'options' => array(
//           'primary' => array(
//             'status' => (($enterprise->getCheckerId() != null) ? $enterprise->getCheckerId() : 0),
//             'field' => array(),
//             'label' => false
//           )
//         )
//       ),
//       'cancel' => array(
//         'status' => (($enterprise->getDesclassificadoVerificacao() != null) ? $enterprise->getDesclassificadoVerificacao() : false),
//         'note' => trim($enterprise->getMotivoDesclassificadoVerificacao())
//       )
//     );
   $checkerV = $enterprise->getCheckerIdV();
   $classifica = $enterprise->getClassificarFase2Nacional();
        $verificadores = array(
          'confirm' => array(
            'status' => (($classifica != null) ? $classifica : false),
            'options' => array(
              'primary' => array(
              	'status' => (($checkerV != null) ?$checkerV : 0),
                'field' => array(),
                'label' => false
              )
            )
          ),
          'cancel' => array(
            'status' => (($enterprise->getDesclassificarFase2Nacional() != null) ? $enterprise->getDesclassificarFase2Nacional() : false),
            'note' => trim($enterprise->getMotivoDesclassificadoFase2Nacional())
          )
        );
 //var_dump($verificadores);   
	$enterpriseUserid = $enterpriseId->getUserIdByIdKey($enterprise->getIdKey());
	$score =(object)$autotest->getAllScoreByEnterpriseId($enterpriseUserid);
	$scoreVisita = $Appraiser->getEnterpriseScoreAppraiserAnwserVerificadorData($enterprise->getEnterpriseId(),$enterprise->getCheckerId());
	$NotaAutoAvalVerificador  = $executionPontuacaoManager->calculateExecutionScore(52,$enterpriseUserid,true);
	
// 	if($scoreVisita->count() > 0)
// 		$NotaQuestVisitaVerificador = $scoreVisita[0]->getPontosFinal();
// 	else
// 		$NotaQuestVisitaVerificador = 0;
	$mediaRelato = $enterprise->getMediaPontos();
	$PontuacaoFinal = $enterprise->getPontosVerificador();
	//$PontuacaoFinal =  (($NotaAutoAvalVerificador * 0.2) + ($mediaRelato * 0.6) + $QtdPontosFortes);
	
    if (isset($this->allCheckers))
    { 
		if(($score->count() > 0 and $score[0]->EnterpriseId == $enterpriseUserid) and $verificadores['confirm']['options']['primary']['status'] != 0)
		{ 
      		foreach ($this->allCheckers as $checker)
      		{ 
	  			if($verificadores['confirm']['options']['primary']['status'] == $checker->getId())
	  			{ 
			        $verificadorNome = $checker->getFirstName() . ' ' . $checker->getSurname();
			        $verificadores['confirm']['options']['primary']['field'][] = '<option '
			                . (($isCurrentCompetition)?'':' disabled ')
			                .' value="' 
			                . (($isCurrentCompetition)?$checker->getId():null) . '" ' 
			                . (($verificadores['confirm']['options']['primary']['status'] == $checker->getId()) ? 'selected="selected"' : '') . '>' 
			                . $verificadorNome 
			                . '</option>';
	  			}
      		}
		} else
		{ 
	      foreach ($this->allCheckers as $checker)
	      { 
		        $verificadorNome = $checker->getFirstName() . ' ' . $checker->getSurname();
		        $verificadores['confirm']['options']['primary']['field'][] = '<option '
		                . (($isCurrentCompetition)?'':' disabled ')
		                .' value="' 
		                . (($isCurrentCompetition)?$checker->getId():null) . '" ' 
		                . (($verificadores['confirm']['options']['primary']['status'] == $checker->getId()) ? 'selected="selected"' : '') . '>' 
		                . $verificadorNome 
		                . '</option>';
	      }
		}
    } 
?>

    <tr
			class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?> <?php echo ($verificadores['cancel']['status'] ? 'editable' : ''); ?>"
			data-idkey="<?php echo $enterprise->getIdKey(); ?>">
			<td>
				<dl style="text-align: left; height: 69px;">
					<dt title="<?php echo $socialName; ?>">
						<b><?php echo (($fantasyName != '') ? substr($fantasyName, 0, 60) : '--'); ?></b>
					</dt>
					<dd style="margin-left: 5px" class="identity"
						title="<?php echo $email; ?> <?php echo $phone; ?>"><?php echo (($CNPJ != '') ? $CNPJ : (($CPF != '') ? $CPF : '--')); ?></dd>
				</dl>
			</td>

			<td class="middle"><i><?php echo $UF; ?></i></td>
			<td class="middle">
          <?php if ($enterprise->getPontosGeral() != '-'): ?>
            <input type="checkbox" <?php if ($isCurrentCompetition): ?>
				name="change-ranking-<?php echo $index; ?>"
				id="change-ranking-<?php echo $index; ?>" class="change-ranking"
				value="<?php echo $enterprise->getIdKey(); ?>" <?php  else : ?>
				disabled <?php endif; ?>
				<?php echo ($verificadores['confirm']['status'] == 1 ? 'checked="checked"' : ''); ?> />
        <?php endif; ?>
      </td>

			<td>
        <?php if ($enterprise->getPontosGeral() != '-'): ?>
            <dl class="change-ranking-label" style="width: 190px; min-width: 190px; display: <?php echo (!$verificadores['confirm']['status'] ? 'block' : 'none'); ?>;">
					<dt></dt>
					<dd class="primary" style="width: 100%">
						<span>Não selecionado</span>
					</dd>
				</dl>
				<dl class="change-ranking-field" style="width: 190px; min-width: 190px; display: <?php echo ($verificadores['confirm']['status'] ? 'block' : 'none'); ?>;">
					<dt></dt>
					<dd class="primary" style="width: 97%">
						<select <?php if ($isCurrentCompetition): ?>
							name="change-ranking-options-first-<?php echo $index; ?>"
							id="change-ranking-options-first-<?php echo $index; ?>"
							class="change-ranking-option" data-type="1" <?php else: ?>
							disabled <?php endif; ?>>
                    <?php if ($isCurrentCompetition): ?> 
                    <option value="0">Selecione</option>
                    <?php endif; ?> 
                  <?php echo implode("\n", $verificadores['confirm']['options']['primary']['field']); ?>
                </select>
					</dd>
				</dl>
          <?php endif; ?>
      </td>
			<td class="middle"><input type="checkbox"
				<?php if ($isCurrentCompetition): ?>
				name="cancel-ranking-<?php echo $index; ?>"
				id="cancel-ranking-<?php echo $index; ?>" class="cancel-ranking"
				value="<?php echo $enterprise->getIdKey(); ?>" <?php else: ?>
				disabled <?php endif; ?>
				<?php echo ($verificadores['cancel']['status'] ? 'checked="checked"' : ''); ?> />
				<a href="" title="Editar justificativa"
				class="cancel-ranking-note-edit">(editar justificativa)</a></td>

			<td class="middle">
          <?php
           // if ($enterprise->getPontosGeral() != '-') {
                
               // $NegocioTotal =  number_format($enterprise->getNegociosTotal()*1, 1 , '.', ',');
               //$MediaTotal =  number_format($enterprise->getTotalPrimeiraFase(), 1 , '.', ',');
 
                //echo $MediaTotal;
          echo number_format($PontuacaoFinal, 1 , ',', '.');
          //$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'NotaAutoAvalVerificador',number_format($NotaAutoAvalVerificador, 1 , ',', '.'));
            //}
        ?>
      </td>
			<td class="middle"><span>
          <?php
            //echo number_format($enterprise->getNegociosTotal()*1, 1 , ',', '.');  
          echo number_format($NotaAutoAvalVerificador*1, 1 , ',', '.');
            ?>
          </span></td>

			</td>
			<td class="middle">
			
			<?php echo number_format($mediaRelato, 1 , ',', '.');?>
                
            </td>

			<td class="middle">
				<dl>
					<dt>

						<a
							href="<?php echo $this->baseUrl("management/appraiser/internal-report/enterprise-id-key/{$enterprise->getIdKey()}/competition-id/{$competitionId}"); ?>#report"
							target="_blank" title="Relatório Interno" class="download-raa"
							target="blank">Interno</a>
					</dt>
				</dl>
			</td>
			<td class="middle">
				<div
					style="width: 295px; display: block; position: relative; clear: both">
					<ul class="devolver"
						style="width: 100%; float: left; margin: 0; margin: 4px; margin-bottom: 0px">

						<li
							style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
                    <?php $avaliador = $enterprise->getFirstNameAvaliadorPri(); ?>
                    
                        <?php if ($avaliador): ?><label>
                            - <?php echo $avaliador; ?> <b
								style="font-size: 10px">(<?php echo $enterprise->getLoginAvaliadorPri(); ?>)</b>
                         
                        <?php if ($enterprise->getAppraiserStatus() == 'C'): ?>
    					   <?php echo number_format($enterprise->getPontos(), 1 , ',', '.'); ?> pts.
                             </label>
                            <?php if ($isCurrentCompetition): ?> 
                            <a
							style="font-size: 11px; text-indent: 0px; width: 54px; display: inline-block;"
							title="Devolver para esse avaliador"
							href="<?php echo $this->baseUrl('management/appraiser/devolver-avaliador/appraiser/' . $enterprise->getAppraiserId() . '/key/' . $enterprise->getIdKey()); ?>">[Devolver]</a>
                            <?php endif; ?> 
                    
                            <?php elseif ($enterprise->getAppraiserStatus() == 'I'): ?>
                              Iniciado
                            <?php elseif ($enterprise->getAppraiserStatus() == 'N'): ?>
                              <Strong>Não iniciado</Strong>
                            <?php endif; ?>
                    <?php endif; ?>
                </li>

						<li
							style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
							<label>
                        <?php $avaliador = $enterprise->getFirstNameAvaliadorSec(); ?>
                        <?php if ($avaliador): ?>
                           - <?php echo $avaliador; ?> <b
								style="font-size: 10px">(<?php echo $enterprise->getLoginAvaliadorSec(); ?>)</b>
                          
                           <?php if ($enterprise->getAppraiserStatusSec() == 'C'): ?>
					           <?php echo number_format($enterprise->getPontosSec(), 1 , ',', '.'); ?> pts.
                                <?php if ($isCurrentCompetition): ?> 
                                 <a
								style="font-size: 11px; text-indent: 0px; width: 54px; display: inline-block;"
								title="Devolver para esse avaliador"
								href="<?php echo $this->baseUrl('management/appraiser/devolver-avaliador/appraiser/' . $enterprise->getAppraiserIdSec() . '/key/' . $enterprise->getIdKey()); ?>">[Devolver]</a>
                                <?php endif; ?> 
                            <?php elseif ($enterprise->getAppraiserStatusSec() == 'I'): ?>
                              Iniciado
                            <?php elseif ($enterprise->getAppraiserStatusSec() == 'N'): ?>
                              <Strong>Não iniciado</Strong>
                            <?php endif; ?>
                              
                        <?php endif; ?>
                    </label>
						</li>

						<li
							style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
							<label>
                        <?php $avaliador = $enterprise->getFirstNameAvaliadorTer(); ?>
                        <?php if ($avaliador): ?>
                            - <?php echo $avaliador; ?> <b
								style="font-size: 10px">(<?php echo $enterprise->getLoginAvaliadorTer(); ?>)</b>
                            
                                
                            <?php if ($enterprise->getAppraiserStatusTer() == 'C'): ?>
					           <?php echo number_format($enterprise->getPontosTer(), 1 , ',', '.'); ?> pts.
                                <?php if ($isCurrentCompetition): ?> 
                                <a
								style="font-size: 11px; text-indent: 0px; width: 54px; display: inline-block;"
								title="Devolver para esse avaliador"
								href="<?php echo $this->baseUrl('management/appraiser/devolver-avaliador/appraiser/' . $enterprise->getAppraiserIdTer() . '/key/' . $enterprise->getIdKey()); ?>">[Devolver]</a>
                                <?php endif; ?> 
                                
                            <?php elseif ($enterprise->getAppraiserStatusTer() == 'I'): ?>
                              Iniciado
                            <?php elseif ($enterprise->getAppraiserStatusTer() == 'N'): ?>
                              <Strong>Não iniciado</Strong>
                            <?php endif; ?>
                        <?php endif; ?>
                    </label>
						</li>

					</ul>

				</div>
			</td>
			<td class="middle"><span><?php echo str_replace('Microempreendedora', 'Microemp.', $enterprise->getDescriptionEca()); ?></span></td>

      <?php if ($competitionId == 2013) : ?>
      <td class="middle"><span><?php echo number_format($enterprise->getPontosEmpreendedorismo(), 2 , ',', '.');?></span></td>
      <?php endif; ?>
      
      <td class="middle">
				<dl>
					<dt>
            <?php if ($raa): ?>
                <a href="<?php echo $raa; ?>" title="Baixar RAE"
							class="report">Baixar RAE</a>
            <?php endif; ?>
            </dt>
				</dl>
			</td>
	<td class="middle">
		<dl>
			<dt>
	         <?php echo $QtdPontosFortes; 
			 $enterpriseId->setTempVal($enterprise->getEnterpriseId(),'QtdPontosFortes',$QtdPontosFortes);
			 ?>
	        
	        </dt>
		</dl>
	</td>
		</tr>
		<tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>"
			data-idkey="<?php echo $enterprise->getIdKey(); ?>">
			<td class="cancel-ranking-fieldset" data-saved="true">
				<dl>
					<dt>
						<label>Justificativa <i>(obrigatório)</i></label>
					</dt>
					<dd class="field">
						<textarea name="cancel-ranking-note-<?php echo $index; ?>"
							id="cancel-ranking-note-<?php echo $index; ?>"
							class="cancel-ranking-note"><?php echo $verificadores['cancel']['note']; ?></textarea>
					</dd>
					<dd class="button">
						<a href="" title="Salvar" class="cancel-ranking-note-save">Salvar</a>
					</dd>
					<!--a href="#" title="Fechar" onclick="console.log($(this).closest('td').hide());return false;">(X)</a-->
				</dl>
			</td>
		</tr>
<?php
  endforeach;
?>
  </tbody>
<?php
endif;
?>
</table>
