<?php
$this->headScript()->appendFile($this->baseUrl('js/management/appraiser/list.js?x1'));
/**
view usada para gerar conteudo do fetchall em .CSV
*/
//CONFIGURACOES
$separador = ";";
$novalinha = "\n";
// FIM CONFIGURACOES
$competitionId = (isset($this->filter['competition_id']))? $this->filter['competition_id'] : $this->competitionId;

echo "Razão Social{$separador}CPF{$separador}Nome Fantasia{$separador}CNPJ{$separador}Email{$separador}UF{$separador}";

echo "Classificar Final{$separador}";
echo "Desclassificar{$separador}";
echo "Pontos Gerais{$separador}";
echo "Pontuação  Gestão{$separador}";
echo "Média Relato Avaliador{$separador}";
echo "Prêmio{$separador}";
echo "Critério de Avaliação{$separador}";

if ($competitionId == 2013) {
	echo "Pontos Empreendedorismo{$separador}";
}

echo "Avaliador 1{$separador}";
echo "Login 1{$separador}";
echo "Status 1{$separador}";
echo "Avaliador 2{$separador}";
echo "Login 2{$separador}";
echo "Status 2{$separador}";
echo "Avaliador 3{$separador}";
echo "Login 3{$separador}";
echo "Status 3{$separador}";
echo $novalinha;

$executionPontuacaoManager = new Manager_ExecutionPontuacao();
$enterpriseId = new Model_Enterprise();

$i = 1;
if (count($this->getAllEnterprise) >= 1) :
   foreach ($this->getAllEnterprise as $enterprise) {
       
   	$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'PontosVerificador_estadual',$enterprise->getPontosVerificador());
   	$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'NegociosTotal_estadual',$enterprise->getNegociosTotal());
   	$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'MediaPontos_estadual',$enterprise->getMediaPontos());
        $socialName = rr ( $enterprise->getSocialName() );
        $inscricaoEstadual = ''; //rr2 ( $enterprise->getInscricaoEstadual() );
        $fantasyName = rr ( $enterprise->getFantasyName() );
        $enterpriseTypeId = 2; //$enterprise->getEnterpriseTypeId();
        $CNPJ = trim($enterprise->getCnpj());
        $CPF = trim($enterprise->getCpfUser());
        $enterpriseType = ($enterpriseTypeId == '1')?$CNPJ:$CPF;
        $email = trim($enterprise->getEmailDefault());
        
        $getClassificado = ($enterprise->getClassificar() == '1' )?'SIM':'NÃO';
        
        $getDesclassificarNacional = ($enterprise->getDesclassificar() == '1' )?'SIM':'NÃO';
        $premio = str_replace('Microempreendedora', 'Microemp.', $enterprise->getDescriptionEca());
        
        $PontuacaoFinal = number_format($enterprise->getPontosVerificador(), 1 , ',', '.');
        
        
        $enterpriseUserid = $enterpriseId->getUserIdByIdKey($enterprise->getIdKey());
        $pontosGeral = (($enterprise->getPontosGeral() != null) ? $enterprise->getPontosGeral() : '--');
        $NotaAutoAvalVerificador  = $executionPontuacaoManager->calculateExecutionScore(52,$enterpriseUserid,true);

        $mediaRelato = number_format($enterprise->getMediaPontos(), 1 , ',', '.');
        $QtdPontosFortes = $enterprise->getQtdePontosFortes();
        
        if($QtdPontosFortes == 12)  $QtdPontosFortes = 20; 
  if($QtdPontosFortes == 11)  $QtdPontosFortes = 19;
  if($QtdPontosFortes == 10)  $QtdPontosFortes = 18;
  if($QtdPontosFortes == 9)   $QtdPontosFortes = 17;
  if($QtdPontosFortes == 8)   $QtdPontosFortes = 16;
  if($QtdPontosFortes == 7)   $QtdPontosFortes = 14;
  if($QtdPontosFortes == 6)   $QtdPontosFortes = 12;
  if($QtdPontosFortes == 5)   $QtdPontosFortes = 10;
  if($QtdPontosFortes == 4)   $QtdPontosFortes = 8;
  if($QtdPontosFortes == 3)   $QtdPontosFortes = 6;
  if($QtdPontosFortes == 2)   $QtdPontosFortes = 4;
  if($QtdPontosFortes == 1)   $QtdPontosFortes = 2;
  if($QtdPontosFortes == 0)   $QtdPontosFortes = 0;
        if ($competitionId == 2013) {
            $pontosEmpreende = number_format($enterprise->getPontosEmpreendedorismo(), 2 , ',', '.');
        }
        
        echo $socialName ? $socialName : $enterpriseType; //Razao Social
        echo $separador;
        echo $CPF.$separador;
        echo $fantasyName.$separador; //Nome Fantasia
        echo $CNPJ.$separador; //CPF/CNPJ
        echo $email.$separador;
        echo rr2($enterprise->getUf()).$separador;
        
        echo $getClassificado.$separador;

        echo $getDesclassificarNacional.$separador;
        
        echo $PontuacaoFinal.$separador;
        echo number_format($NotaAutoAvalVerificador*1, 1 , ',', '.').$separador;
        echo $mediaRelato.$separador;
        
        echo $premio.$separador;
        echo $QtdPontosFortes.$separador;
        
        if ($competitionId == 2013) {
            echo $pontosEmpreende.$separador;
        }
        
        $avaliador = $enterprise->getFirstNameAvaliadorPri();
        if ($avaliador) {
        	echo $avaliador . $separador . $enterprise->getLoginAvaliadorPri();
        	echo $separador;
        	if ($enterprise->getAppraiserStatus() == 'C') {
        		echo number_format($enterprise->getPontos(), 1, ',', '.')  . "pts";
        	} elseif ($enterprise->getAppraiserStatus() == 'I') {
        		echo "Iniciado";
        	} elseif ($enterprise->getAppraiserStatus() == 'N') {
        		echo "Não iniciado";
        	}
        } else {
        	echo $separador;echo $separador;
        }
        echo $separador;
        $avaliador = $enterprise->getFirstNameAvaliadorSec();
        if ($avaliador) {
        	echo $avaliador . $separador . $enterprise->getLoginAvaliadorSec();
        	echo $separador;
        	if ($enterprise->getAppraiserStatusSec() == 'C') {
        		echo number_format($enterprise->getPontosSec(), 1, ',', '.')  . "pts";
        	} elseif ($enterprise->getAppraiserStatusSec() == 'I') {
        		echo "Iniciado";
        	} elseif ($enterprise->getAppraiserStatusSec() == 'N') {
        		echo "Não iniciado";
        	}
        } else {
        	echo $separador.$separador;
        }
        echo $separador;
        $avaliador = $enterprise->getFirstNameAvaliadorTer();
        if ($avaliador) {
        	echo $avaliador . $separador . $enterprise->getLoginAvaliadorTer();
        
        	echo $separador;
        	if ($enterprise->getAppraiserStatusTer() == 'C') {
        		echo number_format($enterprise->getPontosTer(), 1, ',', '.')  . "pts";
        	} elseif ($enterprise->getAppraiserStatusTer() == 'I') {
        		echo "Iniciado";
        	} elseif ($enterprise->getAppraiserStatusTer() == 'N') {
        		echo "Não iniciado";
        	}
        } else {
        	echo $separador.$separador;
        }
        echo $separador;

        echo $novalinha; 
        $i = $i + 1;
   }
   
   echo $novalinha; 
   
endif;