
<h1 class="title">Arquivos</h1>

<ul id="arquivos">
    <li>
        <a href="/files/codigo_etica_revisado_v1_psmn_2015.docx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Código de Ética PSMN - 2015</b>
        </a>
    </li>
    <?php /* ?>
    <?php */ ?>

    <li>
        <a href="/files/reuniao_gestores_apostila_psmn_2015.pdf" target="_blank" style="background-image: url(/img/icon-pdf.png); background-repeat: no-repeat;">
            <b>Reunião de Gestores PSMN - 2015</b>
            Compartilhar as melhores práticas de gestão do Prêmio SEBRAE Mulher de Negócios.</a>
    </li>

    <li>
        <a href="/files/manual_gestor_revisado_v2_2015.doc" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Manual do Gestor do PSMN - 2015</b>
            Documento contendo orientações sobre os processos do Prêmio SEBRAE Mulher de Negócios.</a>
    </li>
    <li>
        <a href="/files/termo_compromisso_adesao_v1_psmn_2015.docx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Termo de Compromisso e Adesão ao PSMN - 2015</b>
            Documento contendo o Termo de Compromisso e Adesão ao Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

    <li>

        <a href="/files/tutorial_aplicacao_sistema_PSMN_2015.pptx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Tutorial de Aplicação do Sistema – PSMN 2015</b>
            Documento contendo o Tutorial de Aplicação do Sistema Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

   <li>

        <a href="/files/Caderno_ Exercicios.docx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b> Caderno de Exercícios Workshop Boas Práticas – PSMN 2015</b>
            Documento contendo o  Caderno de Exercícios Workshop Boas Práticas Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

<li>

        <a href="/files/Apresentação_ppt_ banca_ de_ juizes_ PSMN_ 2015.pptx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Apresentação ppt banca de juizes – PSMN 2015</b>
            Documento contendo a Apresentação ppt banca de juizes Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

<li>

        <a href="/files/Workshop_Boas_Práticas_Participante_Final.pptx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Workshop Boas Práticas  Participante Final – PSMN 2015</b>
            Documento contendo o Workshop Boas Práticas  Participante Final Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>


<li>

        <a href="/files/Modelo_Manual_Comissão_Julgadora_2015.docx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b> Modelo Manual Comissão Julgadora – PSMN 2015</b>
            Documento contendo o Modelo Manual Comissão Julgadora Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

<li>

        <a href="/files/Manual da Banca Avaliadora PSMN 2015 - revisado.doc" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b> Manual da Banca Avaliadora  – PSMN 2015</b>
            Documento contendo o Manual da Banca Avaliadora PSMN 2015 Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>


<li>

        <a href="/files/modelo_de_ppt_banca_de_juizes_PSMN_2015.ppt" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b> Modelo de ppt banca de juizes – PSMN 2015</b>
            Documento contendo o Modelo de ppt banca de juizes – PSMN 2015 Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

</ul>
