<?php
$this->headScript()->appendFile($this->baseUrl('js/management/appraiser/list.js?x1'));
?>

<table class="table">
  <caption></caption>
  <thead>
    <tr>
      <th style="padding: 30px 5px 40px">Empresa</th>
      <th>UF</th>
        <th>Ranking</th>
      <th class="appraisers-confirm">Vencedor<br>Ouro</th>
      <th>Prata</th>
      <th>Bronze</th>
      <th class="appraisers-cancel">Desclassificar</th>
      <th>Pontuação<br>Geral</th>
      <th style="padding: 30px 5px 21px;">Devolver P/<br>Verificador</th>
      <?php if ($competitionId == 2013) : ?>
      <th>Pontos<br>Empreende.</th>
      <?php endif; ?>
      <th>RA<br>Verif.</th>
      <th>Relat.<br>Interno</th>    
      <th>Prêmio</th>
      <th>Questionário<br>de Auto Aval.<br>Negócios</th>
      <th>Questionário<br>de Visita</th>
      <th>Critério<br>de Avaliação</th>
    </tr>
  </thead>
<?php if (count($this->getAllEnterprise) >= 1): ?>
  <tbody>  

<?php 

$autotest = new Model_AnswerVerificador(); 
$enterpriseId = new Model_Enterprise();
$Appraiser = new Model_Appraiser; 
$executionPontuacaoManager = new Manager_ExecutionPontuacao();
$nacional = 2;

foreach ($this->getAllEnterprise as $index => $enterprise):  

$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'PontosVerificador_estadual',$enterprise->getPontosVerificador());
$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'NegociosTotal_estadual',$enterprise->getNegociosTotal());
$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'MediaPontos_estadual',$enterprise->getMediaPontos());


 $QtdPontosFortes = $enterprise->getQtdePontosFortes();
    
  if($QtdPontosFortes == 12)  $QtdPontosFortes = 20; 
  if($QtdPontosFortes == 11)  $QtdPontosFortes = 19;
  if($QtdPontosFortes == 10)  $QtdPontosFortes = 18;
  if($QtdPontosFortes == 9)   $QtdPontosFortes = 17;
  if($QtdPontosFortes == 8)   $QtdPontosFortes = 16;
  if($QtdPontosFortes == 7)   $QtdPontosFortes = 14;
  if($QtdPontosFortes == 6)   $QtdPontosFortes = 12;
  if($QtdPontosFortes == 5)   $QtdPontosFortes = 10;
  if($QtdPontosFortes == 4)   $QtdPontosFortes = 8;
  if($QtdPontosFortes == 3)   $QtdPontosFortes = 6;
  if($QtdPontosFortes == 2)   $QtdPontosFortes = 4;
  if($QtdPontosFortes == 1)   $QtdPontosFortes = 2;
  if($QtdPontosFortes == 0)   $QtdPontosFortes = 0;
  
//echo('<pre>');  
//print_r($autotest->getScoreLevel());exit;
//echo('</pre>');

//750000
  //$NotaAutoAvalVerificador = (1600/16);  

$enterpriseUserid = $enterpriseId->getUserIdByIdKey($enterprise->getIdKey());
// Sandra - $nacional = 8 por ser finalista nacional
$scoreVisita = $Appraiser->getEnterpriseScoreAppraiserAnwserVerificadorData($enterprise->getEnterpriseId(),$enterprise->getCheckerId(), null, 8);

//print_r($scoreVisita->count());exit;

//$score =$autotest->getAllScoreByEnterpriseId($enterpriseUserid);
//$NotaAutoAvalVerificador = $score[0]->ScoreLevel;
 
$NotaAutoAvalVerificador  = $executionPontuacaoManager->calculateExecutionScore(52,$enterpriseUserid,true,$enterprise->getCheckerId());

//$NotaAutoAvalVerificador = ($autotest->getScoreLevel()/16);  
if($scoreVisita->count() > 0)
  	$NotaQuestVisitaVerificador = $scoreVisita[0]->getPontosFinal();
else
  	$NotaQuestVisitaVerificador = 0;
//$mediaRelato = $enterprise->getMediaPontos();
  $PontuacaoFinal =  (($NotaAutoAvalVerificador * 0.2) + ($NotaQuestVisitaVerificador * 0.6) + $QtdPontosFortes);  
  
  //$PontuacaoFinal = $enterprise->getPontosVerificador();
  
    $raa = $enterprise->getDevolutivePath();
	
    try {
		list ($root, $pasta, $key,$arquivo) = split("/",$raa);
		$extension_pos = strrpos($arquivo, '.');
		$fileName = substr($arquivo, 0, $extension_pos) . 'VN' . substr($arquivo, $extension_pos);
		$raa = "/" . $pasta . "/" .$key . "/" . $fileName;
	
	} catch (Excception $e) {}
	
	
    $socialName = $enterprise->getSocialName();
    $fantasyName = $enterprise->getFantasyName();
    $CNPJ = trim($enterprise->getCnpj());
    //$CPF = trim($enterprise->getCpf());
    $CPF = '';
    $UF = trim($enterprise->getUf());
    $email = trim($enterprise->getEmailDefault());
    //$phone = trim($enterprise->getTelefone());
    $phone = trim($enterprise->getPhone());
    $percent = ($enterprise->getPA() ? ($enterprise->getPA() . "%") : "");
    
    $verificadores = array(
      'confirm' => array(
        'status' => (($enterprise->getClassificadoOuroNacional() != null) ? $enterprise->getClassificadoOuroNacional() : false),
        'statusPrata' => (($enterprise->getClassificadoPrataNacional() != null) ? $enterprise->getClassificadoPrataNacional() : false),
        'statusBronze' => (($enterprise->getClassificadoBronzeNacional() != null) ? $enterprise->getClassificadoBronzeNacional() : false),
          'options' => array(
          'primary' => array(
            'status' => (($enterprise->getCheckerId() != null) ? $enterprise->getCheckerId() : 0),
            'field' => array(),
            'label' => false
          )
        )
      ),
      'cancel' => array(
        'status' => (($enterprise->getDesclassificarFase3Nacional() != null) ? $enterprise->getDesclassificarFase3Nacional() : false),
        'note' => trim($enterprise->getMotivoDesclassificadoFase3Nacional())
      )
    );

    if (isset($this->allCheckers)):
      foreach ($this->allCheckers as $checker):
        $verificadorNome = $checker->getFirstName() . ' ' . $checker->getSurname();
        $verificadores['confirm']['options']['primary']['field'][] = '<option '
                . (($isCurrentCompetition)?null:' disabled ') 
                . ' value="' 
                . (($isCurrentCompetition)?$checker->getId():null) . '" ' 
                . (($verificadores['confirm']['options']['primary']['status'] == $checker->getId()) ? 'selected="selected"' : '') . '>' 
                . $verificadorNome 
                . '</option>';
      endforeach;
    endif;

    $qtPf = $enterprise->getQtdePontosFortes();
?>
    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?> <?php echo ($verificadores['cancel']['status'] ? 'editable' : ''); ?>" data-idkey="<?php echo $enterprise->getIdKey(); ?>">
      <td>
        <dl style="text-align: left; height: 41px;">
          <dt title="<?php echo $socialName; ?>"><b><?php echo (($fantasyName != '') ? substr($fantasyName, 0, 60) : '--'); ?></b></dt>
          <dd style="margin-left: 5px" class="identity" title="<?php echo $email; ?> <?php echo $phone; ?>"><?php echo (($CNPJ != '') ? $CNPJ : (($CPF != '') ? $CPF : '--')); ?></dd>
        </dl>
      </td>

      <td class="middle"><i><?php echo $UF; ?></i></td>
        <td class="middle">
            <?php echo ($index+1) ?>
        </td>
        <td class="middle">
            <?php if ($enterprise->getPontosGeral() != '-'): ?>
              <input type="checkbox" 
                <?php if ($isCurrentCompetition): ?> 
                name="change-ranking-<?php echo $index; ?>" id="change-ranking-<?php echo $index; ?>" class="change-ranking" value="1" 
                <?php else : ?> 
                disabled
                <?php endif; ?> 
                <?php echo ($verificadores['confirm']['status'] ? 'checked="checked"' : ''); ?> />
          <?php endif; ?>
        </td>
        <td class="middle">
            <input type="checkbox" 
            <?php if ($isCurrentCompetition): ?> 
                name="x" id="s2" class="change-ranking" value="2" 
            <?php else : ?> 
                disabled
            <?php endif; ?> 
            <?php echo ($verificadores['confirm']['statusPrata'] ? 'checked="checked"' : ''); ?> />
        </td>
        <td class="middle">
            <input type="checkbox" 
                <?php if ($isCurrentCompetition): ?> 
                   name="x" id="s2" class="change-ranking" value="3" 
                <?php else : ?> 
                    disabled
                <?php endif; ?> 
                <?php echo ($verificadores['confirm']['statusBronze'] ? 'checked="checked"' : ''); ?> />
        </td>
      <td class="middle">
        <input type="checkbox" 
            <?php if ($isCurrentCompetition): ?> 
               name="cancel-ranking-<?php echo $index; ?>" id="cancel-ranking-<?php echo $index; ?>" class="cancel-ranking" value="<?php echo $enterprise->getIdKey(); ?>" 
            <?php else : ?> 
                disabled
            <?php endif; ?>                    
            <?php echo ($verificadores['cancel']['status'] ? 'checked="checked"' : ''); ?> />
        <a href="" title="Editar justificativa" class="cancel-ranking-note-edit">(editar justificativa)</a>
      </td>
<td class="middle">
	<dl>
		<dt>

          <?php           
             echo number_format($PontuacaoFinal, 1 , ',', '.'); 

			$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'PontuacaoFinal',number_format($PontuacaoFinal, 1 , ',', '.'));			 
          ?>                 
        </dt>
	</dl>
</td>
      <td class="middle">
          <div style="width: 265px; height: 41px; display: block; position: relative; clear: both">
            <ul class="devolver" style="width: 100%; float:left;  margin: 0; margin: 4px; margin-bottom: 0px">
                
                <li style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
                    <?php $checker = $enterprise->getFirstNameChecker(); ?>
                    <?php if ($checker): ?><label>
                        - <?php echo $checker; ?> <b style="font-size: 10px">(<?php echo $enterprise->getLoginChecker(); ?>)</b>
                         </label>
                        <?php if ($enterprise->getCheckerStatus() == 'C'): ?>
                            <?php if ($isCurrentCompetition): ?> 
                                <a style="font-size:11px; text-indent: 0px; width: 54px; display: inline-block;" title="Devolver para esse verificador"
                                   href="<?php echo $this->baseUrl('management/appraiser/devolver-verificador/checker/' . $enterprise->getCheckerId() . '/key/' . $enterprise->getIdKey(). '/nacional/2' ); ?>">[Devolver]</a>
                            <?php endif; ?>

                                <br>&nbsp; &nbsp;    
                            <?php 
                                if (!$qtPf) {
                                    echo 'Nenhum ponto forte';
                                } elseif ($qtPf === '1') {
                                    echo '1 ponto forte';
                                } else {
                                    echo "{$qtPf} pontos fortes";
                                }
                            ?>
                            <?php elseif ($enterprise->getCheckerStatus() == 'I'): ?>
                           <br>              &nbsp; &nbsp;   Iniciado
                            <?php elseif ($enterprise->getCheckerStatus() == 'N'): ?>
                            <br>              &nbsp; &nbsp;   <Strong>Não iniciado</Strong>
                            <?php endif; ?>
                     

                    <?php endif; ?>
                </li>
   
            </ul>

          </div>
      </td>
      
        <?php if ($competitionId == 2013) : ?>
        <td class="middle"><span><?php echo number_format($enterprise->getPontosEmpreendedorismo(), 2 , ',', '.');?></span></td>
        <?php endif; ?>
        <td class="middle">
          <dl>
              <dt>
                  <?php if ($raa): ?>
                      <a href="<?php echo $raa; ?>" title="Baixar RAA" class="report" target="_blank">Baixar RAA</a>
                  <?php endif; ?>
              </dt>

          </dl>
        </td>

<td class="middle">
	<dl>
	  <dt>
	    <a href="<?php echo $this->baseUrl("management/appraiser/internal-report/enterprise-id-key/{$enterprise->getIdKey()}/competition-id/{$competitionId}/nacional/{$nacional}"); ?>#report" target="_blank" title="Relatório Interno" class="download-raa" target="blank">Interno</a>
	  </dt>
	</dl>
</td>     

        <td class="middle"><span><?php echo str_replace('Microempreendedora', 'Microemp.', $enterprise->getDescriptionEca()); ?></span></td>
<td class="middle">
	<dl>
		<dt>
        <?php echo number_format($NotaAutoAvalVerificador, 1 , ',', '.');
		$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'NotaAutoAvalVerificador',number_format($NotaAutoAvalVerificador, 1 , ',', '.'));
		?>                    
        </dt>
	</dl>
</td>
<td class="middle">
	<dl>
		<dt>		
        <?php printf($NotaQuestVisitaVerificador);
		$enterpriseId->setTempVal($enterprise->getEnterpriseId(),'NotaQuestVisitaVerificador',$NotaQuestVisitaVerificador);
		?>                    
        </dt>
	</dl>
</td>
<td class="middle">
	<dl>
		<dt>
         <?php echo $QtdPontosFortes; 
		 $enterpriseId->setTempVal($enterprise->getEnterpriseId(),'QtdPontosFortes',$QtdPontosFortes);
		 ?>
        
        </dt>
	</dl>
</td>      

    </tr>
    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="<?php echo $enterprise->getIdKey(); ?>">
      <td class="cancel-ranking-fieldset" data-saved="true">
        <dl>
          <dt><label>Justificativa <i>(obrigatório)</i></label></dt>
          <dd class="field"><textarea name="cancel-ranking-note-<?php echo $index; ?>" id="cancel-ranking-note-<?php echo $index; ?>" class="cancel-ranking-note"><?php echo $verificadores['cancel']['note']; ?></textarea></dd>
          <dd class="button"><a href="" title="Salvar" class="cancel-ranking-note-save">Salvar</a></dd>
          <!--a href="#" title="Fechar" onclick="console.log($(this).closest('td').hide());return false;">(X)</a-->
        </dl>
      </td>
    </tr>
<?php
  endforeach;
?>
  </tbody>
<?php
endif;
?>
</table>