<?php

/**
view usada para gerar conteudo do fetchall em .CSV
*/
//CONFIGURACOES
$separador = ";";
$novalinha = "\n";
// FIM CONFIGURACOES

$competitionId = (isset($this->filter['competition_id']))? $this->filter['competition_id'] : $this->competitionId;

echo "Razão Social{$separador}CPF{$separador}Nome Fantasia{$separador}CNPJ{$separador}Email{$separador}UF{$separador}";

echo "Vencedor Ouro{$separador}";
echo "Prata{$separador}";
echo "Bronze{$separador}";
echo "Desclassificar{$separador}";
echo "P. Geral + Bônus{$separador}";
echo "Bônus{$separador}";
//echo "Devolver p/ Verificador{$separador}";
//echo "Relato Interno{$separador}";
echo "Pontos Negócios{$separador}";
echo "Média Relato{$separador}";
echo "Prêmio{$separador}";
if ($competitionId == 2013) {
    echo "Pontos Empreendedorismo{$separador}";
}
//echo "Raa{$separador}";

echo $novalinha;

$i = 1;
if (count($this->getAllEnterprise) >= 1) :
   foreach ($this->getAllEnterprise as $enterprise) {
       
        $socialName = rr ( $enterprise->getSocialName() );
        $inscricaoEstadual = ''; //rr2 ( $enterprise->getInscricaoEstadual() );
        $fantasyName = rr ( $enterprise->getFantasyName() );
        $enterpriseTypeId = 2; //$enterprise->getEnterpriseTypeId();
        $CNPJ = trim($enterprise->getCnpj());
        $CPF = trim($enterprise->getCpfUser());
        $enterpriseType = ($enterpriseTypeId == '1')?$CNPJ:$CPF;
        $getClassificadoOuro = ($enterprise->getClassificadoOuro() == '1' )?'SIM':'NÃO';
        $getClassificadoPrata = ($enterprise->getClassificadoPrata() == '1')?'SIM':'NÃO';
        $getClassificadoBronze = ($enterprise->getClassificadoBronze() == '1')?'SIM':'NÃO';
        $desclassificado = (($enterprise->getDesclassificadoFinal() == '1') ? 'SIM' : 'NÃO');
        
        $pontosGeral = (($enterprise->getPontosGeral() != null) ? $enterprise->getPontosGeral() : '--');
        $qtPf = $enterprise->getQtdePontosFortes();
                                if ($qtPf === false) {
                                    $bonus = '0';
                                } elseif ($qtPf >= 8) {
                                    $bonus = '20%';
                                }  elseif ($qtPf >= 5) {
                                    $bonus = '10%';
                                } else {
                                    $bonus = '0';
                                }
        $pontosNegocios = number_format($enterprise->getNegociosTotal()*10, 1 , ',', '.').'%';
        $mediaRelato = number_format($enterprise->getMediaPontos(), 1 , ',', '.');
        $premio = str_replace('Microempreendedora', 'Microemp.', $enterprise->getDescriptionEca());
        if ($competitionId == 2013) {
            $pontosEmpreende = number_format($enterprise->getPontosEmpreendedorismo(), 2 , ',', '.');
        }
        $email = trim($enterprise->getEmailDefault());
        
        echo $socialName ? $socialName : $enterpriseType; //Razao Social
        echo $separador;
        echo $CPF.$separador;
        echo $fantasyName.$separador; //Nome Fantasia
        echo $CNPJ.$separador; //CPF/CNPJ
        echo $email.$separador;
        echo rr2($enterprise->getUf()).$separador;
        echo $getClassificadoOuro.$separador;
        echo $getClassificadoPrata.$separador;
        echo $getClassificadoBronze.$separador;
        echo $desclassificado.$separador;
        echo number_format($pontosGeral*100, 1 , ',', '.') . '%'.$separador;
        echo $bonus.$separador;
        echo $pontosNegocios.$separador;
        echo $mediaRelato.$separador;
        echo $premio.$separador;
        if ($competitionId == 2013) {
            echo $pontosEmpreende.$separador;
        }
                
        echo $novalinha; 
        $i = $i + 1;
   }
   
   echo $novalinha; 
   
endif;

