<?php
//$this->setEncoding('UTF-8');
echo "\xEF\xBB\xBF";
/**
view usada para gerar conteudo do fetchall em .CSV
*/
//CONFIGURACOES
$separador = ";";
$novalinha = "\n";
// FIM CONFIGURACOES
//var_dump ( 'getAllEnterprise: ',$this->getAllEnterprise ); exit;
//var_dump ('getAllRegional: ', $this->getAllRegional);
//var_dump ('regionalOption',            $this->regionalOption);
echo "Razão Social{$separador}CPF{$separador}Nome Fantasia{$separador}CNPJ{$separador}Email{$separador}";
//Data de Cadastro da Empresa no Prêmio{$separador}
echo "Data de Abertura da Empresa{$separador}Número de colaboradores{$separador}";
echo "Endereço{$separador}Número{$separador}Complemento{$separador}";
echo "Bairro{$separador}Cidade{$separador}Estado{$separador}";
echo "CEP{$separador}Tipo de Empresa{$separador}";
echo "Porte da Empresa{$separador}";
echo "Categoria{$separador}";
echo "Atividade Econômica{$separador}"; // CNAE
echo "Principal Atividade{$separador}"; // Descrição do CNAE
echo "Nome Completo{$separador}";
echo "Cargo{$separador}";
echo "CPF Contato{$separador}";
echo "Endereço Contato{$separador}Número Contato{$separador}";
echo "Complemento Contato{$separador}Bairro Contato{$separador}Cidade Contato{$separador}Estado Contato{$separador}";
echo "CEP Contato{$separador}";
echo "Telefone Fixo{$separador}Celular{$separador}E-mail{$separador}Data de Nascimento{$separador}";
echo "Sexo{$separador}";
//echo "Nivel de Escolaridade{$separador}";
    //Faixa Etária{$separador}Digitador responsável pelo Cadastro{$separador}
//echo "Digitador Responsável pelo Questionário{$separador}";
//echo "Status da Inscrição{$separador}";

//echo "Relação com a melhor da Seleção{$separador}";

if ($this->isRanking) {
    echo "Gestão{$separador}";
    echo "Enfoque{$separador}";

    echo "Liderança{$separador}";
    echo "Estratégias{$separador}";
    echo "Clientes{$separador}";
    echo "Sociedade{$separador}";
    echo "Informações{$separador}";
    echo "Pessoas{$separador}";
    echo "Processos{$separador}";
    echo "Resultados{$separador}";

    echo "Inovação{$separador}";
    echo "Responsabilidade Social";
}
 

echo "Gerou Inscrição{$separador}";
//echo "Gerou Inscrição{$separador}";data
echo "Gerou Devolutiva{$separador}";
//echo "Gerou Devolutiva{$separador}"; data
//echo "SocialName{$separador}Cnpj{$separador}EmailDefault{$separador}City{$separador}";
//echo "Bairro{$separador}Telefone{$separador}DataInscrição";
echo $novalinha;

function rr ($value)
{
    return str_replace(',','',str_replace(';', '', $value)); 
}
function rr2 ($value)
{
    return str_replace(',','.',$value); 
}
$arrFaturamento = Vtx_Util_Array::annualRevenue();
$arrStatus = Vtx_Util_Array::status();
$categoria = Vtx_Util_Array::categoriaMpe();
$tipoEmpresa = Vtx_Util_Array::tipoEmpresaMPE();
$genderArray = Vtx_Util_Array::gender();

$escolaridadeArray = $this->getAllEducation;
$cargoArray = $this->getAllPosition;


$i = 1;
if (count($this->getAllEnterprise) >= 1) :
   foreach ($this->getAllEnterprise as $enterprise) {
    
        if ($this->isRanking) {
            $gestaoTotalCalc = $enterprise->getGestaoTotal();
            //$maxGestaoTotal[] = $gestaoTotalCalc;
            //$relacao = $this->getHelper('Util')->regraTres($maxGestaoTotal[0],$gestaoTotalCalc).'%';
            $numLid = ($enterprise->getGestaoLideranca()?$enterprise->getGestaoLideranca():0);
            $numEst = ($enterprise->getGestaoEstrategias()?$enterprise->getGestaoEstrategias():0);
            $numCli = ($enterprise->getGestaoClientes()?$enterprise->getGestaoClientes():0);
            $numSoc = ($enterprise->getGestaoSociedade()?$enterprise->getGestaoSociedade():0);
            $numInf = ($enterprise->getGestaoInformacoes()?$enterprise->getGestaoInformacoes():0);
            $numPes = ($enterprise->getGestaoPessoas()?$enterprise->getGestaoPessoas():0);
            $numPro = ($enterprise->getGestaoProcessos()?$enterprise->getGestaoProcessos():0);
            $numRes = ($enterprise->getGestaoResultados()?$enterprise->getGestaoResultados():0);
            //pontuacao
            $gestaoTotal = rr2(number_format(($gestaoTotalCalc?$gestaoTotalCalc:0),2,',','.')).'%';
            $gestaoLideranca = rr2(number_format($numLid,2,',','.')).'%';
            $gestaoEstrategias = rr2(number_format($numEst,2,',','.')).'%';
            $gestaoClientes = rr2(number_format($numCli,2,',','.')).'%';
            $gestaoSociedade = rr2(number_format($numSoc,2,',','.')).'%';
            $gestaoInformacoes = rr2(number_format($numInf,2,',','.')).'%';
            $gestaoPessoas = rr2(number_format($numPes,2,',','.')).'%';
            $gestaoProcessos = rr2(number_format($numPro,2,',','.')).'%';
            $gestaoResultados = rr2(number_format($numRes,2,',','.')).'%';
            $enfoque = rr2(number_format(($numLid+$numEst+$numCli+$numSoc+$numInf+$numPes+$numPro),2,',','.')).'%';
            $inovacao = rr2(number_format(($enterprise->getInovacaoTotal()?$enterprise->getInovacaoTotal():0),2,',','.')).'%';
            $responsabilidade = rr2(number_format(($enterprise->getResponsabilidadeTotal()?$enterprise->getResponsabilidadeTotal():0),2,',','.')).'%';
        }
        
        $socialName = rr ( $enterprise->getSocialName() );
        $inscricaoEstadual = ''; //rr2 ( $enterprise->getInscricaoEstadual() );
        $fantasyName = rr ( $enterprise->getFantasyName() );
        $enterpriseTypeId = 2; //$enterprise->getEnterpriseTypeId();
        $CNPJ = trim($enterprise->getCnpj());
        $CPF = trim($enterprise->getCpfUser());
        $enterpriseType = ($enterpriseTypeId == '1')?$CNPJ:$CPF;
        
        $tipoEmpresaString = '';//$tipoEmpresa[$enterpriseTypeId];
        
        $email = trim($enterprise->getEmailDefault());
        $creationDate = Vtx_Util_Date::format_dma(trim($enterprise->getCreationDate()));
        $numeroEmpregados = $enterprise->getEmployeesQuantity();
        $enderecoRua =  rr ( $enterprise->getStreetNameFull() );
        $enderecoNumero =  rr ( $enterprise->getStreetNumber() );
        $enderecoComplemento = rr (  $enterprise->getStreetCompletion() );
        $enderecoBairro = rr ( $enterprise->getNeighName() );
        $enderecoCidade = $enterprise->getCityName();
        $enderecoEstado = $enterprise->getUf();
        $enderecoCEP = rr ( $enterprise->getCep() );
        
        $faturamento = $arrFaturamento[$enterprise->getAnnualRevenue()];
        $categoria = Vtx_Util_Array::categoriaStringMpe($enterprise->getCategoriaId());
        $cnae = rr ( $enterprise->getCnae() );
        $cnaeDescricao = '';// rr ( $enterprise->getCnaeDescricao() );
        $nomeCompleto = $enterprise->getNomeCompletoUser();
        $cargo = ($enterprise->getPositionId() != '0')?$cargoArray[$enterprise->getPositionId()]:'--';
        
        $enderecoContatoRua =rr ( $enterprise->getUsStreetNameFull() );
        $enderecoContatoNumero =rr ( $enterprise->getUsStreetNumber() );
        $enderecoContatoComplemento =rr ( $enterprise->getUsStreetCompletion() );
        $enderecoContatoBairro =rr ( $enterprise->getUsNeighName() );
        $enderecoContatoCidade =rr ( $enterprise->getUsCityName() );
        $enderecoContatoEstado =rr ( $enterprise->getUsUf() );
        $enderecoContatoCEP =rr ( $enterprise->getUsCep() );
        
        $telefoneFixoContato = $enterprise->getTelefone();
        $celularContato = $enterprise->getCelularUser();
        $emailContato = $enterprise->getEmailUser();
        $dataNascimento = Vtx_Util_Date::format_dma($enterprise->getDataNascimentoUser());
        $sexo = $genderArray[$enterprise->getSexoUser()];
        $nivelEscoladidade = $escolaridadeArray[$enterprise->getEducationId()];
        
        $enterpriseUserId = $enterprise->getIdUser();
        $userLogInscricao = ($enterpriseUserId == $enterprise->getDigitadorLogInscricaoUserIdLog())?true:false;
        $userDigitadorLogGerouDevolutiva = ($enterpriseUserId == $enterprise->getDigitadorLogGerouDevolutivaUserIdLog())?true:false;
        
        $digitadorLogInscricao = ($userLogInscricao)?'':rr($enterprise->getDigitadorLogInscricao());
        //$logInscricao = rr($enterprise->getLogInscricao());
        
        $digitadorLogGerouDevolutiva = ($userDigitadorLogGerouDevolutiva)?'':rr($enterprise->getDigitadorLogGerouDevolutiva());
        //$logGerouDevolutiva = rr($enterprise->getLogGerouDevolutiva());
        
        //if (!$enterprise->getCurrentStatus()) echo 'INATIVA: ';
        //echo Vtx_Util_Date::format_dma($enterprise->getDataInscricao()); //Data de cadastro da empresa no Premio  
        
        echo $socialName ? $socialName : $enterpriseType; //Razao Social
        echo $separador;
        echo $CPF.$separador;
        echo $fantasyName.$separador; //Nome Fantasia
        echo $CNPJ.$separador; //CPF/CNPJ
        echo $email.$separador;
        echo $creationDate.$separador; //Data de cadastro da empresa 
        echo $numeroEmpregados.$separador; //Número de Empregados
        echo $enderecoRua.$separador;
        echo $enderecoNumero.$separador; 
        echo $enderecoComplemento.$separador;
        echo $enderecoBairro.$separador;
        echo $enderecoCidade.$separador;
        echo $enderecoEstado.$separador;
        echo $enderecoCEP.$separador;
        
        
        echo $tipoEmpresaString.$separador;
        
        
        echo $faturamento.$separador;
        echo $categoria.$separador;
        echo $cnae.$separador;
        echo $cnaeDescricao.$separador;
        echo $nomeCompleto.$separador;
        echo $cargo.$separador;
        echo $CPF.$separador;
        echo $enderecoContatoRua.$separador;
        echo $enderecoContatoNumero.$separador;
        echo $enderecoContatoComplemento.$separador;
        echo $enderecoContatoBairro.$separador;
        echo $enderecoContatoCidade.$separador;
        echo $enderecoContatoEstado.$separador;
        echo $enderecoContatoCEP.$separador;
        echo $telefoneFixoContato.$separador;
        echo $celularContato.$separador;
        echo $emailContato.$separador;
        echo $dataNascimento.$separador;
        echo $sexo.$separador;
       // echo $nivelEscoladidade.$separador;

        if ($this->isRanking) {
            echo $separador; 
            echo $gestaoTotal."";
            echo $separador; 
            echo $enfoque."";
            echo $separador;        
            echo $gestaoLideranca."";
            echo $separador; 
            echo $gestaoEstrategias."";
            echo $separador; 
            echo $gestaoClientes."";
            echo $separador; 
            echo $gestaoSociedade."";
            echo $separador; 
            echo $gestaoInformacoes."";
            echo $separador; 
            echo $gestaoPessoas."";
            echo $separador; 
            echo $gestaoProcessos."";
            echo $separador; 
            echo $gestaoResultados."";
            echo $separador; 
            echo $inovacao."";
            echo $separador; 
            echo $responsabilidade."";
        }
        
        echo $digitadorLogInscricao.$separador;
        //echo $logInscricao.$separador;
        echo $digitadorLogGerouDevolutiva.$separador;
        //echo $logGerouDevolutiva.$separador;
        echo $novalinha; 
        $i = $i + 1;
   }
   
   echo $novalinha; 
   
   endif;

