<?php
$request = $this->request();
$controller = $request->getControllerName();
$action = $request->getActionName();

$fluid = false;
$buttonExport = true;

$this->headScript()
    ->appendFile($this->baseUrl('js/address/capital.js'))
    ->appendFile($this->baseUrl('js/management/enterprise.js?133xv2'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.metadata.js'))
    ->prependFile($this->baseUrl('js/validation/jquery.validate.min.js'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.form322.min.js'));

//Permissão para alterar/responder questionário
$permissionRespondAll = ($this->loggedAllowed('index', 'questionnaire:respond')
    and $this->loggedAllowed('answer', 'questionnaire:respond')
    and $this->loggedAllowed('not-coop-responding', 'management:questionnaire')
);        
$permissionPremioEligibility = $this->loggedAllowed('do-premio-eligibility', 'management:enterprise');

$competitionId = (isset($this->filter['competition_id']))? $this->filter['competition_id'] : $this->competitionId;

$isCurrentCompetition = ($this->competitionId == $competitionId)?TRUE:FALSE;

switch ($action) {
    case 'ranking':
        $titulo = 'Ranking Candidatas Estaduais';
        $includeFile = 'ranking-candidatas.phtml';
        break;

    case 'classificadas':
        $titulo = 'Ranking Classificadas Estaduais';
        $includeFile = 'ranking-classificadas.phtml';
        $buttonExport = true;
        break;

    case 'finalistas':
        $titulo = 'Ranking Finalistas Estaduais';
        $includeFile = 'ranking-finalistas.phtml';
        $buttonExport = true;
        break;

    case 'candidatas-nacional':
        $titulo = 'Ranking Candidatas Nacionais';
        $includeFile = 'candidatas-nacional.phtml';
        $buttonExport = true;
        break;

    case 'classificadas-nacional':
        $titulo = 'Ranking Classificadas Nacionais';
        $includeFile = 'classificadas-nacional.phtml';
        $buttonExport = true;
        break;

    case 'finalistas-nacional':
        $titulo = 'Ranking Finalistas Nacionais';
        $includeFile = 'finalistas-nacional.phtml';
        $buttonExport = true;
        break;

    case 'report-global':
        $titulo = 'Panorama das Respostas';
        $includeFile = 'report-global.phtml';
        $buttonExport = true;
        break;

    case 'report-regional':
        $titulo = 'Participantes por Escritório Regional';
        $includeFile = 'report-regional.phtml';
        $fluid = true;
        $buttonExport = true;
        break;

    case 'report-digitador':
        $titulo = 'Participantes por Digitador';
        $includeFile = 'report-digitador.phtml';
        $fluid = true;
        $buttonExport = true;
        break;

    case 'report-categoria':
        $titulo = 'Participantes por Setor';
        $includeFile = 'report-categoria.phtml';
        $fluid = true;
        $buttonExport = true;
        break;

    case 'report-categoria-premio':
        $titulo = 'Participantes por Categoria do Prêmio';
        $includeFile = 'report-categoria-premio.phtml';
        $fluid = true;
        $buttonExport = true;
        break;

    case 'report-inscricoes':
        $titulo = 'Preenchimento de Inscrições - Estado';
        $includeFile = 'report-inscricoes.phtml';
        $extraMainClass = 'report-inscricoes';
        $fluid = true;
        $buttonExport = true;
        break;

    case 'report-status-appraiser':
        $titulo = 'Relatório Status Avaliação';
        $includeFile = 'report-status-appraiser.phtml';
        $extraMainClass = 'report-inscricoes';
        $fluid = true;
        $buttonExport = true;
        break;

    case 'report-status-verificador':
        $titulo = 'Relatório Status Verificação';
        $includeFile = 'report-status-verificador.phtml';
        $extraMainClass = 'report-inscricoes';
        $fluid = true;
        $buttonExport = true;
        break;
    
    
    default:
        $titulo = 'Inscrições';
        $includeFile = 'lista-inscricoes.phtml';
        break;
}
?>

<h1 class="title"><?php echo $titulo; ?> - Busca</h1>

    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>

    <?php echo $this->buscaPadrao($this->filter); ?>    

    <?php if ($this->getAllEnterprise and $this->getAllEnterprise instanceof Zend_Paginator): ?>
        <div class="table-menu header">
            <?php
                $total = $this->getAllEnterprise->getTotalItemCount();
                $label_total = (($total > 0) ? implode(' ', array(
                  $total,
                  implode('', array(
                    'registro',
                    (($total > 1) ? 's' : '')
                  ))
                )) : 'Nenhum registro encontrado');
            ?>
            <hgroup>
              <a name="lista"></a>
              <h2><?php echo $titulo; ?> - <span><?php echo $label_total; ?></span></h2>
            </hgroup>
            
            <?php if ($buttonExport): ?>
                <div class="nav tools">
                  <p>Ferramentas:</p>
                  <ul>
                    <li>
                        <a href="<?php echo $this->baseUrl('management/enterprise/' . $this->request()->getActionName() . '/?' . $this->urlParaGerarCsv); ?>" 
                           target="_blank" title="Exportar empresas"><span>Exportar<i> empresas</i></span></a>
                    </li>
                  </ul>
                </div>
            <?php endif; ?>
          <?php echo $this->paginationControl($this->getAllEnterprise, null, null); ?>
        </div>

        <?php if ($action == 'ranking') : ?>
        <fieldset style="border: 1px solid #ccc; width: 370px; margin-left: -7px;" class="fontMeta">
            <legend class="">Legenda</legend>
              <div style="height: 16px; width: 16px; float: left;" class="ineligibility1"></div> Porte da empresa e Data de abertura inválidos <br />
              <div style="height: 16px; width: 16px; float: left;" class="ineligibility2"></div> Data de abertura inválida <br />
              <div style="height: 16px; width: 16px; float: left;" class="ineligibility3"></div> Porte da empresa inválido
        </fieldset>
        <?php endif; ?>

        <div class="table-container">
            <?php include $includeFile; ?>
        </div>

        <div class="table-menu footer">
          <?php echo $this->paginationControl($this->getAllEnterprise, null, null); ?>
        </div>
    <?php elseif($this->getAllEnterprise): ?>

            <?php include $includeFile; ?>

    <?php endif; ?>
