<?php
$this->headScript()
    ->appendFile($this->baseUrl('js/lib/modernizr.js'))
    ->appendFile($this->baseUrl('js/lib/jquery.inview.js'))
    ->appendFile($this->baseUrl('js/lib/chart/Chart.js'))
    ->appendFile($this->baseUrl('js/management/report.js'));
$i = 0;
?> 
<div style="display: table; clear: both;">
    <div class="table-menu header">
          <hgroup><a name="lista"></a><h2><?php echo $titulo; ?>

              </h2>
          </hgroup>
         <?php if ($buttonExport): ?>
          <div class="nav tools">
            <p>Ferramentas:</p>
            <ul>
              <li><a href="<?php echo $this->baseUrl('management/enterprise/report-inscricoes/?' . $this->urlParaGerarCsv); ?>" target="_blank" title="Exportar empresas">
                      <span>Exportar<i> empresas</i></span></a>
              </li>
            </ul>
            </div>
        <?php endif; ?>
    </div>
    <div class="table-container <?php echo ($fluid  ? 'fluid' : ''); ?>">
        <table class="table">
          <thead>
            <tr>
              <th>Estado</th>
              <th>Realizadas pelos digitadores</th>
              <th>Realizadas pelas próprias empresas</th>
            </tr>
          </thead>

            <?php if (count($this->dataReport) >= 1): ?>

              <tbody>

                <?php
                for ($index1 = 1; $index1 < 28; $index1++) {
                    //$dataDigitadores[$index1] = 0;
                    $dataInscricoes[$index1] = 0;
                }
                $totalInscricoesEmpresas = 0;
                $totalInscricoesDigitadores = 0 ;
                $ufs = array();
                foreach ($this->dataReport as $index => $dataRow):
                    //$dataDigitadores[$dataRow->getStateId()] = $dataRow->getAceiteDigitadoresQt();
                    //$totalDigitadores += $dataRow->getAceiteDigitadoresQt();
                    $dataInscricoes[$dataRow->getStateId()] = $dataRow->getAceiteEmpresaQt() + $dataRow->getAceiteDigitadoresQt();
                    $ufs[$dataRow->getStateId()] = $dataRow->getUf();
                    $totalInscricoesEmpresas += $dataRow->getAceiteEmpresaQt();
                    $totalInscricoesDigitadores += $dataRow->getAceiteDigitadoresQt(); ?>
                  
                    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="">
                        <td>
                            <span class="left">
                                <?php echo $dataRow->getState(); ?>
                            </span>
                        </td>
                        <td class="middle"><span><?php echo $dataRow->getAceiteDigitadoresQt(); ?></span></td>
                        <td class="middle"><span><?php echo $dataRow->getAceiteEmpresaQt(); ?></span></td>
                    </tr>

                <?php endforeach; ?>

              </tbody>
            <?php endif; ?>
        </table>
    </div>

    <?php
	asort($dataInscricoes);
    $dataInscricoesPercent = array();
    foreach ($dataInscricoes as $StateId => $dataQt) {
        $dataInscricoesPercent[$StateId] = round((float)((100*($dataQt))/($totalInscricoesEmpresas+$totalInscricoesDigitadores)),1);
    }
    $i = 0;

    $this->headScript()->captureStart() ?>
        var INSCRICOES_JSON = '<?php echo json_encode($dataInscricoes); ?>';

        var INSCRICOES_PORCENT_JSON = '<?php echo json_encode($dataInscricoesPercent); ?>';
        var UFS_JSON = '<?php echo json_encode($ufs); ?>';
        var TOTALEMPRESAS = <?php echo $totalInscricoesEmpresas; ?>;
        var TOTALDIGITADORES = <?php echo $totalInscricoesDigitadores; ?>;
        var TOTALEMPRESASPORCENT = <?php echo round((float)((100*($totalInscricoesEmpresas))/($totalInscricoesEmpresas+$totalInscricoesDigitadores)),1); ?>;
        var TOTALDIGITADORESPORCENT = <?php echo round((float)((100*($totalInscricoesDigitadores))/($totalInscricoesEmpresas+$totalInscricoesDigitadores)),1); ?>;
    <?php
    $this->headScript()->captureEnd()
    ?>
        <div style="clear: both; padding-bottom: 1em; height: 395px;">
    <div id="areaChartInscricoes" class="hidden" style="width: 50%; float: left; margin-top: 1.5em">
        <div class="table-menu header">
            <hgroup><h2> Inscritas por Estado </h2> </hgroup>
        </div>
        <div class="canvasWrapper">
            <canvas id="chartInscricoes" width="449" height="300"></canvas>		
        </div>
    </div> 

    <div id="areaChartInscricoes2" class="hidden" style="width: 50%; float: left; margin-top: 1.5em">
        <div class="table-menu header">
        <hgroup><h2> Inscritas Geral </h2> </hgroup>
        </div>
        <div class="canvasWrapper">
            <canvas id="chartInscricoes2" width="449" height="300"></canvas>		
        </div>
    </div>
        </div>
        
    <div class="table-menu header" style="clear: left">
          <hgroup><a name="lista"></a><h2>Preenchimento de Inscrições - Setor 
              </h2>
          </hgroup>
         <?php if ($buttonExport): ?>
          <div class="nav tools">
            <p>Ferramentas:</p>
            <ul>
              <li><a href="<?php echo $this->baseUrl('management/enterprise/report-inscricoes/?' . $this->urlParaGerarCsv); ?>" target="_blank" title="Exportar empresas"><span>Exportar<i> empresas</i></span></a></li>
            </ul>
            </div>
        <?php endif; ?>
    </div>
        
    <div class="table-container <?php echo ($fluid  ? 'fluid' : ''); ?>">
        <table class="table">
          <thead>
            <tr>
              <th>Categoria</th>
              <th>Realizadas pelos digitadores</th>
              <th>Realizadas pelas próprias empresas</th>
            </tr>
          </thead>

            <?php if (count($this->dataCategoriaReport) >= 1): ?>

              <tbody>

                <?php
                $categoriaMpe = Vtx_Util_Array::categoriaMpe();
                foreach ($this->dataCategoriaReport as $index => $dataRow):
                ?>
                    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="">
                        <td>
                            <span class="left">
                                <?php echo $categoriaMpe[$dataRow->getCategoriaId()]; ?>
                            </span>
                        </td>
                        <td class="middle"><span><?php echo $dataRow->getAceiteDigitadoresQt(); ?></span></td>
                        <td class="middle"><span><?php echo $dataRow->getAceiteEmpresaQt(); ?></span></td>
                    </tr>

                <?php endforeach; ?>

              </tbody>
            <?php endif; ?>
        </table>
    </div>
</div>