<?php
$i = 0;
$this->headScript()->captureStart() ?>
      var DATA_RADAR = [
      <?php
          echo $this->dataCriteriosPoncent[0] . ',';
          echo $this->dataCriteriosPoncent[1] . ',';
          echo $this->dataCriteriosPoncent[2] . ',';
          echo $this->dataCriteriosPoncent[3] . ',';
          echo $this->dataCriteriosPoncent[4] . ',';
          echo $this->dataCriteriosPoncent[5] . ',';
          echo $this->dataCriteriosPoncent[6] . ',';
          echo $this->dataCriteriosPoncent[7];
      ?>
      ];
<?php $this->headScript()->captureEnd(); ?>        
      
<?php if ($this->showRadar): ?>
    <div class="table-menu header">
    <hgroup><a name="lista"></a><h2>Autoavaliação da Gestão - Desempenho Global da Empresas </h2>
    </hgroup>
  </div>      

    <div id="radarChart" class="hidden" style="width: auto; padding: 0">
        <div class="canvasWrapper">
            <canvas id="radarChartCanvas" width="500" height="480" style="margin-bottom: -36px; margin-top: -46px; margin-left: 0"></canvas>		
        </div>
    </div>
 
    <table id="table-details" class="chart" style="width: 40%; margin-top: 1.8em">
        <thead>
            <tr>
			    <th></th>
                <th>Critério</th>
                <th>Pontuação Máxima</th>
                <th>Média seleção</th>
                <th>%</th>
            </tr>
        </thead>
        <?php foreach ($this->dataCriterios as $criterio => $pontuacao): 
                if ($i <> 0) : ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $criterio; ?></td>
                <td><?php echo number_format((double)$this->pontuacaoMaxima[$i],0,',','.'); ?></td>
                <td><?php echo number_format($pontuacao,4,',','.'); ?></td>
                <td><?php echo number_format($this->dataCriteriosPoncent[$i-1],2,',','.'); ?>%</td>
            </tr>
        <?php endif; $i++; endforeach; ?>
    </table>
<?php endif; ?> 
<div class="table-menu header">
    <hgroup><a name="lista"></a><h2> Panorama das Respostas dos Questionários </span> </h2> </hgroup>
    <?php if ($buttonExport): ?><div class="nav tools">
    <p>Ferramentas:</p>
     
        <ul>
        <li><a title="Exportar empresas" target="_blank" href="<?php echo $this->baseUrl('management/enterprise/report-global/?' . $this->urlParaGerarCsv); ?>"><span>Exportar<i> empresas</i></span></a></li>
        </ul>
    
    </div><?php endif; ?>
</div>
      
      <ul class="ulTabQuestions relatorio">
  <?php
    $questionsNumber = 0;
    $Question = new Model_Question;
    foreach ($this->questions['Criterions'] as $criterionId => $criterion):
       $uniqueCriterion = ($criterion['CriterionValue'] != '')?false:true;
  ?>
  <li class="criterionItem <?php echo  !$uniqueCriterion?'':'openned uniqueCriterion'; ?>">
    <div class="<?php echo  !$uniqueCriterion?'':'uniqueCriterion'; ?>">
      <?php echo $criterion['CriterionValue']; ?>
    </div>
    <ul>
      <?php
            foreach ($criterion['Questions'] as $questionId => $question):
                $alternatives = $this->alternativesByQuestion[$questionId];
                ++$questionsNumber;
                $qtRespostasQuestao = 0;
                $arrayImprimeAlterativa = array();
                $questionData = $Question->cacheOrModelQuestionById($questionId);
                //calculo porcentagem
                foreach ($alternatives as $alternativeId => $alternative) {
                    $qtRespostasAlternativa = isset($this->qtRespostasAlternativa[$alternative['Id']])? $this->qtRespostasAlternativa[$alternative['Id']] : 0;
                    $qtRespostasQuestao += $qtRespostasAlternativa;
                    $arrayImprimeAlterativa[] = array($qtRespostasAlternativa, $alternative['Value']);
                }
          ?>
        <li>
          <b>
            <?php echo ((($this->blockId == 52) && ($questionsNumber == 9)) ? implode('.', array(($questionsNumber - 1), 1)) : $questionsNumber); ?>)
            <?php echo str_replace(array('<a ', '</a>'), array('<b ', '</b>'), $questionData['V']); ?>
          </b>
            <ol>
                <?php foreach ($arrayImprimeAlterativa as $alternativa): ?>
                    <li>
                      <div>
                          <span class="percentage"><?php echo number_format(($alternativa[0]/$qtRespostasQuestao)*100, 2, ',', '.') ?>%</span>
                          <span class="value">(<?php echo number_format($alternativa[0], 0, ',', '.'); ?>)</span>
                          <span class="answer"><?php echo $alternativa[1]; ?></span>
                      </div>
                    </li>
                <?php endforeach; ?>
                    
            </ol>
        </li>
      <?php endforeach; ?>
    </ul>
  </li>
<?php endforeach; ?>
</ul>
