<?php
$i = 0;
?> 
<div style="display: table; width:100%">
    <div class="table-menu header">
          <hgroup><a name="lista"></a><h2><?php echo $titulo; ?>

              </h2>
          </hgroup>
         <?php if ($buttonExport): ?>
          <div class="nav tools">
            <p>Ferramentas:</p>
            <ul>
              <li><a href="<?php echo $this->baseUrl('management/enterprise/report-digitador/?' . $this->urlParaGerarCsv); ?>" target="_blank" title="Exportar empresas"><span>Exportar<i> empresas</i></span></a></li>
            </ul>
            <?php endif; ?>
        </div>
    </div>
    <div class="table-container <?php echo ($fluid  ? 'fluid' : ''); ?>">
        <table class="table" style="min-width: inherit; width: 635px;">
          <thead>
            <tr>
              <th>Estado</th>
              <th>Digitador</th>
              <th>Inscrições</th>
              <th>Alterou<br>Inscrições</th>
              <th>Candidatas<br>(Devolutiva)</th>
              <th>Alterou<br>(Devolutiva)</th>
            </tr>
          </thead>

            <?php
            if (count($this->dataReport) >= 1): ?>
              <tbody>

                <?php 
                    $inscricoesTotal=0;
                    $alterouDevolutivaTotal=0;
                    $alterouInscricoesTotal=0;
                    $candidatasDevolutivaTotal=0;
                
                    foreach ($this->dataReport as $index => $dataRow): 
                        
                        $inscricoes = $dataRow->getAceiteQt();
                        $alterouInscricoes = $dataRow->getEdicaoCompletaQt();
                        $candidatasDevolutiva = $dataRow->getDevolutivaQt();
                        $alterouDevolutiva = $dataRow->getDevolutivaRegeradaQt(); 
                        
                        $inscricoesTotal += $inscricoes;
                        $alterouInscricoesTotal += $alterouInscricoes;
                        $candidatasDevolutivaTotal += $candidatasDevolutiva;
                        $alterouDevolutivaTotal += $alterouDevolutiva; 
                        
                    ?>
                    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="">
                        <td class="middle"><?php echo $dataRow->getUfDigitador(); ?></td>
                        <td>
                            <span class="left" >
                                <?php echo $dataRow->getFirstName() . ' ' . $dataRow->getSurName(); ?>
                            </span>
                        </td>
                        <td class="middle"><span><?php echo $inscricoes; ?></span></td>
                        <td class="middle"><span><?php echo $alterouInscricoes; ?></span></td>
                        <td class="middle"><span><?php echo $candidatasDevolutiva; ?></span></td>
                        <td class="middle"><span><?php echo $alterouDevolutiva; ?></span></td>
                    </tr>

                <?php endforeach; ?>
                    
                    <tr>
                        <td class="middle"><strong>Todas UF</strong></td>
                        <td>
                            <span class="left" >
                                <strong>Todos digitadores</strong>
                            </span>
                        </td>
                        <td class="middle"><span><strong><?php echo $inscricoesTotal; ?></strong></span></td>
                        <td class="middle"><span><strong><?php echo $alterouInscricoesTotal; ?></strong></span></td>
                        <td class="middle"><span><strong><?php echo $candidatasDevolutivaTotal; ?></strong></span></td>
                        <td class="middle"><span><strong><?php echo $alterouDevolutivaTotal; ?></strong></span></td>
                        
                    </tr>

              </tbody>
            <?php
            endif;
            ?>
        </table>
    </div>
</div>