<?php
//$this->setEncoding('UTF-8');
echo "\xEF\xBB\xBF";

function rr ($value)
{
    return str_replace(',','',str_replace(';', '', $value)); 
}
function rr2 ($value)
{
    return str_replace(',','.',$value); 
}

/**
view usada para gerar conteudo do fetchall em .CSV
*/
//CONFIGURACOES
$separador = ";";
$novalinha = "\n";

echo "Número da Questão{$separador}";
echo "Questão{$separador}";
echo "Alternativa{$separador}";
echo "Porcentagem{$separador}";
echo "Valor{$separador}";
echo "Resposta{$separador}";

echo $novalinha;

$alternativaAlpha = array(
    1 => 'a',
    2 => 'b',
    3 => 'c',
    4 => 'd',
    5 => 'e',
);

if (count($this->questions['Criterions']) >= 1) :

    $questionsNumber = 0;
    $Question = new Model_Question;
    foreach ($this->questions['Criterions'] as $criterionId => $criterion):
  
    $CriterionValue = $criterion['CriterionValue']; 

        foreach ($criterion['Questions'] as $questionId => $question):
            
            $alternatives = $this->alternativesByQuestion[$questionId];
            ++$questionsNumber;
            $qtRespostasQuestao = 0;
            $arrayImprimeAlterativa = array();
            $questionData = $Question->cacheOrModelQuestionById($questionId);
            //calculo porcentagem
            foreach ($alternatives as $alternativeId => $alternative) :
                
                $qtRespostasAlternativa = isset($this->qtRespostasAlternativa[$alternative['Id']])?
                    $this->qtRespostasAlternativa[$alternative['Id']] : 0;
                $qtRespostasQuestao += $qtRespostasAlternativa;
                $arrayImprimeAlterativa[] = array($qtRespostasAlternativa, $alternative['Value']);
                
            endforeach;

            $qstNumber = ((($this->blockId == 52) && ($questionsNumber == 9)) ? implode('.', array(($questionsNumber - 1), 1)) : $questionsNumber).')'; 
            $qst = $questionData['Q']; //str_replace(array('<a ', '</a>'), array('<b ', '</b>'), $questionData['V']); 

            $i = 1;
            foreach ($arrayImprimeAlterativa as $alternativa): 
                
                echo $qstNumber;
                echo $separador;
                echo $qst;
                echo $separador;
                echo $alternativaAlpha[$i];
                echo $separador;
                echo $percentage = number_format(($alternativa[0]/$qtRespostasQuestao)*100, 2, ',', '.') .'%';
                echo $separador;
                echo $value = number_format($alternativa[0], 0, ',', '.');
                echo $separador;
                echo $answer = $alternativa[1]; 
                echo $separador;
                
                echo $novalinha; 
                
            $i = $i + 1;
            endforeach; 
            
        endforeach; 
        
        
    endforeach; 
    
   echo $novalinha;

endif;

