<?php
//include APPLICATION_PATH . '/modules/management/views/scripts/menus/admin_menu.phtml';
?>
<?php /* ?>
<h1 class="center">Empresa</h1>
<a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/enterprise/edit/id_key/'.$this->enterpriseIdKey); ?>">Voltar</a>
<?php */ ?>
<?php if (isset($this->itemEditSuccess)):?>
    <?php if ($this->itemEditSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Empresa (<?php echo $this->social_name; ?>) editada com sucesso. <br /><br />
                    Foi enviando um email com o login e senha (caso alterada) para o email da empresa.<br /><br />
                    <br />
                    <!--strong>Aguarde, redirecionando para o questionário de Empreendedorismo.</strong-->
                    <br /><br />
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($this->itemInsertSuccess)):?>
    <?php if ($this->itemInsertSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Empresa (<?php echo $this->social_name; ?>) inscrita com sucesso. <br /><br />
                    Foi enviando um email com o login e senha para o email da empresa.<br /><br />
                    <br />
                    <!--strong>Aguarde, redirecionando para o questionário de Empreendedorismo.</strong-->
                    <br /><br />
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
        <!--script>
            window.location = "<?php echo $this->baseUrl('/management/questionnaire/not-coop-responding/enterprise-id-key/'.$this->enterpriseIdKey.'/block/60'); ?>";
        </script-->