<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="">
    <h1 class="center">
        Critério ::
        <?php echo ($this->request()->getActionName() == 'insert')? 'Inserir' : 'Editar'; ?>
    </h1>
    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/criterion/'); ?>">Voltar</a>
    
    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>
    
    <form class="normal" method="POST" action="<?php echo $this->baseUrl(($this->request()->getActionName() == 'insert')? 'management/criterion/insert' : 'management/criterion/edit/id/' . $this->criterionRow->getId()); ?>">

        <fieldset>
            <label for="designation">Ordem: </label>
            <input type="text" name="designation" id="designation" readonly="readonly" value="<?php if ($this->criterionRowData) echo $this->criterionRowData['designation']; ?>">
            <br class="clear" />
            
            <label for="block_id">Bloco </label>
                <select name="block_id" id="block_id" class="fancy">
                    <?php foreach ($this->getAllBlock as $block) : ?>
                        <?php if ($this->criterionRowData['annual_result_id'] == $block->getId()) : ?>
                            <option value="<?php echo $block->getId();?>" selected="selected"> <?php echo $block->getId().' - '.$block->getValue();?> </option>
                        <?php else : ?>
                            <option value="<?php echo $block->getId();?>"> <?php echo $block->getId().' - '.$block->getValue();?> </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />

            <label for="value">Descrição: </label>
                <input type="text" name="value" id="value" value="<?php if ($this->criterionRowData) echo $this->criterionRowData['value']; ?>">
            <br class="clear" />

            <label for="long_description">Long Description: </label>
                <textarea name="long_description" id="long_description"><?php if ($this->criterionRowData) echo $this->criterionRowData['long_description']; ?></textarea>
            <br class="clear" />
            
            <label for="conclusion_text">Conclusion Text: </label>
                <textarea name="conclusion_text" id="conclusion_text"><?php if ($this->criterionRowData) echo $this->criterionRowData['conclusion_text']; ?></textarea>
            <br class="clear" />
        </fieldset>

        <div class="clear"> </div>
        <button type="submit" class="save">Finalizar</button>
        <div class="clear"> </div>
	</form>
</div>