<?php //echo $this->headScript()->appendFile($this->baseUrl('js/question/add.js')); ?>
<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="">
    <h1 class="center">Critério</h1>
    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/'); ?>">Voltar</a>
    
    <?php if ($this->criterionInsertSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Critério inserido com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>

    <?php if ($this->criterionUpdateSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Critério atualizado com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>

    <?php if ($this->criterionDeleteSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Critério deletado com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>

    <?php if ($this->criterionMoveSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Critério Movido com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>

    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>

    <?php if ($this->loggedAllowed('insert')): ?>
        <a href="<?php echo $this->baseUrl('management/criterion/insert'); ?>" title="Criar Critério" class="link"><span class="ico new large">Novo</span>Criar Critério</a>
    <?php endif; ?>

<hr />
<h3>filtro: Bloco </h3>
    <form class="normal" method="POST" action="<?php echo $this->baseUrl('management/criterion/index/block_id/'); ?>">
        <fiedset>
            <label for="block_id"></label>
            <select name="block_id" id="block_id" class="w400 fancy">
                    <?php foreach ($this->getAllBlock as $block) : ?>
                        <?php if ($this->blockId == $block->getId()) :?>
                            <option value="<?php echo $block->getId();?>" selected="selected">
                                <?php echo $block->getId().' - '.$block->getValue();?>
                            </option>
                        <?php else: ?>
                            <option value="<?php echo $block->getId();?>">
                                <?php echo 
                                        $block->findParentQuestionnaire()->getId().' - '.
                                        $block->findParentQuestionnaire()->getDescription().' - '.
                                        $block->getId().' - '.
                                        $block->getValue();
                                ?>
                            </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />
            <br class="clear" />
        </fiedset>
        <div class="clear"> </div>
        <button type="submit" class="save">Filtrar</button>
        <div class="clear"> </div>
	</form>

    <table class="striped " border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th>Questionário</th>
                <th>Bloco</th>
                <th>Ordem</th>
                <th>Critério</th>
                <th>Ações</th>
                <th>Mover</th>
            </tr>
        </thead>
    <?php
    if ( count($this->getAllCriterion) > 0 ) :
        foreach ($this->getAllCriterion as $criterion) :
        ?>
            <tr>
                <td><?php echo $criterion->findParentBlock()->findParentQuestionnaire()->getTitle();?></td>
                <td><?php echo $criterion->findParentBlock()->getValue();?></td>
                <td><?php echo $criterion->getDesignation();?></td>
                <td><?php echo $criterion->getValue();?></td>
                <td>
                    <?php if ($this->loggedAllowed('edit', 'management:privilege')): ?>
                        <a href="<?php echo $this->baseUrl('management/criterion/edit/id/'.$criterion->getId()); ?>" alt="editar"><span class="ico edit">Editar</span></a>
                    <?php endif; ?>
                    <?php if ($this->loggedAllowed('delete', 'management:privilege')): ?>
                        <a href="<?php echo $this->baseUrl('management/criterion/delete/id/'.$criterion->getId()); ?>"><span class="ico delete">Excluir</span></a>
                    <?php endif; ?>
                </td>
                <td><a href="<?php echo $this->baseUrl('management/criterion/move/id/'.$criterion->getId()); ?>"><span class="ico insert">Mover</span></a></td>
            </tr>
        <?php
        endforeach;
        else :
        ?>
            <tr>
                <td colspan="6"> Não há Critérios para este Bloco.</td>
            </tr>
    <?php
    endif;
    ?>
    </table>

<hr />

</div>
