<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="">
    <h1 class="center">Critério :: Trocar ordem</h1>
    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/criterion/'); ?>">Voltar</a>

    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>
    
    <form class="normal" method="POST" action="<?php echo $this->baseUrl('management/criterion/move/id/'. $this->criterionRow->getId()); ?>">

        <fieldset>

            <label for="id">Bloco / posição / Critério Atual: </label>
                <?php echo $this->criterionRow->getBlockId().' - '.$this->criterionRow->getDesignation().' - '.$this->criterionRow->getValue(); ?>
            <input  type="hidden" name="id" readonly="readonly" id="id" value="<?php echo $this->criterionRow->getId(); ?>">
            <br class="clear" />
            <hr />
            <label for="new_position_designation">Block / posição / Trocar com Critério: </label>
                <select name="new_position_designation" id="new_position_designation" class="w300 fancy">
                    <?php foreach ($this->getAllCriterion as $criterion) : ?>
                        <?php if($criterion->getId() != $this->criterionRow->getId() ) :?>
                            <?php if($criterion->getBlockId() == $this->criterionRow->getBlockId() ) : ?>
                                <option value="<?php echo $criterion->getId(); ?>">
                                    <?php echo $criterion->getBlockId().' - '. $criterion->getDesignation().' - '. $criterion->getValue(); ?>
                                </option>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />

        </fieldset>

        <div class="clear"> </div>
        <button type="submit" class="save">Finalizar</button>
        <div class="clear"> </div>
	</form>
</div>