<div class="page-cronograma">
<h2>CRONOGRAMA</h2>
<h3>
    Sua trajetória pode abrir caminho<br>
    para milhares de outras mulheres
</h3>
<div class="box-cronograma cf">
    <div class="float--left">
        <table class="tbl-show">
            <tr>
                <td class="laranja" id="crono-principal">
                    <div style="position: relative;">
                        <div style="width: 200px; margin: 0 auto">
                            <strong id="showDia" class="showDia">08 março</strong>
                        </div>
                        <hr class="both">
                        <div id="showDescricao" style="margin: 0 auto; width: 190px">Início das candidaturas 2016</div>
                        <div id="crono-prev" class="crono-nav" title="Anterior">Anterior</div>
                        <div id="crono-next" class="crono-nav"  title="Próxima">Próxima</div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="float--left">
        <table class="tbl" id="table-datas">
            <tr>
                <td class="crono-date roxo" data-dia="08 março" data-descricao="Início das candidaturas 2016">08<br>março</td>
                <td class="crono-date roxo" data-dia="31 julho" data-descricao="Término das candidaturas">31<br>julho</td>
                <td class="crono-date roxo" data-dia="setembro/outubro" data-descricao="Avaliação e Visitas Etapa Estadual">setembro/<br>outubro</td>
            </tr>
            <tr>
                <td class="crono-date rosa" data-dia="novembro/dezembro" data-descricao="Reconhecimento Estadual 2016">novembro/<br>dezembro</td>
                <td class="crono-date rosa" data-dia="16 dezembro" data-descricao="Divulgação das Vencedoras Estaduais">16<br>dezembro</td>
<!--                 <td class="crono-date cinza disable" data-dia="" data-descricao="">/</td> -->
                 <td class="crono-date rosa" data-dia="1 à 9 dezembro 2016" data-descricao="Leitura dos relatos">1 à 9<br>dezembro<br>2016</td>
            </tr>
            <tr>
                <td class="crono-date vermelho flush" data-dia="29 de novembro de 2016 a fevereiro de 2017" data-descricao="Etapa Nacional 2016" colspan="2">
                    <table>
                        <tr>
                           
                            <td class="this-or-this__or" data-dia="12 à 16 dezembro 2016" data-descricao="Definição das visitadas">12 à 16<br>dezembro<br>2016</td>
                            <td class="this-or-this__this"  data-dia="9 à 20 janeiro 2017" data-descricao="Visitas">9 à 20<br>janeiro<br>2017</td>
                        </tr>
                    </table>
                </td>
                <td class="crono-date cinza-escuro" data-dia="7 de março de 2017" data-descricao="Reconhecimento Nacional 2016">07<br>março 2017<br></td>
            </tr>
        </table>
    </div>
</div>
</div>
