<div id="container" class="boxWhite container page-participar">
    <h2>COMO PARTICIPAR</h2>
    <h3>

    </h3>
 
    <p>Para participar, preencha a ficha de inscrição, acompanhada do relato escrito da empreendedora e da autoavaliação sobre o negócio (ver anexo III do Regulamento). A candidatura só será considerada completa com o preenchimento de todos os campos do cadastro, conclusão do relato conforme regulamento e autoavaliação do negócio totalmente preenchida. Lembrar ainda de gerar a Devolutiva, que será enviada automaticamente para o e-mail fornecido no cadastro.</p>
    <p>As inscrições terão início dia <b>08 de março de 2015</b>, e se encerrarão às <b>23h59 do dia
31 de julho de 2015.</b> Para entrega dos formulários de inscrição por meio físico (impresso) será observado o mesmo
período de inscrição, e será considerada a data de entrega no SEBRAE ou a postagem no correio (respeitando o horário normal de funcionamento).</p>
    <p>Para fins de verificação do cumprimento do prazo de inscrição, será considerada a
data de entrega no SEBRAE, a postagem no correio ou, ainda, o protocolo emitido
pela Internet.</p>
    <p>As inscrições são gratuitas e poderão ser realizadas nas seguintes modalidades:</p>
    <ul><li>Inscrição
eletrônica
pela
<b>
www.mulherdenegocios.sebrae.com.br</b></li>
        <li>Inscrição em ficha que acompanha o regulamento, anexo I, também
disponível em todas as unidades do SEBRAE que deve ser enviada pelo
correio ou entregue na unidade do seu Estado.</li>
    </ul>
    <p>A realização da inscrição implica na aceitação e concordância das condições do
regulamento.</p>
    
      <p>As participantes deverão observar os seguintes pontos no ato de inscrição:</p>
    <ul>
        <li>Cada relato inscrito só poderá referir-se a um CNPJ e uma
única vez no ciclo vigente;</li>
        <li>As inscrições incompletas, sem assinatura quando em
papel, fora do padrão e do prazo deste regulamento serão
desclassificadas.</li>
    </ul></div>
<?php /* ?>
<div class="navegacao">
    <a href="#" id="up"><i class="i ir bt-up">up</i></a>
    <a href="#" id="down"><i class="i ir bt-down">down</i></a>
</div>
<?php */ ?>
