<div id="container" class="boxWhite container page-premio">
    <h2>O QUE É O PRÊMIO?</h2>
    <h3>Reconhecimento estadual e nacional às mulheres que transformaram seus sonhos em realidade.</h3> 
    <p>É o reconhecimento estadual e nacional às mulheres que transformaram seus sonhos em realidade, e cuja vida é
        exemplo para tantas outras mulheres que sonham ser empreendedoras.</p>
    <p>O prêmio é uma parceria entre o Serviço Brasileiro de Apoio às Micro e Pequenas Empresas (SEBRAE), a Secretaria
        de Políticas para as Mulheres (SPM) e a Federação das Associações de Mulheres de Negócios e
        Profissionais do Brasil (BPW), com apoio técnico da Fundação Nacional da Qualidade (FNQ).</p>
</div>
