<div id="container" class="boxWhite container page-premiacao">
    <h2>PREMIAÇÃO</h2>
    <h3>Destaque valores positivos, que possam incentivar outras mulheres.</h3> 
    
    <p>O Prêmio SEBRAE Mulher de Negócios é composto por 2 (duas) etapas: estadual e nacional.</p>

    <h4>Etapa Estadual</h4>
    <p>Nesta etapa, podem ser reconhecidas como vencedoras estaduais até 3 (três) empreendedoras de cada estado e 3
        (três) do Distrito Federal; uma para cada categoria prevista, podendo-se chegar a até 81 empreendedoras em todo
        o Brasil.</p>
    <p>
        <b>Todas Unidades da federação do SEBRAE, oferecerão as suas vencedoras:</b>
    </p>
    
    
    
    <ul>
        <li>Uma placa/ troféu de reconhecimento; </li>
        <li>Certificado de premiação;</li>
        <li>Direito ao uso do selo de vencedora, explicitando o ciclo;</li>
        <li>Um curso da Matriz de Soluções Educacionais e/ou 16 (dezesseis) horas técnicas de consultoria em gestão.</li>
    </ul>


    <h4>Etapa Nacional</h4>
    <p>Dentre as 81 empreendedoras selecionadas, elas serão avaliadas e selecionadas por uma comissão técnica nacional,
        considerando os critérios de julgamento descritos no artigo 7º deste regulamento, para a escolha de até 9 (nove)
        finalistas: 3 (três) representantes de cada categoria (Pequenos Negócios, Produtora Rural e Microempreendedora
        Individual).</p>
<p>
Todas as 81 empreendedoras receberão:
    </p>
    <ul>
        <li>Viagem para participar do evento da etapa nacional em
Brasília.</li>
    </ul>
    <p>Os 9 (nove) relatos escolhidos serão as finalistas nacionais que serão avaliadas e classificadas por uma comissão técnica nacional, considerando os seguintes critérios de julgamento:</p>
    <ol>
        Na Gestão:
        <li>Marketing e Vendas;</li>
        <li>Finanças;</li>
        <li>Gestão de Pessoas;</li>
        <li>Processos e Operação;</li>
        <li>Inovação e Tecnologia;</li>
        <li>Legislação e Normas;</li>
        <li>Estratégia;</li>
        <li>Empreendedorismo.</li>
    </ol>
    <ol>
        No Relato:
        <li>Superação da mulher; </li>
        <li>Visão de Futuro; </li>
        <li>Ideias inovadoras e adaptação às novas tendências; </li>
        <li>Atuação democrática, transparente, inspiradora e motivadora; </li>
        <li>Participação ativa nos negócios, perseverança e superação dos desafios;</li>
        <li>Ambiente participativo e agradável para quem trabalha no seu negócio; </li>
        <li>Estabelecimento de relacionamentos duradouros com os clientes; </li>
        <li>Preocupação com a preservação do meio ambiente e da cultura da sua região; </li>
        <li>Estabelecimento de parcerias para o desenvolvimento das atividades;</li>
        <li>Lições aprendidas (por meio de experimentações, erros cometidos ou compartilhamento de informações); </li>
        <li>Crescimento dos resultados obtidos; </li>
        <li>Contribuição para o desenvolvimento de outras empreendedoras.</li>
    </ol>
    <p>I – As ganhadoras do troféu ouro, prata e bronze receberão uma viagem para
capacitação em território nacional;</p>
    <p>II – Selo de vencedora nacional, explicitando o ciclo;</p>
    <p>III – As três ganhadoras nacionais receberão, além do troféu ouro, do selo e da
capacitação em território nacional, uma viagem internacional.</p>
    
        <ul>
        <li>As ganhadoras estaduais do prêmio só poderão concorrer
novamente após 2 (dois) anos da sua premiação.</li>
    </ul>
    
    <p>As ganhadoras nacionais do prêmio, contempladas com a viagem internacional, não
poderão concorrer mais ao Prêmio SEBRAE Mulher de Negócios.</p>
    
    <p>As candidatas receberão uma devolutiva, via e-mail, e com base em sua autoavaliação, após finalizar sua inscrição no site. Essa inscrição engloba o preenchimento de todos os campos da ficha com os dados da empresa e pessoais, mais o relato e o preenchimento do questionário sobre o negócio.</p>
</div>
<?php /* ?>
<div class="navegacao">
    <a href="#" id="up"><i class="i ir bt-up">up</i></a>
    <a href="#" id="down"><i class="i ir bt-down">down</i></a>
</div>
<?php */ ?>
