<div id="container" class="boxWhite container page-regulamento">
  <h2>REGULAMENTO</h2>
  <h3>2015</h3>

  <p>
    <a href="<?php echo $this->baseUrl('/files/psmn2015-regulamento-2015-v2.docx'); ?>" title="Baixe aqui o regulamento">Baixe aqui o regulamento</a>
  </p>
  
  <p>O Prêmio é uma parceria entre o Serviço Brasileiro de Apoio às Micro e Pequenas Empresas (SEBRAE), a Secretaria de Políticas para as Mulheres (SPM), a Federação das Associações de Mulheres de Negócios e Profissionais do Brasil (BPW) e a Fundação Nacional da Qualidade (FNQ).</p>
  <p><strong>Art. 1º - Objetivo</strong></p>
  <p>Este regulamento estabelece normas, condições e diretrizes para selecionar e reconhecer as histórias de vida de mulheres de negócios, que transformaram seus sonhos em realidade e cujos relatos sirvam de exemplos e estímulo para outras mulheres desenvolverem seu comportamento empreendedor.</p>
  <p><strong>Art. 2º - Público-alvo</strong></p>
  <p>O prêmio é dirigido a mulheres empreendedoras, com mais de 18 anos, que poderão concorrer em 3 (três) categorias:</p>
  <p>I - <strong>Pequenos Negócios:</strong> proprietárias de micro e pequenas empresas que estejam estabelecidas formalmente há, no mínimo, um ano. (data de abertura anterior a 01/03/2014, conforme consta no CNPJ);</p>
  <p>II - <strong>Produtora Rural:</strong> mulheres que explorem atividades agrícolas, pecuárias e/ou pesqueiras nas quais não sejam alteradas a composição e as características do produto in natura), e que estejam estabelecidas formalmente há, no mínimo, um ano. (data de abertura anterior a 01/03/2014, conforme documento de registro legal pertinente, descrito no artigo 7, parágrafo 2º);</p>
  <p>III - <strong>Micro Empreendedora Individual:</strong> mulheres que trabalhem por conta própria, tenham seu empreendimento legalizado, com faturamento máximo anual de até R$ 60.000,00 por ano, e não tenham participação em outra empresa como sócias ou titulares, e tenham até um(a) empregado(a) contratado(a) que receba o salário mínimo, ou o piso da categoria. (data de abertura anterior a 01/03/2014, conforme consta no CNPJ);</p>
  <p><strong>§ 1º</strong> - o faturamento anual não poderá ultrapassar R$ 3.600.000,00 (três milhões e seiscentos mil reais) segundo o Estatuto Nacional das Microempresas e das Empresas de Pequeno Porte;</p>
  <p><strong>§ 2º</strong> - não será permitida a participação de ONG, OSCIP, sindicatos, associações filantrópicas e outras de caráter semelhante, assim como empresas cujas proprietárias ou sócias sejam empregadas ou prestadoras de serviço das entidades promotoras do prêmio com acesso a informações privilegiadas do processo de avaliação.</p>
  <p><strong>Art. 3º - Inscrições</strong></p>
  <p><strong>As inscrições terão início dia 08 de março de 2015, e se encerrarão às 23h59 do dia 31 de julho de 2015.</strong></p>
  <p>Para fins de verificação do cumprimento do prazo de inscrição, será considerada a data de entrega no SEBRAE, a postagem no correio ou, ainda, o protocolo emitido pela Internet.</p>
  <p>As inscrições são gratuitas e poderão ser realizadas nas seguintes modalidades:</p>
  <p>I - inscrição eletrônica pela Internet no endereço: www.mulherdenegocios.sebrae.com.br</span></p>
  <p>II - inscrição em ficha, também disponível em todas as unidades do SEBRAE.</p>

  <p><strong>§ 1º</strong> - a candidatura só será considerada completa com o preenchimento de todos os campos da ficha de inscrição, acompanhada do relato escrito e da autoavaliação sobre o negócio.</p>
  <p><strong>§ 2º</strong> - a realização da inscrição implica na aceitação e concordância das condições deste regulamento.</p>
  <p><strong>§ 3º</strong> - as participantes deverão observar os seguintes pontos no ato de inscrição:</p>
  <p>I - cada relato inscrito só poderá referir-se a um CNPJ, ou documento equivalente para a produtora rural, e uma única vez no ciclo vigente;</p>
  <p>II - a candidata poderá inscrever-se pelo site (www.mulherdenegocios.sebrae.com.br) ou enviar pelo correio ou entregar a ficha de inscrição na unidade do SEBRAE onde estiver sediada a sua empresa, ou na sede do SEBRAE do seu Estado;</p>
  <p>III - o horário para recebimento da ficha de inscrição em todas as unidades do SEBRAE nas Unidades da Federação será o mesmo do funcionamento da entidade;</p>
  <p><strong>§ 4º</strong> - as inscrições incompletas, sem assinatura quando em papel, fora do padrão e do prazo deste regulamento serão desclassificadas.</p>
  <p><strong>§ 5º</strong> - as ganhadoras estaduais (ouro) do prêmio só poderão concorrer novamente após 2 (dois) anos da sua premiação.</p>
  <p><strong>§ 6º</strong> - as ganhadoras nacionais (ouro) do prêmio não poderão concorrer mais ao Prêmio SEBRAE Mulher de Negócios.</p>
  <p><strong>§ 7º</strong> - as candidatas receberão uma devolutiva com base em sua autoavaliação entregue na inscrição, desde que todos os dados necessários tenham sido preenchidos.</p>
  <p><strong>Art. 4° - Apresentação do Relato</strong></p>
  <p><strong>§ 1º</strong> - o relato poderá ser escrito a mão, considerando o formulário disponibilizado abaixo. O mínimo será de 60 (sessenta) linhas e o máximo 120 (cento e vinte) linhas. Não serão aceitos anexos ou textos fora do formulário permitido.</p>
  <p><strong>§ 2º</strong> - o relato poderá ser digitado diretamente no site e deverá ter no mínimo 500 (quinhentas) palavras (3000 caracteres) a no máximo 1200 (mil e duzentas) palavras (7140 caracteres), incluindo o título.</p>
  <p><strong>§ 3º</strong> - relatos fora dos padrões especificados nos § 1º e § 2º não serão aceitos.</p>
  <p><strong>§ 4º</strong> - para escrever o relato, a empreendedora poderá seguir o roteiro, conforme instruções disponíveis no site www.mulherdenegocios.sebrae.com.br.</p>
  <p><strong>Art. 5º - Etapas</strong></p>
  <p>O prêmio é composto por 2 (duas) etapas: estadual e nacional.</p>
  <p>Parágrafo único. As melhores pontuadas na etapa estadual receberão a visita de um verificador, que validará as informações apresentadas na Autoavaliação da gestão e no relato.</p>
  <p>Etapa Estadual</p>
  <p><strong>§ 1º</strong> - nesta etapa, a avaliação da gestão e o relato inscrito serão avaliados e selecionados por uma comissão julgadora estadual, considerando os critérios de julgamento descritos no artigo 7º deste regulamento. Serão escolhidas até 3 (três) candidatas de cada Unidade da Federação: 1 (uma) da categoria <strong>Pequenos Negócios</strong>, 1 (uma) da categoria <strong>Produtora Rural</strong> e 1 (uma) da categoria <strong>Microempreendedora Individual</strong>.</p>
  <p>I - o número total de candidatas selecionadas em todas as Unidades da Federação será, no máximo, de 81 (oitenta e uma). Este número poderá ser menor caso as histórias não atendam aos critérios estabelecidos neste regulamento.</p>

  <p>II - cada SEBRAE da Unidade da Federação oferecerá às suas vencedoras:</p>
  <p>a)uma placa/ troféu de reconhecimento;</p>
  <p>b)certificado de premiação;</p>
  <p>c)direito ao selo de vencedora, explicitando o ciclo;</p>
  <p>d)um curso e/ou 16 (dezesseis) horas técnicas de consultoria em gestão.</p>
  <p>Etapa Nacional</p>
  <p><strong>§ 1º</strong> - As vencedoras estaduais (ouro) são automaticamente classificadas para a Etapa Nacional da premiação.</p>
  <p>I - todas as 81 candidatas nacionais receberão uma viagem, exclusiva para a empresária participante do prêmio não podendo repassar a outro esse direito, para participar do evento da etapa nacional em Brasília.</p>
  <p><strong>§ 2º</strong> - as 81 (oitenta e uma) candidatas nacionais, 3 (três) por Unidade da Federação, serão avaliadas por uma comissão técnica nacional, considerando os critérios de julgamento descritos no artigo 7º deste regulamento, para a escolha de até 9 (nove) vencedoras (ouro, prata e bronze) nas 3 (três) categorias: <strong>Pequenos Negócios</strong>, <strong>Produtora Rural</strong> e <strong>Microempreendedora Individual</strong>.</p>
  <p><strong>§ 3º</strong> - as candidatas nacionais serão avaliadas e classificadas, considerando os critérios de julgamento descritos no artigo 7º deste regulamento, da seguinte forma:</p>
  <p>a)3 (três) candidatas, sem considerar a região, 1 (um) de cada categoria (<strong>Pequenos Negócios</strong>, <strong>Produtora Rural</strong> e <strong>Microempreendedora Individual</strong>) receberão o troféu bronze;</p>
  <p>b)3 (três) candidatas, sem considerar a região, 1 (um) de cada categoria (<strong>Pequenos Negócios</strong>, <strong>Produtora Rural</strong> e <strong>Microempreendedora Individual</strong>) receberão o troféu prata;</p>
  <p>c)3 (três) candidatas, sem considerar a região, 1 (um) de cada categoria (<strong>Pequenos Negócios</strong>, <strong>Produtora Rural</strong> e <strong>Microempreendedora Individual</strong>) receberão o troféu ouro.</p>
  <p>I - as ganhadoras do troféu ouro, prata e bronze receberão uma viagem para capacitação em território nacional;</p>
  <p>a)a capacitação será em evento de mercado, no segmento de empreendedorismo e/ou gestão empresarial, em data e local a serem informados posteriormente.</p>
  <p>b)troféu de vencedora nacional, explicitando o ciclo.</p>
  <p>II - as 3 (três) ganhadoras nacionais receberão, além do troféu ouro, do selo de vencedora nacional e da capacitação em território nacional, uma viagem internacional.</p>
  <p>a)a agenda da viagem estará relacionada ao tema gestão empresarial e/ou ao segmento de negócio das vencedoras. O destino e período da viagem serão definidos pela coordenação do Prêmio SEBRAE Mulher de Negócios e informados com antecedência;</p>
  <p>b)selo de vencedora nacional, explicitando o ciclo.</p>
  <p><strong>§ 4º</strong> - Todos os cursos e as viagens, concedidos a título de premiação pelos promotores do Prêmio, são individuais e intransferíveis, ou seja, só podem ser usufruídos pela empresária cujo CPF foi vinculado na inscrição do prêmio.</p>
  <p><strong>§ 5º</strong> - As providências relativas à documentação para a viagem internacional serão de responsabilidade de cada participante.</p>
  <p><strong>§ 6º</strong> - Para participação nas viagens, cada empresária contemplada deverá, obrigatoriamente, assinar o Termo de Compromisso e Isenção de Responsabilidade a ser fornecido pelos Organizadores.</p>
  <p><strong>§ 7º</strong> - Caso a empresária vencedora decline da participação nos cursos e viagens, ela deverá comunicar os organizadores do prêmio, por escrito. Caso ela deseje, será fornecido um Termo de Desistência.</p>
  <p><strong>§ 8º</strong> - A participação nos eventos e viagens, incluindo toda a logística, é de uso exclusivo das empresárias vencedoras.</p>
  <p><strong>Art. 6º - Comissões Julgadoras</strong></p>
  <p>As comissões serão constituídas da seguinte forma:</p>

  <p>I - as comissões julgadoras da etapa estadual poderão ser constituídas por representantes do SEBRAE e entidades parceiras, totalizando no mínimo 3 (três) integrantes;</p>
  <p>II - a comissão julgadora da etapa nacional será composta por 2 (dois) representantes do SEBRAE Nacional e 1 (um) de cada entidade parceira, totalizando 5 (cinco) membros.</p>
  <p><strong>§ 1º</strong> - não poderão integrar as comissões profissionais vinculados direta ou indiretamente a qualquer candidata.</p>
  <p><strong>§ 2º</strong> - integrantes do processo de avaliação, de todas as etapas, cumprirão as exigências do Código de Ética deste Prêmio assumindo o compromisso de sigilo em relação aos dados e às informações que chegarem a seu conhecimento.</p>
  <p><strong>§ 3º</strong> - em caso de empate, o presidente da Comissão Julgadora terá, além do seu voto, o voto de decisão.</p>
  <p><strong>Art. 7° - Critérios de Julgamento</strong></p>
  <p>Na avaliação das candidatas serão considerados os seguintes aspectos:</p>

  <ol>
    Na Gestão:
    <li>Marketing e Vendas;</li>
    <li>Finanças;</li>
    <li>Gestão de Pessoas;</li>
    <li>Processos e Operação;</li>
    <li>Inovação e Tecnologia;</li>
    <li>Legislação e Normas;</li>
    <li>Estratégia;</li>
    <li>Empreendedorismo.</li>
  </ol>

  <ol>
    No Relato:
    <li>Superação da mulher; </li>
    <li>Visão de Futuro; </li>
    <li>Ideias inovadoras e adaptação às novas tendências; </li>
    <li>Atuação democrática, transparente, inspiradora e motivadora; </li>
    <li>Participação ativa nos negócios, perseverança e superação dos desafios;</li>
    <li>Ambiente participativo e agradável para quem trabalha no seu negócio; </li>
    <li>Estabelecimento de relacionamentos duradouros com os clientes; </li>
    <li>Preocupação com a preservação do meio ambiente e da cultura da sua região; </li>
    <li>Estabelecimento de parcerias para o desenvolvimento das atividades;</li>
    <li>Lições aprendidas (por meio de experimentações, erros cometidos ou compartilhamento de informações); </li>
    <li>Crescimento dos resultados obtidos; </li>
    <li>Contribuição para o desenvolvimento de outras empreendedoras.</li>
  </ol>

  <p><strong>§ 1º</strong> - as informações apresentadas pelas candidatas serão examinadas pela equipe técnica do SEBRAE que visitará as empresas com a gestão e os relatos melhor avaliados, <strong>de acordo com o número de empreendimentos aptos para verificação</strong>.</p>
  <p><strong>§ 2º</strong> - os empreendimentos com gestão e relatos melhores avaliados deverão apresentar, quando solicitados, os documentos que comprovem a regularidade fiscal e estatutária:</p>
  <table cellpadding="0" cellspacing="0"  border="1">
    <tbody>
    <tr>
      <td><p class=" ">Documentação</p></td>
      <td style="width: 80px;"><p>Pequenos Negócios</p></td>
      <td style="width: 80px;"><p>Produtora Rural</p></td>
      <td style="width: 80px; padding: 0px;"><p>Micro Empreendedora Individual</p></td>
    </tr>
    <tr>
      <td class="tr4 td4">Cadastro Nacional de Pessoa Jurídica (CNPJ)</td>
      <td class="tr4 td5"><p>X</p></td>
      <td class="tr4 td6"><p>&nbsp;</p></td>
      <td class="tr4 td7"><p>X (CCMEI)</p></td>
    </tr>
    <tr>
      <td class="tr0 td4">Certidão Negativa de Débito junto à Previdência Social – INSS</td>
      <td class="tr0 td5"><p>X</p></td>
      <td class="tr0 td6"><p>&nbsp;</p></td>
      <td class="tr0 td7"><p>X</p></td>
    </tr>
    <tr>
      <td class="tr0 td0"><p>Regularidade do Empregador - Certidão Negativa do FGTS – Fundo de Garantia por Tempo de Serviço</p></td>
      <td class="tr0 td1" style="width: 80px;"><p>X</p></td>
      <td class="tr0 td2" style="width: 80px;"><p>&nbsp;</p></td>
      <td class="tr0 td3" style="width: 90px; padding: 0px;"><p>X (se tiver empregado)</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p>Certidão Negativa de Débito Municipal</p></td>
      <td class="tr4 td5"><p>X</p></td>
      <td class="tr4 td6"><p>&nbsp;</p></td>
      <td class="tr4 td7"><p>X</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p>Certidão Negativa de Débito Estadual</p></td>
      <td class="tr4 td5"><p>X</p></td>
      <td class="tr4 td6"><p>&nbsp;</p></td>
      <td class="tr4 td7"><p>X</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p>Certidão Conjunta de Débitos relativos a Tributos Federais e à Dívida Ativa da União</p></td>
      <td class="tr4 td5"><p>X</p></td>
      <td class="tr4 td6"><p>&nbsp;</p></td>
      <td class="tr4 td7"><p>X</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p>Recibo de entrega da Declaração da RAIS – Relação Anual de Informações Sociais (último exercício)</p></td>
      <td class="tr0 td5"><p>X</p></td>
      <td class="tr0 td6"><p>&nbsp;</p></td>
      <td class="tr0 td7"><p>X(se tiver empregado)</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p>Contrato social com última alteração contratual ou Estatuto</p></td>
      <td class="tr4 td5"><p>X</p></td>
      <td class="tr4 td6"><p>&nbsp;</p></td>
      <td class="tr4 td7"><p>&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p>Declaração das responsáveis pela empresa, assinada também pelo contador, relatando que a mesma não ultrapassa o limite máximo de enquadramento de micro e pequena empresa, conforme Estatuto Nacional das Microempresas e das Empresas de Pequeno Porte –– Base 2014</td>
      <td class="tr0 td5"><p>X</p></td>
      <td class="tr0 td6"><p>&nbsp;</p></td>
      <td class="tr0 td7"><p>&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p>Cópia da Identidade e CPF</p></td>
      <td class="tr0 td5"><p>X</p></td>
      <td class="tr0 td6"><p>X</p></td>
      <td class="tr0 td7"><p>X</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p>Inscrição Estadual de Produtor ou Declaração de Aptidão ao PRONAF (DAP) ou CNPJ ou Registro no Ministério da Pesca ou NIRF (Número de Inscrição do Imóvel Rural na Secretaria da Receita Federal do Brasil)</p></td>
      <td class="tr4 td5"><p>&nbsp;</p></td>
      <td class="tr4 td6"><p>X</p></td>
      <td class="tr4 td7"><p>&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p>Declaração Anual para o MEI – DASN-Simei (último exercício)</td>
      <td class="tr0 td5"><p>&nbsp;</p></td>
      <td class="tr0 td6"><p>&nbsp;</p></td>
      <td class="tr0 td7"><p>X</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p>Declaração da produtora rural, de próprio punho, relatando que a mesma não ultrapassou o limite máximo de faturamento anual de R$ 3.600.000,00 –– base 2014</p></td>
      <td class="tr0 td5"><p>&nbsp;</p></td>
      <td class="tr0 td7"><p>X</p></td>
      <td class="tr0 td6"><p>&nbsp;</p></td>
    </tr>
    </tbody>
  </table>

  <p><strong>§ 3º</strong> - Se os fatos relatados não puderem ser comprovados ou se for constatado pela equipe técnica não serem verdadeiros, a candidata será desclassificada.</p>

  <p><strong>Art. 8° - Disposições Gerais</strong></p>
  <p>O objetivo dos parceiros ao instituir o Prêmio SEBRAE Mulher de Negócios é o de evidenciar o espírito empreendedor da mulher e de utilizar, em seus cursos e palestras, os melhores casos como ferramenta educacional e de incentivo.</p>
  <p><strong>§ 1º</strong> - as vencedoras se comprometem a participar de eventos promovidos pelo SEBRAE ou instituições parceiras para relatar suas experiências;</p>
  <p>I - o SEBRAE ou a instituição parceira agendará com antecedência os eventos com a empreendedora, arcando com as despesas de deslocamento e hospedagem.</p>
  <p><strong>§ 2º</strong> - as candidatas e as vencedoras de qualquer etapa cedem por tempo indeterminado sem ônus para os realizadores e promotores do Prêmio o direito de uso e a divulgação de seus relatos, imagens, sons e qualquer material complementar ou ilustrativo entregues para concorrer a este Prêmio, ou dele oriundos, em eventos; palestras; feiras; seminários; cursos presenciais; cursos virtuais; tradução para outros idiomas; assim como veiculação em todas as mídias disponíveis utilizadas pelo Sistema SEBRAE e instituições parceiras; para distribuição em bibliotecas, escolas, organizações não governamentais, imprensa, e quaisquer instituições que queiram fazer uso educacional, ou para promover ou disseminar o empreendedorismo, sem quaisquer restrições ou pagamentos.</p>
  <p><strong>§ 3º</strong> - os materiais produzidos em decorrência do prêmio serão de propriedade do SEBRAE.</p>
  <p><strong>§ 4º</strong> - as vencedoras terão direito aos prêmios indicados neste regulamento.</p>
  <p><strong>§ 5º</strong> - qualquer outra liberalidade do SEBRAE em relação a uma vencedora ou grupo de vencedoras não constituirá em direito de reivindicação das demais.</p>
  <p><strong>§ 6º</strong> - os casos considerados omissos serão submetidos à coordenação nacional do Prêmio, cuja decisão será soberana, não cabendo recurso ou apelação.</p>
  <p><strong>§ 7º</strong> - a decisão da banca de juízes é soberana e não cabe recurso ou apelação.</p>
  <p>Brasília, 2015</p>

</div>
