<html>
<head>
  <title>Busca CNAE</title>
</head>
<body>
  <center>
    <?php if ($this->formAction == 's'): ?>
      <ol id="cnae-list">
        <li>
          <span class="term"> busca por <u><i><?php echo $this->palavraBusca; ?></i></u></span>
        </li>
          <?php foreach ($this->result as $key => $resp): ?>
            <li class="item">
                <input type="radio" value="<?php echo $key; ?>" name="cnae-search-item<?php echo $key; ?>"<?php if ($key==0){ echo ' id="firstChoice"'; } ?>>
                <span class="num"><?php echo $resp['numero'] ?></span>
                <span class="desc"><?php echo $resp['descricao'] ?></span>
            </li>
          <?php endforeach;?>
      </ol>
      <?php if (!$this->result): ?>
        <li class="no-results"> Não encontrado</li>
      <?php endif;   ?>
    <?php else : ?>
      <form action="?" name="cnae" method="GET" id="form-search-cnae">
        <input type="hidden" name="envia" value="s">
        <input type="text" name="busca" value="" required minlength="3">
        <input type="submit" name="submit" value="vamos encontrar este cnae">
      </form>
    <?php endif;   ?>
  </center>
</body>
</html>