<h1 class="title">
    Confirmação de Inscrição
</h1>
<h4 class="subtitle">
    <?php if($this->success): ?>
        Sua inscrição foi confirmada com sucesso. Caso queira acessar o sistema do Prêmio SEBRAE Mulher de Negócios, <a href="/">clique aqui</a>.
    <?php else: ?>
        Não foi possível confirmar a sua inscrição. Verifique se o endereço informado é o mesmo que o recebido por e-mail.
    <?php endif; ?>
</h4>