<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <!--title>Mulher de Negócios 2014</title-->
  <title>Mulher de Negócios <?php echo $this->ciclo;?></title>
</head>
<body>
    
      <h1><a href="<?php echo $this->baseUrl(''); ?>">Tente novamente.</a></h1>
<?php if (in_array(APPLICATION_ENV, array('production', 'staging'))): ?>
    <!--
<?php endif; ?>
  <h1>Uma indisponibilidade técnica ocorreu, tente novamente.
  </h1>
    

  <h2><?php echo $this->message; ?></h2>

  <?php if (isset($this->exception)): ?>
  
    <h3>Exception information:</h3>
    <p>
    <pre><?php echo $this->exception->getMessage() ?> </pre>
    </p>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>

  <?php endif ?>
    
<?php if (in_array(APPLICATION_ENV, array('production', 'staging'))): ?>
    -->
<?php endif; ?>
</body>
</html>
