<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="pag_privilege_edit">
    <h1 class="center">Edição de privilégios do papel <b><?php echo $this->roleRow->getLongDescription(); ?></b></h1>
    <a href="<?php echo $this->baseUrl('management/role'); ?>" id="back" title="Voltar">Voltar</a>

    <form action="<?php echo $this->baseUrl('management/privilege/edit/role/' . $this->roleRow->getId()); ?>" method="POST" class="normalTable">
        <table class="striped tight" border="0" cellpadding="0" cellspacing="0">
            <caption></caption>
            <colgroup>
                <col class="firstCol" style="width: 300px;" />
                <col class="defaultCol" />
                <col class="defaultCol" />
                <col class="defaultCol" />
                <col class="defaultCol" />
                <col class="lastCol" />
            </colgroup>
            <thead>
                <tr>
                    <th> Recurso </th>
                    <th> Acesso Listar </th>
                    <th> Incluir </th>
                    <th> Editar </th>
                    <th> Excluir </th>
                    <th class="lastTd"> Outros </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->resources as $resource): ?>
                    <tr style="border: 1px solid #ccc; margin: 3px">
                        <th title="<?php echo $resource->getResourceName(); ?>"> 
                            <?php 
                            $aliasLongDescription = $resource->getLongDescriptionAlias();
                            $longDescription = $resource->getLongDescription();
                            
                            $descricaoPrivilegio = $aliasLongDescription;
                            if ($descricaoPrivilegio == '' || is_null($descricaoPrivilegio)) {
                               $descricaoPrivilegio = "<i>".$longDescription."</i>";
                            }
                            echo $descricaoPrivilegio;
                        
                            echo " <br> <span style='font-size:10px'>[{$resource->getResourceName()}]</span>";
                            ?> 
                        </th>
                        <?php
                        foreach (Model_Acl::$DEFAULT_PRIVILEGES as $privilege):
                        ?>
                            <td> 
                                <?php 
                                    //usuário logado tem permissão sobre o privilégio? 
                                    if ($this->loggedAllowed($privilege, $resource->getResourceName())): ?>
                                        <label><input name="allowPrivileges[]" value="<?php echo $resource->getId() . ':' . $privilege; ?>" type="checkbox"
                                            <?php
                                                //Permissão do papel no privilégio
                                                echo $this->acl()->isAllowed(
                                                    $this->roleRow->getDescription(), $resource->getResourceName(), $privilege
                                                )? 'checked' : ''
                                            ?> />
                                        </label>
                                <?php endif; ?>
                            </td>
                        <?php endforeach; ?>
                        <td>
                            <?php
                                $otherPrivileges = $resource->getOtherPrivileges();
                                foreach ($otherPrivileges as $privilege): ?>
                                    <?php 
                                        //usuário logado tem permissão sobre o privilégio? 
                                        if ($this->loggedAllowed($privilege->getPrivilege(), $resource->getResourceName())): ?>
                                            <label>
                                                <input type="checkbox"
                                                       name="allowPrivileges[]" value="<?php echo $resource->getId() . ':' . $privilege->getPrivilege(); ?>"
                                                <?php
                                                    echo $this->acl()->isAllowed(
                                                        $this->roleRow->getDescription(), $resource->getResourceName(), $privilege->getPrivilege()
                                                    )? 'checked' : ''
                                                ?> />
                                                <?php 
                                                
                                                    //echo $privilege->getPrivilege() ." ---"; 
                                                
                                                    //var_dump ($privilege);
                                                    
                                                   $privilegeLongDescription = $privilege->getLongDescription();
                                                   if ($privilegeLongDescription == '' || is_null($privilegeLongDescription)) {
                                                       $privilegeLongDescription = "<i>".$privilege->getPrivilege()."</i>";
                                                   }
                                                   
                                                   echo $privilegeLongDescription;
                                                ?>
                                            </label>
                                    <?php endif; ?>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="clear"> </div>
            <button class="large green" type="submit" style="float: right">
                <span class="icon" data-icon="C"></span>
                Salvar
            </button>
        
    </form>
    <hr class="clear"/>
</div>