<?php 
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');

$this->headScript()
    ->appendFile($this->baseUrl('js/management/questionnaire/edit.js'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.metadata.js'))
    ->prependFile($this->baseUrl('js/validation/jquery.validate.min.js'));

//$this->headLink()->prependStylesheet($this->baseUrl('css/custom-theme/jquery-ui-1.8.23.custom.css'));
?>
<div id="content" class="pag_answer">
    <h1 class="center">
        <?php echo ($this->request()->getActionName() == 'insert')? 'Novo questionário' : 'Dados :: <b>' . $this->questionnaireRowData['title'] . '</b>'; ?>
    </h1>
    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/questionnaire/'); ?>">Voltar</a>
    
    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>

    <form class="normal" method="POST" action="<?php echo $this->baseUrl(($this->request()->getActionName() == 'insert')? 'management/questionnaire/insert' : 'management/questionnaire/edit/id/' . $this->questionnaireRow->getId()); ?>">
        
        <input type="hidden" id="version" name="version" value="<?php if ($this->questionnaireRowData) { echo $this->questionnaireRowData['version']; } else { echo '1'; } ?>">
         <div id="msgError" class="notice error hide" style="margin-left: 26px; z-index: 9999">
             <span class="icon small" data-icon="X"></span>
             <b></b><a href="#close" class="icon close" data-icon="x"></a>
         </div>
        
        <fieldset>
            
            <label id="title">Título:</label>
                <input tabindex="1" class="w220 {required:true}" maxlength="100" type="text" id="title" name="title" value="<?php if ($this->questionnaireRowData) { echo $this->questionnaireRowData['title']; } ?>">
            <hr class="clear" />

            <label id="description">Breve Descrição:</label>
                <input tabindex="2" class="w220 {required:true}" maxlength="145" type="text" id="description" name="description" value="<?php if ($this->questionnaireRowData) { echo $this->questionnaireRowData['description']; } ?>">
            <hr class="clear" />

            <label id="long_description">Texto Complementar:</label>
                <textarea tabindex="3" class="w220 {required:true}" id="long_description" name="long_description"><?php if ($this->questionnaireRowData) { echo $this->questionnaireRowData['long_description']; } ?></textarea>

                <hr class="clear" />

            <label for="operation_beginning">Data início do período de execução:</label>
                <input tabindex="4" id="operation_beginning" type="text" name="operation_beginning" value="<?php if ($this->questionnaireRowData['operation_beginning']) { echo Vtx_Util_Date::format_dma($this->questionnaireRowData['operation_beginning']); } ?>" class="w140 datepicker {required:true}" alt="date"  />


            <hr class="clear" />

            <label for="operation_ending">Data final do período de execução:</label>
                <input tabindex="5" id="operation_ending" type="text" name="operation_ending" value="<?php if ($this->questionnaireRowData['operation_ending']) { echo Vtx_Util_Date::format_dma($this->questionnaireRowData['operation_ending']); } ?>" class="w140 datepicker {required:true}" alt="date"  />

            <hr class="clear" />

            <label for="public_subscription_ends_at">Inscrição Pública Termina Em:</label>
            <input tabindex="4" id="public_subscription_ends_at" type="text" name="public_subscription_ends_at" value="<?php if ($this->questionnaireRowData['public_subscription_ends_at']) { echo Vtx_Util_Date::format_dma($this->questionnaireRowData['public_subscription_ends_at']); } ?>" class="w140 datepicker {required:true}" alt="date"  />
            <hr class="clear" />

            <label for="internal_subscription_ends_at">Inscrição Interna Termina Em:</label>
            <input tabindex="4" id="internal_subscription_ends_at" type="text" name="internal_subscription_ends_at" value="<?php if ($this->questionnaireRowData['internal_subscription_ends_at']) { echo Vtx_Util_Date::format_dma($this->questionnaireRowData['internal_subscription_ends_at']); } ?>" class="w140 datepicker {required:true}" alt="date"  />
            <hr class="clear" />
            
            <label for="devolutive_id" class="">Tipo de Devolutiva:</label>
            <select tabindex="6" id="Uf" class="fnc fanc2y" style="width:180px;" name="devolutive_id">
                <?php foreach ($this->getAllDevolutives as $devolutive) : ?>
                    <?php if ($devolutive->getId() == $this->questionnaireRowData['devolutive_id']) : ?>
                        <option value="<?php echo $devolutive->getId();?>" selected="selected"><?php echo $devolutive->getTitle();?></option>
                    <?php else : ?>
                        <option value="<?php echo $devolutive->getId();?>"><?php echo $devolutive->getTitle();?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </fieldset>

        <div class="clear"> </div>
            <button tabindex="7" class="large green" type="submit" style="float: right">
                <span class="icon" data-icon="C"></span> Salvar
            </button>
        <div class="clear"> </div>
	</form>
</div>