<?php
$this->headScript()
    ->prependFile($this->baseUrl('js/validation/lib/jquery.metadata.js'))
    ->prependFile($this->baseUrl('js/validation/jquery.validate.min.js'));

//$this->headLink()->prependStylesheet($this->baseUrl('css/custom-theme/jquery-ui-1.8.23.custom.css'));

include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="pag_role_index">
    <h1 class="center">Questionários</h1>
    <br class="clear" />

    <?php if ($this->questionnaireInsertSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Questionário criado com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>

    <?php if ($this->questionnaireUpdateSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Questionário atualizado com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>

    <?php if ($this->questionnaireDeleteSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Questionário excluído com sucesso.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
    
    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>


    <?php echo $this->paginationControl($this->getAllQuestionnaire); ?>
    <div class="clear"></div>
    <table class="striped tight" border="0" cellpadding="0" cellspacing="0" width="100%">
        <caption></caption>
        <colgroup>
            <col class="firstCol" />
            <col class="" />
            <col class="" />
            <col class="" />
            <col style="width:85px" />
        </colgroup>
        <thead>
            <tr>
                <th rowspan="2" nowrap> Título </th>
                <th rowspan="2" nowrap>Descrição</th>
                <th nowrap colspan="2" style="padding-bottom: 2px">Período de Execução</th>
                <th rowspan="2" nowrap>Inscrição Pública Termina Em</th>
                <th rowspan="2" nowrap>Inscrição Interna Termina Em</th>
                <th class="lastTd" rowspan="2"> Ações </th>
            </tr>
            <tr>
                <th nowrap style="width:85px" class="colspan">Data Início</th>
                <th nowrap style="width:85px" class="colspan">Data Fim</th>
            </tr>
        </thead>
        <tbody>
            
            <?php
            if($this->getAllQuestionnaire) :
                foreach ($this->getAllQuestionnaire as $questionnaire):
            ?>
                <tr>
                    <th><?php echo $questionnaire->getTitle(); ?></th>
                    <td><?php echo $questionnaire->getDescription(); ?></td>
                    <td nowrap style="text-align:center;"><?php echo Vtx_Util_Date::format_dma($questionnaire->getOperationBeginning()); ?></td>
                    <td nowrap style="text-align:center;"><?php echo Vtx_Util_Date::format_dma($questionnaire->getOperationEnding()); ?></td>
                    <td nowrap style="text-align:center;"><?php echo Vtx_Util_Date::format_dma($questionnaire->getPublicSubscriptionEndsAt()); ?></td>
                    <td nowrap style="text-align:center;"><?php echo Vtx_Util_Date::format_dma($questionnaire->getInternalSubscriptionEndsAt()); ?></td>
                    <td class="center">
                        <?php if ($this->loggedAllowed('edit', 'management:questionnaire')): ?>
                            <a href="<?php echo $this->baseUrl('management/questionnaire/edit/id/'.$questionnaire->getId());?>" title="Editar questionário"><span class="ico edit">Editar</span></a>
                        <?php endif; ?> 

                        <?php if ($this->loggedAllowed('delete', 'management:questionnaire')): ?>
                            <a href="<?php echo $this->baseUrl('management/questionnaire/delete/id/'.$questionnaire->getId());?>" title="Excluir questionário" class="delete confirm"><span class="ico delete">Excluir</span></a>
                        <?php endif; ?>
                            
                        <?php //if ($this->loggedAllowed('index', 'management:privilege')): ?>
                            <!--<a href="#<?php //echo $this->baseUrl('management/questionnaire/view/id/'.$questionnaire->getId());?>"><span class="ico view">Visualizar</span></a>-->
                        <?php //endif; ?>
                            
                            
                    </td>
                </tr>
            <?php 
                endforeach; 
            endif;
            ?>
        </tbody>
    </table>
    <div class="clear"></div>
    <?php echo $this->paginationControl($this->getAllQuestionnaire); ?>
    <hr class="clear" />
</div>


