<div style="position: relative">
    <ul class="alternatives clearfix">
         <?php foreach ($this->alternatives as $alternative): ?>
            <li class="alternative clearfix">
                
                <a href="#" class="move moveAlternative" title="Mover" /><span class="ico minimove">Mover</span></a>
                <input type="text" name="alternative[value][]" class="alternativeItem" id="questionAnswer<?php echo $alternative; ?><?php echo $questionFieldN ?>" value="" placeholder="Conteúdo da alternativa" />
                <div class="clear"></div>
                <select title="Ação diferenciada da alternativa" name="alternative[alternative_type_id][]" id="questionTypeAction<?php echo $alternative; ?><?php echo $questionFieldN ?>" class="w95 alternativeType">
                    <option value="1">Sem ação</option>
                    <option value="2">Escrita</option>
                    <option value="3">Tabela</option>
                </select>
                
                <a href="#" title="Título resposta escrita" class="titleAnsWriteLnk hide">[Título introdutório]</a>
                <input type="hidden" name="alternative[dialogue_description][]" value="" class="titleAnsWriteVal hide" />
                
                <input type="hidden" name="annualresult[value][]" value="" class="titleAnnualResultVal hide" />

                
                <select class="mascAnnualResult hide" name="annualresult[mask][]" title="Máscara para os campos da tabela">
                    <option value="moeda" title="Moeda">R$</option>
                    <option value="percentual" title="Percentual">%</option>
                    <option value="numero" title="Número">99</option>
                    <option value="texto" title="Texto">XX</option>
                </select>
                <a href="#" title="Título tabela com resultados" class="titleAnnualResultLnk hide">[Título introdutório]</a>
     
                <label class="peso"> Peso <input type="text" name="alternative[score_level][]" id="ScoreLevel" class="pesoItem alternativeScoreLevel" value=""></label>
                    
                <div class="clear"></div>

              <label class="txDevolutiva"><i>Devolutiva</i>
              <textarea name="alternative[feedback_default][]" title="Feedback Padrão" class="alternativeFeedbackDefault" id="FeedbackDefault<?php echo $alternative;?><?php echo $questionFieldN;?>" placeholder="Texto da devolutiva"></textarea>
              </label>
                <hr>
                <!--<a href="#" class="delete" title="Excluir" /><span data-icon="T" class="icon"></span></a>-->
            </li>
        <?php endforeach; ?>
    </ul>              
    <?php foreach ($this->alternatives as $alternative): ?>
          <div class="opt opt<?php echo $alternative; ?>" for="questionAnswer<?php echo $alternative; ?><?php echo $questionFieldN ?>"><?php echo $alternative; ?>.</div>
    <?php endforeach; ?>
</div>