    <ul class="criterions clearfix">
        <?php
            foreach ((isset($block['criterions'])? $block['criterions'] : array()) as $criterionN => $criterion):
                $criterionFieldN = $blockFieldN . 'cri' . $criterionN;
                $criterionId = isset($criterion['Id'] )? $criterion['Id'] : '';
                $action = (!$systemDefault)?
                    'management/criterion/edit/format/json/id/' . $criterionId : 
                    'management/criterion/insert/format/json';
        ?>
        <?php  // echo '<pre>';  var_dump($criterion['name']);  echo '</pre>'?>
            <li class="criterion hide">

                <form class="clearfix" action="<?php echo $this->baseUrl($action) ?>" method="POST">
                    <input type="hidden" name="designation" value="<?php echo isset($criterion['Designation'])? $criterion['Designation'] : ''; ?>">
                    <input type="hidden" name="conclusion_text" value="">
                    <input type="hidden" name="questionnaire_id" value="<?php echo $this->questionnaireId; ?>">
                    <input type="hidden" name="block_id" value="<?php echo isset($criterion['BlockId'] )? $criterion['BlockId'] : ''; ?>">
                    <input type="hidden" class="itemId" name="item_id" value="<?php echo $criterionId; ?>">
                    <input type="hidden" name="item_type" value="criterion">

                    <a href="#" class="expand" title="Editar" /><span class="ico plus large">+</span></a>
                    <label for="<?php echo $criterionFieldN; ?>">Critério <?php //echo $criterionN ?></label>
                    <input type="text" name="value" id="<?php echo $criterionFieldN; ?>" value="<?php echo $criterion['name']; ?>" class="title impossibleEdit" placeholder="Para bloco sem critério, não informe nada aqui." />
                    <a href="#" class="move moveCriterion" title="Mover" /><span class="ico move large">Mover</span></a>
                    <a href="#" class="delete hide" title="Excluir" /><span data-icon="T" class="icon"></span></a>

                    <fieldset class="adicionalFields clearfix"> 
                        <label for="textarea<?php echo $criterionFieldN; ?>" class="apoio "></label><br class="clear" />
                        <textarea name="long_description" id="textarea<?php echo $criterionFieldN ?>" class="autohide impossibleEdit" data-minheight="90" placeholder="Texto de apoio" style="height: 1px; min-height: 1px; width: 1px;" /><?php echo $criterion['apoio']; ?></textarea>
                        <button class="small green btSave"><span data-icon="C" class="icon"></span>Salvar</button>
                        <button class="small btReset" type="button" title="Cancelar"><span data-icon=":" class="icon"></span></button>

                        <br class="clear" />
                        <div class="notice success hide">
                            <span data-icon="C" class="icon small"></span> <b>Dados salvos com sucesso!</b>
                            <a data-icon="x" class="icon small close" href="#close"></a>
                        </div>

                        <div class="notice error hide">
                            <span data-icon="X" class="icon small"></span> <b></b>
                            <a data-icon="x" class="icon small close" href="#close"></a>
                        </div>
                    </fieldset>
                </form>

                <?php include 'item-questions.phtml'; ?>

            </li> <!-- # li.criterion -->

        <?php endforeach; ?>

    </ul> <!-- # ul.criterions -->

    <a href="#" class="add newCriterion hide"><span class="icon small" data-icon="+"></span> Clique para adicionar um <b>Critério</b></a>
