    <div class="ajuda">
        <h5>Inserir ajuda</h5>
        <button class="small orange addHelper" type="button" data-addHelperType="Video"><span data-icon="2" class="icon"></span>Conteúdo Web Multimídia</button>
        <!--<button class="small orange addHelper" type="button" data-addHelperType="Image"><span data-icon="0" class="icon"></span>Imagem</button>
        <button class="small orange addHelper" type="button" data-addHelperType="Text"><span data-icon="v" class="icon"></span>Texto</button>-->
    </div>

    <ul class="helpers clearfix">

        <li class="alternative helper clearfix helperVideo">
            <a href="#" class="move moveAlternative" title="Mover" /><span class="ico minimove">Mover</span></a>
            <button class="small" type="button"><span data-icon="2" class="icon"></span></button>
            <input type="text" name="helper[helper_value][]" class="helperItem" value="" placeholder="Informe o endereço do vídeo (Youtube)." />
            <input type="hidden" name="helper[helper_type][]" value="video" />
            <a href="#" class="delete" title="Excluir" /><span data-icon="T" class="icon"></span></a>
        </li>

        <li class="alternative helper clearfix helperImage">
            <a href="#" class="move moveAlternative" title="Mover" /><span class="ico minimove">Mover</span></a>
            <button class="small" type="button"><span data-icon="0" class="icon"></span></button>
            <input type="text" name="helper[helper_value][]"  class="helperItem" value="" placeholder="Informe o endereço do imagem." />
            <input type="hidden" name="helper[helper_type][]" value="image" />
            <a href="#" class="delete" title="Excluir" /><span data-icon="T" class="icon"></span></a>
        </li>

        <li class="alternative helper clearfix helperText">
            <a href="#" class="move moveAlternative" title="Mover" /><span class="ico minimove">Mover</span></a>
            <input type="text" name="helper[helper_value][]"  class="helperItem" value="" placeholder="Informe a texto da ajuda.">
            <input type="hidden" name="helper[helper_type][]" value="text" />
            <a href="#" class="delete" title="Excluir" /><span data-icon="T" class="icon"></span></a>
        </li>
    </ul>