<?php
if ($this->userAuth()->getRoleId() == $this->configRegistry()->acl->roleEnterpriseId) {
    // echo '<h1 class="title 22x">Fim das inscrições.</h1>';
    // return;
}


$this->headScript()->captureStart() ?>

<?php
    $this->headScript()->appendFile($this->baseUrl('assets/javascripts/vendor/jquery.fancybox.js?v=2.1.5'));
    $this->headLink()->appendStylesheet($this->baseUrl('assets/stylesheets/vendor/jquery.fancybox.css?v=2.1.5'))
        ->appendStylesheet($this->baseUrl('assets/css/respond.css'));
?>

  <?php
    
    $answered = array();
    $answered_items = array();
    if(isset($this->answeredByUserId) &&  $this->answeredByUserId != null){
    foreach ($this->answeredByUserId as $answer):
      $answered[] = $answer['Id'];
      $answered_items[$answer['Id']] = array(
        'id' => $answer['AlternativeId'],
        'complement' => $answer['AnswerValue']
      );
  ?>
    $('#alternativeItem<?php echo $answer['AlternativeId']; ?>')[0].checked = true;
    <?php if ($answer['AnswerValue'] && (trim($answer['AnswerValue']) != '')): ?>
        if ($('#FdbkQuestion<?php echo $answer['Id']; ?>').length) {
        $('[for="FdbkQuestion<?php echo $answer['Id']; ?>"]').addClass('visible');
        $('#FdbkQuestion<?php echo $answer['Id']; ?>').addClass('visible');
        $('#FdbkQuestion<?php echo $answer['Id']; ?>')[0].value = "<?php echo str_replace(array("\r\n", "\r", "\n"), array('\r\n', '\r', '\n'), $answer['AnswerValue']); ?>";
        }
    <?php
      endif;
    endforeach;
    }
  ?>
  var QUESTION_ANSWERED = [<?php echo implode(', ', $answered); ?>];
  var QUESTION_ANSWERED_ITEMS = {};
  <?php
  if ($answered_items):
    foreach ($answered_items as $answered_items_index => $answered_items_value):
  ?>
  QUESTION_ANSWERED_ITEMS[<?php echo $answered_items_index; ?>] = {
    id: <?php echo $answered_items_value['id']; ?>,
    complement: '<?php echo str_replace(array("\r\n", "\r", "\n"), array('\r\n', '\r', '\n'), $answered_items_value['complement']); ?>'
  };
  <?php
    endforeach;
  endif;
  ?>
  var PAPEL_EMPRESA = <?php echo $this->papelEmpresa; ?>;
  var QUESTION_TYPE_ABCD_ID = <?php echo Model_QuestionType::ABCD_ID; ?>;
  var QUESTION_TYPE_YESNO_ID = <?php echo Model_QuestionType::YESNO_ID; ?>;
  var QUESTION_TYPE_AGREEDISAGREE_ID = <?php echo Model_QuestionType::AGREEDISAGREE_ID; ?>;
  var QUESTION_TYPE_ALWAYS_ID = <?php echo Model_QuestionType::ALWAYS_ID; ?>;
  var ALTERNATIVE_TYPE_TEXT_ID = <?php echo Model_AlternativeType::TEXT_ACTION; ?>;
  var ALTERNATIVE_TYPE_RESULT_ID = <?php echo Model_AlternativeType::RESULT_ACTION; ?>;
  var ENTERPRISE_USER = <?php echo isset($this->user_id) ? $this->user_id : ''; ?>;
  var ENTERPRISE_ID_KEY = <?php echo isset($this->enterpriseIdKey) ? '"'.$this->enterpriseIdKey.'"' : ''; ?>;
  var QSTN_ID = <?php echo isset($this->qstnRespondId) ? $this->qstnRespondId : ''; ?>;
  var PERMISSION_EVALUATION_OF_RESPONSE = <?php echo $this->permissionEvaluationOfResponse? 1 : 0 ?>;
  var SPEEDY_TRANSITION = <?PHP echo (Zend_Auth::getInstance()->getIdentity()->getRoleId()==Zend_Registry::get('config')->acl->roleDigitadorId)? 0 : 450; ?>;
  var startDate = "<?php echo date('H:i:s'); ?>";
  var PROGRAMA_ID = <?php echo isset($this->programaId) ? $this->programaId : Zend_Registry::get('configDb')->competitionId; ?>;
  var CURRENT_BLOCK_ID = <?php echo isset($this->blockId) ? $this->blockId : Zend_Registry::get('configDb')->qstn->currentBlockIdNegocios; ?>;
  
<?php $this->headScript()->captureEnd() ?>
<?php
$this->headScript()
  ->appendFile($this->baseUrl('js/questionnarie/respondPSMN.js?v=66'))
//  ->prependFile($this->baseUrl('js/validation/lib/jquery.form.js'));
?>

<div id="content">
<?php
if ($this->request()->getParam('module') == 'management') {
    include APPLICATION_PATH . '/modules/management/views/scripts/menus/admin_menu.phtml';
}
?>
  <?php
    foreach ($this->blockQuestions as $questionId => $question){
      $questionType = $question['QuestionTypeId'];
      break;
    }
  ?>

  <?php include ($questionType == 5 ? 'questionnaire-5.php' : 'questionnaire-6.php' ); ?>


  <div id="textoQuestao">
    <?php if ($this->messageError): ?>
      <div class="notice error">
        <span data-icon="X" class="icon medium"></span>
        <b><?php echo $this->messageError; ?></b>
        <a data-icon="x" class="icon close" href="#close"></a>
      </div>
    <?php endif; ?>
  </div>

</div>