<?php 
if ($this->userAuth()->getRoleId() == $this->configRegistry()->acl->roleEnterpriseId) {
    // echo '<h1 class="title 22x">Fim das inscrições.</h1>';
    // return;
}
$this->headScript()->captureStart() ?>
  var QSTN_ID = <?php echo $this->questionnaireId; ?>;
  <?php // var ENTERPRISE_USER = <?php echo $this->enterpriseUserId; ? >; ?>
  var ENTERPRISE_ID_KEY = '<?php echo $this->enterpriseIdKey; ?>';
  var ADMIN_MENU = <?php echo $this->request()->getParam('menu-admin', 0); ?>;
<?php $this->headScript()->captureEnd() ?>
<?php
$this->headScript()->appendFile($this->baseUrl('js/questionnarie/devolutive.js?xx2'))
?>
<?php
if ($this->request()->getParam('module') == 'management' or  $this->request()->getParam('menu-admin')) {
    include APPLICATION_PATH . '/modules/management/views/scripts/menus/admin_menu.phtml';
}
?>

<h2 id="tituloDevolutiva">Obtendo devolutiva, aguarde...</h2>
<h3 id="msgDownloadDevolutiva"></h3>

<br/>

<?php if(!$this->subscriptionConfirmationCheck()): ?>
    <div class="alert alert-error">Favor confirmar sua inscrição no link que foi enviado para o e-mail informado. Caso tenha informado não possuir e-mail, aguarde o contato da coordenação do prêmio.</div>
<?php endif ?>
