<h1 class="title">Relato</h1>

<?php if (isset($this->itemEditSuccess)):?>
    <?php if ($this->itemEditSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Relato editado com sucesso. 
                    <a href="<?php echo $this->baseUrl('/questionnaire/respond/index/geraDevolutiva/1') ?>">Clique aqui para gerar a devolutiva.</a>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($this->itemInsertSuccess)):?>
    <?php if ($this->itemInsertSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Relato cadastrado com sucesso.
                     <a href="<?php echo $this->baseUrl('/questionnaire/respond/index/geraDevolutiva/1') ?>">Clique aqui para gerar a devolutiva.</a>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>


    <?php endif; ?> 
<?php endif; ?>
        <button tabindex="48" class="large btn-submit" type="button"
                style="float: right; margin-bottom: 20px"
                onclick="window.location=BASE_URL+'/questionnaire/respond/index/geraDevolutiva/1';">
            <span class="icon" data-icon="C"></span> Continuar
        </button>
<!--<a title="Voltar" id="back" class="btn-back btn-submit" href="<?php echo ($this->request()->getParam('module') == 'management')? $this->baseUrl('management/enterpris') : $this->baseUrl('questionnaire/'); ?>"><span class="icon" data-icon=""></span> Voltar</a>-->