<?php
$this->headScript()
    ->appendFile($this->baseUrl('js/management/configuration.js'));

include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div class="pageEditRegional" id="content">
    <h1 class="center">
        Configurações
    </h1>

<?php if (isset($this->itemSuccess)):?>
    <?php if ($this->itemSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span> Configuração alterada com sucesso.
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
</div>
    <?php return; endif; ?>
<?php endif; ?>

<?php if (isset($this->messageError)):?>
    <?php if ($this->messageError):?>
        <div class="notice error">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
    <form id="frmConfiguration" action="<?php echo $this->baseUrl('management/configuration/index'); ?>" method="POST" class="normal" autocomplete="on">
         <fieldset>
             
            <label for="competition">Concurso corrente:</label>
            <select name="competition_id" id="competition" class="fnc" style="width:280px;">
                <option value="">Escolha um Concurso</option>
                <?php if (isset($this->getAllCompetition)) : ?>
                    <?php foreach ($this->getAllCompetition as $competition) : ?>
                        <?php if (isset($this->allConfig->competitionId) && $this->allConfig->competitionId == $competition->getId()) : ?>
                            <option value="<?php echo $competition->getId();?>" selected="selected"><?php echo $competition->getDescription();?></option>
                        <?php else : ?>
                            <option value="<?php echo $competition->getId();?>"><?php echo $competition->getDescription();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
             <hr class="clear" />
            <label for="description">Questionário corrente:</label>
                <select name="autoavaliacao_value" id="autoavaliacaoId" class="fnc" style="width:280px;">
                    <?php foreach ($this->getAutoavaliacaoQuestionnaires as $key => $value) : ?>
                        <?php if (isset($this->allConfig->qstn->currentAutoavaliacaoId) && 
                                $this->allConfig->qstn->currentAutoavaliacaoId == $value->getId()) : ?>
                            <option value="<?php echo $value->getId();?>" selected="selected"><?php echo $value->getTitle().' - '.$value->getDescription();?></option>
                        <?php else : ?>
                            <option value="<?php echo $value->getId();?>"><?php echo $value->getTitle().' - '.$value->getDescription();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
                <input type='hidden' name='autoavaliacao_key' id='autoavaliacao_key' value='qstn.currentAutoavaliacaoId'>
            <hr class="clear" />
            
            <?php /* ?>
        	<label for="blockGovAutoavaliacao">Bloco de questões de Empreendedorismo:</label>
                <select name="block_empreendedorismo_value" id="blockScoreGovAutoavaliacao" class="fnc" style="width:280px;">
                    <option value="">Escolha um Questionário de Autoavaliação</option>
                    <?php if (isset($this->getAllBlockByAutoavaliacao)) : ?>
                        <?php foreach ($this->getAllBlockByAutoavaliacao as $block) : ?>
                            <?php if (isset($this->allConfig->qstn->currentBlockIdEmpreendedorismo) && 
                                    $this->allConfig->qstn->currentBlockIdEmpreendedorismo == $block->getId()) : ?>
                                <option value="<?php echo $block->getId();?>" selected="selected"><?php echo $block->getValue();?></option>
                            <?php else : ?>
                                <option value="<?php echo $block->getId();?>"><?php echo $block->getValue();?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
                <input type='hidden' name='current_block_empreendedorismo_id_key' id='currentBlockIdEmpreendedorismoKey' value='qstn.currentBlockIdEmpreendedorismo'>
            <hr class="clear" />
            <?php */ ?>
            
            <label for="blockRadarAutoavaliacao">Bloco de questões de Negócios:</label>
                <select name="block_negocios_value" id="blockScoreRadarAutoavaliacao" class="fnc" style="width:280px;">
                    <option value="">Escolha um Questionário de Autoavaliação</option>
                    <?php if (isset($this->getAllBlockByAutoavaliacao)) : ?>
                        <?php foreach ($this->getAllBlockByAutoavaliacao as $block) : ?>
                            <?php if (isset($this->allConfig->qstn->currentBlockIdNegocios) && 
                                    $this->allConfig->qstn->currentBlockIdNegocios == $block->getId()) : ?>
                                <option value="<?php echo $block->getId();?>" selected="selected"><?php echo $block->getValue();?></option>
                            <?php else : ?>
                                <option value="<?php echo $block->getId();?>"><?php echo $block->getValue();?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            <input type='hidden' name='current_block_negocios_id_key' id='currentBlockIdNegociosKey' value='qstn.currentBlockIdNegocios'>
            <hr class="clear" />
            <hr class="clear" />
            
            
            <label for="description">Endereço de E-mail para recebimento via contato:</label>
                <input name="secoop_contact_value" id="secoop_contact_value" class="fancy" style="width:280px;" value="<?php echo $this->allConfig->addr->sescoopContactEmail; ?>">
                <input type='hidden' name='secoop_contact_key' id='secoop_contact_key' value="addr.sescoopContactEmail">
            <hr class="clear">
            
            <label for="description">Endereço de E-mail do Gestor (inelegibilidade no cadastro):</label>
                <input name="eligibility gestor_value" id="eligibility_gestor_value" class="fancy" style="width:280px;" value="<?php echo $this->allConfig->addr->eligibilityGestorEmail; ?>">
                <input type='hidden' name='eligibility_gestor_key' id='eligibility_gestor_key' value="addr.eligibilityGestorEmail">
            <hr class="clear">
            
            

            <input type='hidden' name='competition_id_key' id='competitionIdKey' value='competitionIdKey'>
            <hr class="clear" />
            <hr class="clear" />
            
            
            
            
            
            
            
            <button class="large green" type="submit" style="float: right" tabindex="9">
                <span class="icon" data-icon="C"></span> Salvar
            </button>
        </fieldset> 
    </form>
</div>


