<?php
$this->headScript()
    ->appendFile($this->baseUrl('js/address/capital.js'))
    ->appendFile($this->baseUrl('js/lost-login.js?v1'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.metadata.js'))
    ->prependFile($this->baseUrl('js/validation/jquery.validate.min.js'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.form322.min.js'));

?>
<?php // include 'menu.phtml'; ?>
<div id="content" class="forgot-pass">
    <h1 class="center">Esqueci minha senha</h1>

    <?php if ($this->itemSucess): ?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo 'Nova senha enviada para o email cadastrado.'; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>    

    <form method="POST" class="normal frm" autocomplete="off"
          action="<?php echo $this->baseUrl('login/lost/format/json'); ?>"  id="frmLost">
         <div id="msgError" class="notice error autoScroll" style="margin-left: 26px; z-index: 9999" data-name-scroll="msgError">
             <span class="icon small" data-icon="X"></span>
             <b></b><a href="#close" class="icon close" data-icon="x"></a>
         </div>

		<fieldset>
            <label for="Cnpj">Informe o login cadastrado*:</label>
                <input tabindex="1" id="Cpf" type="text" name="user[login]" size="18" 
                       class="w140 {required:true}" /> 

            <label for="PasswordHint" class="w200">Dica de senha:
            </label>
            <div>
                <button tabindex="2" id="bt-PasswordHint" class="large green" type="button"> solicitar dica de senha </button>
            </div>
                <input tabindex="3" disabled="disabled" id="PasswordHint" type="text" class="w300" style="display: none;" />
                
            <label for="EmailDefault" class="w200">E-mail cadastrado*:</label>
                <input tabindex="4" id="EmailDefault" type="text" size="120" maxlength="120" 
                    name="user[email]"
                    class="w300 {required:true, email:true, messages:{email:'Entre com endereço de e-mail válido.'}}"
                />
                
                
            <div>
            <button tabindex="3" id="bt-reset-pass" class="large green" type="submit"> Enviar </button>
            </div>
        </fieldset>

            <div>
                <label style=" width: 327px;"><span>(*) Campos com preenchimento obrigatório..</span></label>
            </div>
    </form>
    
    
</div>
