<?php
$includeFile = 'lista-empresas-verificador.phtml';
$permissionRespondAll = (
    $this->loggedAllowed('index', 'questionnaire:respond')
    and $this->loggedAllowed('answer', 'questionnaire:respond')
    and $this->loggedAllowed('not-coop-responding', 'management:questionnaire')
    );
if ($this->retorno)
{ 
	?><div class="alert alert-error">Favor responder na ordem dos questionários: Gestão, Relato e PF/OM</div><?php
	$this->retorno = false;
}
?>
<main>
    <div id="main" class="listagem-empresa"  style="margin-top:20px">
        <section class="section-full-page">
        <div class="box-content form-tab">
                <?php if($this->getAllEnterpriseNacional) : ?>
                    <div class="table-menu header">
                        <?php
                        $total = count($this->getAllEnterpriseNacional);
                        $label_total = (($total > 0) ? implode(' ', array(
                          $total, implode('', array('empresa', (($total > 1) ? 's' : '')))
                        )) : 'Nenhuma empresa listada para verificação no momento.');
                        ?> 
                        <hgroup>
                            <a name="lista"></a><h2>Avaliação Etapa Nacional - <span><?php echo $label_total; ?></span></h2>
                        </hgroup>
                    </div>
                    <div class="table-container">
                        <?php include 'lista-empresas-verificador-nacional.phtml'; ?>
                    </div>
                <?php endif; ?>
    
               <?php if($this->getAllEnterprise) : ?>
                    <div class="table-menu header">
                        <?php
                        $total = count($this->getAllEnterprise);
                        $label_total = (($total > 0) ? implode(' ', array(
                          $total, implode('', array('empresa', (($total > 1) ? 's' : '')))
                        )) : 'Nenhuma empresa listada para verificação no momento.');
                        ?> 
                        <hgroup>
                            
                            <a name="lista"></a><h2>Verificação Etapa Estadual - <span><?php echo $label_total; ?></span></h2>
                        </hgroup>
                    </div>
                    <div class="table-container">
                        <?php include $includeFile; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="clear"></div>
        </section>
    </div>
    <div id="areaIframe"></div>
</main>
