<?php 
$this->headScript()
    ->appendFile($this->baseUrl('js/address/capital.js'))
    ->appendFile($this->baseUrl('js/management/appraiser/edit.js'));

include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
$appraiserId = $this->appraiserRow->getId();
?>
<div class="pageEditRegional" id="content">
    <h1 class="center">
        Associação de empresas ao avaliador
    </h1>
    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/appraiser'); ?>">Voltar</a>
<?php if (isset($this->itemEditSuccess)):?>
    <?php if ($this->itemEditSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span> Avaliador alterado com sucesso.
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($this->itemInsertSuccess)):?>
    <?php if ($this->itemInsertSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Avaliador relacionado com sucesso.
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
    
<?php if (isset($this->messageError)):?>
    <?php if ($this->messageError):?>
        <div class="notice error">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>


    
    <form id="frm" action="<?php echo $this->baseUrl('management/appraiser/edit/id/'.$appraiserId.'/page/'.$this->page.'/format/html');?>" method="GET" autocomplete="on">
    <fieldset>
        <label for="description">Avaliador:</label>
        <input type="hidden" value="<?php echo $appraiserId; ?>" name="appraiser_id" id="AppraiserId"  />

        <input tabindex="1" type="text" readonly="readonly" disabled name="first_name" id="appraiserName" class="{required:true}"
            value="<?php echo $this->appraiserRow->getFirstName() . ' ' . $this->appraiserRow->getSurname();?>" style="font-weight: bold">
        
        <select class="sortBy hide">
            <option value="">Empresa &nbsp;</option>
            <option value=""<?php echo $this->orderBy == 'FinalScore DESC'? ' selected' : ''; ?>>Avaliador &nbsp;</option>
        </select>
        
        <label>Regional:</label>
        <select name="filter[regional_id]" class="fnc">
            <option value="">Todas</option>
            <?php foreach ($this->getAllRegional as $regional) :?>
                <?php if ( $regional->getId() == $this->filter['regional_id'] ) :?>
                    <option value="<?php echo $regional->getId();?>" selected="selected"><?php echo $regional->getDescription();?></option>
                <?php else : ?>
                    <option value="<?php echo $regional->getId();?>"><?php echo $regional->getDescription();?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>


        <hr class="clear" />

        <label for="Cnpj">Empresa:</label>
        <input tabindex="1" id="coopName" type="text" name="filter[coop_name]" size="18" value="<?php echo isset($this->filter['coop_name'])? $this->filter['coop_name'] : ''; ?>"  />
            <label for="Cnpj">CNPJ:</label>
            <input tabindex="1" id="cnpj" type="text" name="filter[cnpj]" size="18" value="<?php echo isset($this->filter['cnpj'])? $this->filter['cnpj'] : ''; ?>" style="padding-right: 0px; " />
        <hr class="clear" />
        <label for="showOnly" class="fnc select">Mostrar:</label>
        <select tabindex="10" id="showOnly" class="fnc" name="filter[show_only]">
            <option value="">Todas</option>
            <option value="appraiserIsNull" <?php echo (isset($this->filter['show_only']) && $this->filter['show_only'] == 'appraiserIsNull')? 'selected' : '';?>>Coops. sem avaliador</option>
        </select>
            <label for="Uf" class="select">UF:</label>
            <select data-placeholder="" tabindex="10" id="Uf" class="fnc" name="filter[state_id]">
                <option value="">Todos</option>
                <?php foreach ($this->getAllStates as $states) : ?>
                    <?php if (isset($this->filter['state_id']) && $states->getId() == $this->filter['state_id']) : ?>
                        <option value="<?php echo $states->getId();?>" selected><?php echo $states->getUf();?></option>
                    <?php else : ?>
                        <option value="<?php echo $states->getId();?>"><?php echo $states->getUf();?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
             <hr class="clear" />
            <label for="city" class="select">Cidade:</label>
            <select tabindex="10" id="CityId" class="fnc" name="filter[city_id]">
                <option value="">Todas</option>
                <?php if (isset($this->getAllCities)) : ?>
                    <?php foreach ($this->getAllCities as $cities) : ?>
                        <?php if ($cities->getId() == $this->filter['city_id']) : ?>
                            <option value="<?php echo $cities->getId();?>" selected="selected"><?php echo $cities->getName();?></option>
                        <?php else : ?>
                            <option value="<?php echo $cities->getId();?>"><?php echo $cities->getName();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <label for="Neighborhood" class="select">Bairro:</label>
            <select tabindex="10" id="NeighborhoodId" class="fnc" name="filter[neighborhood_id]">
                <option value="">Todos</option>
                <?php if (isset($this->getAllNeighborhoods)) : ?>
                    <?php foreach ($this->getAllNeighborhoods as $neighborhood) : ?>
                        <?php if ($neighborhood->getId() == $this->filter['neighborhood_id']) : ?>
                            <option value="<?php echo $neighborhood->getId();?>" selected="selected"><?php echo $neighborhood->getName();?></option>
                        <?php else : ?>
                            <option value="<?php echo $neighborhood->getId();?>"><?php echo $neighborhood->getName();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <hr class="clear" />
            <label for="Status" class="">Status:</label>
            <select tabindex="4" name="filter[status]" class="fnc" id="Status">
                <?php foreach (Vtx_Util_Array::status() as $key => $status) :?>
                    <?php if ( $key == $this->filter['status'] ) :?>
                        <option value="<?php echo $key;?>" selected="selected"><?php echo $status;?></option>
                    <?php else : ?>
                        <option value="<?php echo $key;?>"><?php echo $status;?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        <button tabindex="16" style="float: right" type="submit" class="green small">
            <span class="icon small" style="left: 3px; top: -2px;" data-icon="s"></span>
        </button>
    </fieldset>
    <?php

    ?>
        
    </form>
    
    <div id="msgError" class="notice error autoScroll hide" style="margin-left: 26px; z-index: 9999">
        <span class="icon small" data-icon="X"></span>
        <b></b><a href="#close" class="icon close" data-icon="x"></a>
    </div>

    <?php echo $this->paginationControl($this->getAllEnterpriseByRegionalServiceArea, null, null); ?>

    <div class="clear"></div>

    <table id="tbCoops" class="striped tight" border="0" cellpadding="0" cellspacing="0">
        <caption></caption>
        <colgroup>
            <col style="width: 300px;" />
            <col style="width: " />
            <col style="width: 220px" />
        </colgroup>
        <thead>
            <tr>
                <th>Empresa</th>
                <th >UF</th>
                <th > Relacionar </th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($this->getAllEnterpriseByRegionalServiceArea) >= 1) : ?>
                <?php
                    foreach ($this->getAllEnterpriseByRegionalServiceArea as $enterprise):
                ?>
                <tr>
                    <th style="text-align: left; padding-bottom: 2px; padding-top: 3px" title="<?php echo $enterprise->getFantasyName() . ' CNPJ: ' . $enterprise->getFormattedCnpj() ?>"> <?php /*echo $enterprise->getId();*/ echo substr($enterprise->getSocialName(), 0, 60) ; ?>
                        <br>
                        <span style="margin-left: 3px; margin-bottom: -2px;font-size: 0.9em; color: #909090">
                            <a href="mailto:<?php echo $enterprise->getEmailDefault(); ?>" title="<?php echo $enterprise->getEmailDefault(); ?>"><span class="icon small gray" data-icon="@"></span></a>
                            <span class="icon small gray" data-icon="8"></span>
                            <?php echo $enterprise->getPhone();  ?>
                            <?php echo $enterprise->getCityName(); ?>
                        </span>
                    </th>
                    <td title="<?php echo $enterprise->getCityName(); ?> - <?php echo $enterprise->getNeighName(); ?>"> <?php echo $enterprise->getUf(); ?></td>
                    <td>
                        <label style="text-align: left; font-size: 1em; width: 100%;">
                            <?php
                                 if ($enterprise->getAppraiserId() == NULL) {
                                      if ($this->loggedAllowed('set-appraiser-to-enterprise')) {
                                         echo '<input data-enterprise-id="' . $enterprise->getId() . '" name="allowAppraiser[enterprise_id]['.$enterprise->getId().']" value="0" type="checkbox" class="checkbox" title="Selecionar empresa para o avaliador" /><span style="font-size: 1em;color:#505050"></span>';
                                     }
                                 } else {
                                     if ($enterprise->getAppraiserId() == $appraiserId) {
                                         if ($this->loggedAllowed('set-appraiser-to-enterprise')) {
                                             echo ' <input data-enterprise-id="' . $enterprise->getId() . '" name="allowAppraiser[enterprise_id]['.$enterprise->getId().']" value="1" checked="checked" title="Tirar seleção da empresa para o avaliador" type="checkbox" class="checkbox"/>';
                                         }
                                     } else {
                                         echo ' <input type="checkbox" class="checkbox" checked disabled> ';
                                     }
                                     echo '<span style="font-size: 1em; color:#505050"> ' . $enterprise->getFirstName() . ' ' . $enterprise->getSurname() . '</span>';
                                 }
                             ?>
                        </label>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr>
                    <td width="220" colspan="7">Não há empresas cadastradas para este avaliador.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="clear"></div>
    <?php echo $this->paginationControl($this->getAllEnterpriseByRegionalServiceArea, null, null); ?>

    <div class="clear"> </div>
    <hr class="clear" />

</div>
