<form action="" id="" method="POST" class="avaliacao">
  <fieldset style="border-bottom: 2px solid #CCCCCC">
    <input type="hidden" id="" name="" value="" />
  </fieldset>
  <fieldset>
    <div class="list-table-20">
      <label class="label-control">CNPJ</label>
      <span class="label-value"><?php echo $this->enterprise->getFormattedCnpj(); ?></span>
    </div>

    <div class="list-table-20">
      <label class="label-control">Candidata</label>
      <span class="label-value"><?php echo $this->president->getName(); ?></span>
    </div>
    <div class="list-table-20">
      <label class="label-control">Estado</label>
      <span class="label-value"><?php echo $enterpriseState->getUf(); ?></span>
    </div>

    <div class="list-table-20">
      <label class="label-control">Empresa</label>
      <span class="label-value"><?php echo $this->enterprise->getFantasyName(); ?></span>
    </div>
  </fieldset>
<?php $score = $this->scores; ?>
<fieldset style="width: 100%;">
    

    <div class="list-table-20">
      <label class="label-control">Categoria</label>
      <span class="label-value"><?php if ($this->enterprise->getCategoryAwardId()) echo Vtx_Util_Array::categoriaPsmn($this->enterprise->getCategoryAwardId()) ?></span>
    </div>
    
           <div class="list-table-20">
             <label class="label-control"><?php  echo $this->fase == null ? "Pontos Primeira Fase" : "Pontos Segunda Fase";?></label>
             <span class="label-value">
                <?php
                    if ($score->getPontosGeral() != '-') {
                      $NegocioTotal =  number_format($score->getNegociosTotal()*1, 1, '.', ',');                      
                      $MediaTotal =  number_format($score->getMediaPontos(), 1 , '.', ',');
                      echo number_format(($NegocioTotal + $MediaTotal)/2, 1 , ',', '.');
                    }
                ?>
             </span>
           </div>

           <div class="list-table-20">
             <label class="label-control">Pontos Negócios</label>
             <span class="label-value">
                <?php
                  echo number_format($score->getNegociosTotal()*1, 1 , ',', '.');
                  ?>
             </span>
           </div>

           <div class="list-table-20" style="">
             <label class="label-control">Média Relato

             </label>
             <span class="label-value">
                <?php echo number_format($score->getMediaPontos(), 1 , ',', '.');?>

             </span>
           </div>   
    

</fieldset>

<fieldset style="width: 100%;">
    <ul class="devolver" style="width: 100%; float:left;  margin: 0; margin: 4px; margin-bottom: 0px">
    <?php $avaliador = $score->getFirstNameAvaliadorPri(); if ($avaliador): ?>
       <li style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
           <div class="list-table-20">
             <label class="label-control"><?php  echo $this->fase == null ? "Avaliador Estadual" : "Avaliador Nacional";?></label>
             <span class="label-value"><?php echo $avaliador; ?> <b style="font-size: 10px">(<?php echo $score->getLoginAvaliadorPri(); ?>)</b></span>
           </div>

           <div class="list-table-20">
             <label class="label-control">Pontos</label>
             <span class="label-value">
               <?php if ($score->getAppraiserStatus() == 'C'): ?>
                   <?php echo number_format($score->getPontos(), 1 , ',', '.'); ?> pts. </label>
               <?php elseif ($score->getAppraiserStatus() == 'I'): ?>
                 Iniciado
               <?php elseif ($score->getAppraiserStatus() == 'N'): ?>
                 <Strong>Não iniciado</Strong>
               <?php endif; ?>
             </span>
           </div>

           <div class="list-table-20" style="margin-bottom: 16px;
            margin-right: 5px;
            width: 427px;margin-right: 5px; width: 427px;">
             <label class="label-control">Observação</label>
             <span class="label-value">
                 <?php echo ($score->getConclusaoDate())? ("(".$score->getConclusaoDate() . ")") : ''; ?>
               <?php echo $this->escape($score->getConclusao()); ?>
             </span>
           </div>
       </li>
   <?php endif; ?>


    <?php $avaliador = $score->getFirstNameAvaliadorSec(); if ($avaliador): ?>
       <li style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 20px">
           <div class="list-table-20">
             <span class="label-value"><?php echo $avaliador; ?> <b style="font-size: 10px">(<?php echo $score->getLoginAvaliadorSec(); ?>)</b></span>
           </div>

           <div class="list-table-20">
             <span class="label-value">
               <?php if ($score->getAppraiserStatusSec() == 'C'): ?>
                   <?php echo number_format($score->getPontosSec(), 1 , ',', '.'); ?> pts. </label>
               <?php elseif ($score->getAppraiserStatusSec() == 'I'): ?>
                 Iniciado
               <?php elseif ($score->getAppraiserStatusSec() == 'N'): ?>
                 <Strong>Não iniciado</Strong>
               <?php endif; ?>
             </span>
           </div>

           <div class="list-table-20" style="margin-bottom: 16px; margin-right: 5px; width: 427px; margin-right: 5px; width: 427px;">

               
             <span class="label-value">
                <?php echo ($score->getConclusaoDateSec())? ("(".$score->getConclusaoDateSec() . ")") : ''; ?>

               <?php echo $this->escape($score->getConclusaoSec()); ?>
             </span>
           </div>
       </li>
   <?php endif; ?>
       
    <?php $avaliador = $score->getFirstNameAvaliadorTer(); if ($avaliador): ?>
       <li style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 20px">
           <div class="list-table-20">
             <span class="label-value"><?php echo $avaliador; ?> <b style="font-size: 10px">(<?php echo $score->getLoginAvaliadorTer(); ?>)</b></span>
           </div>

           <div class="list-table-20">
             <span class="label-value">
               <?php if ($score->getAppraiserStatusTer() == 'C'): ?>
                   <?php echo number_format($score->getPontosTer(), 1 , ',', '.'); ?> pts. </label>
               <?php elseif ($score->getAppraiserStatusTer() == 'I'): ?>
                 Iniciado
               <?php elseif ($score->getAppraiserStatusTer() == 'N'): ?>
                 <Strong>Não iniciado</Strong>
               <?php endif; ?>
             </span>
           </div>

           <div class="list-table-20" style="margin-bottom: 16px; margin-right: 5px; width: 427px; margin-right: 5px; width: 427px;">

               
             <span class="label-value">
                <?php echo ($score->getConclusaoDateTer())? ("(".$score->getConclusaoDateTer() . ")") : ''; ?>

               <?php echo $this->escape($score->getConclusaoTer()); ?>
             </span>
           </div>
       </li>
   <?php endif; ?>

    </ul>

  </fieldset>
    
    <!--fieldset style="width: 100%;">

        <div class="list-table-20">
          <label class="label-control">Verificador Estadual</label>
          <span class="label-value">
              <?php if ($this->enterprise->getCategoryAwardId()) echo Vtx_Util_Array::categoriaPsmn($this->enterprise->getCategoryAwardId()) ?>
          </span>
        </div>

        <div class="list-table-20">
          <label class="label-control">Pontos Geral</label>
          <span class="label-value">
             <?php
                 if ($score->getPontosGeral() != '-') {
                     echo number_format($score->getPontosGeral()*100/2, 1 , ',', '.');
                 }
             ?>
          </span>
        </div>

        <div class="list-table-20">
          <label class="label-control">Pontos Negócios</label>
          <span class="label-value">
             <?php
               echo number_format($score->getNegociosTotal()*10, 1 , ',', '.');
               ?>
          </span>
        </div>

        <div class="list-table-20" style="">
          <label class="label-control">Média Relato

          </label>
          <span class="label-value">
             <?php echo number_format($score->getMediaPontos(), 1 , ',', '.');?>

          </span>
        </div>

</fieldset-->