<?php

$fase = $this->fase;

$addressEnterprise = $this->enterprise->findAddressEnterprise()->current();
$enterpriseState = $addressEnterprise->findParentState();

 $executionPontuacaoManager = new Manager_ExecutionPontuacao();
 $Appraiser = new Model_Appraiser; 
 $enterpriseId = new Model_Enterprise();
 $enterpriseUserid = $enterpriseId->getUserIdByIdKey($this->enterprise->getIdKey());
 
 $checkerId = (isset($this->scores) and $this->scores->getCheckerId() != null) ? $this->scores->getCheckerId() : null;
 $final = ($fase == 2) ? 8 : null;
try {
	$NotaAutoAvalVerificador  = $executionPontuacaoManager->calculateExecutionScore(52,$enterpriseUserid,true,$checkerId);
    //$NotaAutoAvalVerificador  = $executionPontuacaoManager->calculateExecutionScore(52,$enterpriseUserid,true);
} catch (InvalidArgumentException $e) {
    $NotaAutoAvalVerificador = 0;
}

try {
$scoreVisita =$Appraiser->getEnterpriseScoreAppraiserAnwserVerificadorData($this->enterprise->getId(),$checkerId, null, $final);

} catch (InvalidArgumentException $e) {
	$scoreVisita = 0;
}

if($scoreVisita->count() > 0)
  	$NotaQuestVisitaVerificador =  $scoreVisita[0]->getPontosFinal();
else
  	$NotaQuestVisitaVerificador = 0;

try {
$QtdPontosFortes = $this->scores->getQtdePontosFortes();
 
 } catch (InvalidArgumentException $e) {
	$QtdPontosFortes = 0;
}

  if($QtdPontosFortes == 12)  $QtdPontosFortes = 20; 
  if($QtdPontosFortes == 11)  $QtdPontosFortes = 19;
  if($QtdPontosFortes == 10)  $QtdPontosFortes = 18;
  if($QtdPontosFortes == 9)   $QtdPontosFortes = 17;
  if($QtdPontosFortes == 8)   $QtdPontosFortes = 16;
  if($QtdPontosFortes == 7)   $QtdPontosFortes = 14;
  if($QtdPontosFortes == 6)   $QtdPontosFortes = 12;
  if($QtdPontosFortes == 5)   $QtdPontosFortes = 10;
  if($QtdPontosFortes == 4)   $QtdPontosFortes = 8;
  if($QtdPontosFortes == 3)   $QtdPontosFortes = 6;
  if($QtdPontosFortes == 2)   $QtdPontosFortes = 4;
  if($QtdPontosFortes == 1)   $QtdPontosFortes = 2;
  if($QtdPontosFortes == 0)   $QtdPontosFortes = 0;
  
  $PontuacaoFinal =  (($NotaAutoAvalVerificador * 0.2) + ($NotaQuestVisitaVerificador * 0.6) + $QtdPontosFortes);  

$blocoAnterior = ''; 
$criterioAnterior = '';
$qsts = array();
$blocos = array();
$criterios = array();
//Questoes
foreach ($this->questoes as $k => $questao):
    $bloco = $questao->getBloco();
    $criterio = $questao->getCriterio();
    if ($bloco != $blocoAnterior) {
        $qsts[$bloco] = array(
            'BlockName' => Vtx_Util_PsmnAvaliacao::BlocosAvaliacao($bloco), 'Criterions' => array()
        );
    }
    if ($criterio != $criterioAnterior) {
        $qsts[$bloco]['Criterions'][$criterio] = array(
            'CriterionValue' => Vtx_Util_PsmnAvaliacao::CriteriosAvaliacao($bloco, $criterio),
            'Questions' => array()
        );
    }
    $qsts[$bloco]['Criterions'][$criterio]['Questions'][$questao->getId()] = $questao;
    $blocoAnterior = $bloco;
    $criterioAnterior = $criterio;
endforeach;
 
function comentario($array,$value) {
   $filtered = false;
   $member = "CriterioNumber";

   foreach($array as $v) {

      if($v["CriterioNumber"] == $value)
         $filtered = $v["Comment"];
   }

    return $filtered;
}


?>
 
 <style>
 p{
	 word-wrap: break-word!important;
	   width: 722px!important;
 }
 </style>
<a title="Imprimir" style="margin-right: 16px; position: absolute; right: 0" href="#" id="verRelato" onclick="window.print(); return false;"><span>Imprimir</span></a>

<br>

<h1 class="title"><a name="report"></a>Relatório da Candidata</h1>

<?php 
include realpath(dirname(__FILE__) . '/../appraiser/enterprise-scores.phtml');
?>


<fieldset style="width: 100%;">
    <ul class="devolver" style="width: 100%; float:left;  margin: 0; margin: 4px; margin-bottom: 0px">
    <?php $verificador = $score->getFirstNameChecker(); if ($verificador): ?>
       <li style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
           <div class="list-table-20">
             <label class="label-control"><?php  echo $this->fase == null ? "Verificador Estadual" : "Verificador Nacional";?></label>
             <span class="label-value"><?php echo $verificador; ?> <b style="font-size: 10px">(<?php echo $score->getLoginChecker(); ?>)</b></span>
           </div>

           <div class="list-table-20" style="width:130px">
             <label class="label-control">Pontuação Geral</label>
             <span class="label-value">
                 
             <?php            
             echo number_format($PontuacaoFinal, 1 , ',', '.');            
          ?>  

             </span>
           </div>
           
            <div class="list-table-20" style="width:130px">
             <label class="label-control">Questionário<br/>de Auto Aval.</br>Negócios</label>
             <span class="label-value">
                 
             <?php            
             echo number_format($NotaAutoAvalVerificador , 1 , ',', '.');            
          ?>  

             </span>
           </div>
           
            <div class="list-table-20" style="width:130px">
             <label class="label-control">Questionário</br>de Visita</label>
             <span class="label-value">
                 
             <?php            
             echo number_format( $NotaQuestVisitaVerificador, 1 , ',', '.');            
          ?>  

             </span>
           </div>
           
            <div class="list-table-20" style="width:130px;margin-right:0;">
             <label class="label-control">Critério</br>de Avaliação</label>
             <span class="label-value">
                 
             <?php            
             echo number_format( $QtdPontosFortes, 1 , ',', '.');            
          ?>  

             </span>
           </div>
 

           <div class="list-table-20" style="margin-bottom: 16px;
            margin-right: 5px;
            width: 427px;margin-right: 5px; width: 427px;">
             <label class="label-control">Comentários gerais</label>
           </div>
       </li>
        <?php if ($score->getCheckerStatus() == 'C'): ?>
       <li>
 


    <div id="frmAvaliacao" class="avaliacao">


        <div id="avaliacaoRelato"class="inner-content" style="margin-top: 0; padding-top: 0">
        <ul class="root">
    <?php foreach ($qsts as $blockId => $bloco): ?>

          <li class="macro " style="max-width: 834px;">
            <span class="title topic" style="display: inline; border: none; visibility: hidden; height: 1px;">
            </span>

            <ul style="float: left;">
            <?php foreach ( $qsts[$blockId]['Criterions'] as $criterioId => $criterio): ?>
              <li class="micro ">
                  <p class="title" style="color: #555; border: none; padding: 0; margin: 0">
                    <b class="topic" style="<?php echo (isset($this->criteriosError[$blockId][$criterioId])? 'background-color: #FCFC8D"' : ''); ?>">
                        <?php echo $bloco['BlockName']; ?> -
                        <?php echo $criterio['CriterionValue']; ?>
                    </b>
                  </p>
                  <p style="font: 14px 'Lato'; color:#999; margin-left: 50px; padding-bottom: 20px">
                    <?php $comment ='' ; $comment = comentario($this->commentAnswers,"$blockId$criterioId"); if (isset($comment)): ?>
                         <?php echo $this->escape($comment); ?>
                     <?php endif; ?>
                  </p>
              </li>
            <?php endforeach; ?>

    <?php endforeach; ?>

          <li class="macro">
            <p class="title">
              <b  style="margin-top: 15px" class="topic">Verificação</b>
            </p>
            
            <ul id="verificacao">
                <li class="micro">
                    <ol class="answers">
                        <?php foreach ($this->questionsAvaliacao as $questionAvaliacao): ?>
                          <li data-weight="20" id="question-1" class="question">
                              <div style="width: 542px;min-height: 20px; <?php echo (isset($this->evaluationQuestionsError[$questionAvaliacao->getId()])? 'background-color: #FCFC8D"' : ''); ?>" class="texto">
                                    <?php echo $questionAvaliacao->getValue(); ?>
                              </div>
                            <?php
                                $checked = (isset($this->respostas[$questionAvaliacao->getId()]) and $this->respostas[$questionAvaliacao->getId()]['Resposta'] == 'F')? true : false;

                                if ($checked) : 
                            ?>
                              <div class="answer-option" style="min-height: 20px; width: 210px; margin-top: 0; margin-bottom: 0; border-right: none">

                                <label class="label-inline radio checked" for="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-F" style="background: none !important; padding: 23px 10px 0; font-weight: bold">
                                  Ponto forte
                                </label>
                                </div>
                              <?php endif; ?>

                                <?php
                                    $checked = (isset($this->respostas[$questionAvaliacao->getId()]) and $this->respostas[$questionAvaliacao->getId()]['Resposta'] == 'M')? true : false;
                                    if ($checked):
                                ?>
                              <div class="answer-option" style="min-height: 20px;width: 210px; border-right: none; margin-top: 0; margin-bottom: 0;">

                                <label class="label-inline radio" for="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-M" style="padding: 23px 10px 0">
                                  Oportunidade de melhoria
                                </label>
                               </div>
                            <?php endif; ?>
                           </li>
                       <?php endforeach; ?>
                    </ol>
                </li>

              </ul>
          </li>

            </ul>
          </li>
    </ul>    
        </div>

    </div>
           
           
       </li>
   <?php endif; ?><?php endif; ?>
    </fieldset>
</ul>

		<?php if($score->getCheckerConclusaoDate()){?>
           <div class="list-table-20" style="margin-bottom: 16px;
            margin-right: 5px;
            width: 800px;margin-right: 5px;">
             <label class="label-control">Comentário do Verificador</label>
             <span class="label-value">
                 <?php echo ($score->getCheckerConclusaoDate())? ("(".$score->getCheckerConclusaoDate() . ")") : ''; ?>
               <?php echo $this->escape($score->getCheckerConclusao()); ?>
             </span>
           </div>
           
          <?php } ?>
    <!-- Relato -->
    
    <div class="inner-content">
     <label class="label-control">Relato da Candidata</label>
        <ul id="avaliacaoRelato2">
            <li style="float: left; min-height: 100px; width: auto; height: 100px; overflow: hidden;  border-right: 3px solid #F5F6F7;">
                <?php
                    for ($index = 1; $index < 1000; $index++) {
                        echo '<span style="line-height: 22px;  text-align: right; border-bottom: 1px solid #F5F6F7;  font: italic 14px/22px \'Lato\'; color: #ACACAC; width: 35px; display:block;">' . $index . ' &nbsp; <br></span>';
                    }
                ?>
            </li>
            <li style="padding-left: 10px; width: 730px; float: left; font: 14px/23px 'Lato'; color: rgb(237, 124, 76);">
                <strong><?php echo $this->escape($this->report->getTitle()); ?></strong><br>   
                <?php echo str_replace('&lt;br /&gt;', '<br>', $this->escape(nl2br($this->report->getReport()))); ?>
            </li>
        </ul>
<hr style="clear:both;opacity:0">
    </div>
</form>
<?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        setTimeout(function(){
            cols = $('#avaliacaoRelato2 li');
            cols.eq(0).height(cols.eq(1).height()+207);
            $('#menu-top, #profile').hide();
            $('div.container12').css('margin-top', -97);
        }, 100);
    });
<?php $this->headScript()->captureEnd() ?>