<table class="table">
  <caption></caption>
  <thead>
    <tr>
      <th>Candidata</th>
      <th>Empresa</th>
      <th>UF</th>
      <th>RAA</th>
      <th>Relato</th>
      <th>Avaliar</th>
      <th style="width: 120px">Status</th>
      <th>Motivo da Devolução</th>
      
      <th>Endereço</th>
      <th>Telefone</th>
      <th>Email</th>
    </tr>
  </thead>
<?php
if (count($this->getAllEnterprise) >= 1):
?>
  <tbody>
<?php
    $userIdLogged = Zend_Auth::getInstance()->getIdentity()->getUserId();
  foreach ($this->getAllEnterprise as $index => $enterprise) :
  
    //$raa = $enterprise->getEvaluationPathAvaliador();
    //$ra = '';//$enterprise->getDevolutivePath();
    $raa = $enterprise->getDevolutivePath();
    $avaliador1 = $enterprise->getAppraiserId();
    $avaliador2 = $enterprise->getAppraiserIdSec();
    $avaliador3 = $enterprise->getAppraiserIdTer();

    $avaliador1Status = $enterprise->getAppraiserStatus();
    $avaliador2Status = $enterprise->getAppraiserStatusSec();
    $avaliador3Status = $enterprise->getAppraiserStatusTer();
    
    $devolutiva1 = $enterprise->getAppraiserDevolutiva();
    $devolutiva2 = $enterprise->getAppraiserDevolutivaSec();
    $devolutiva3 = $enterprise->getAppraiserDevolutivaTer();
    $devolutiva = '';

    switch ($userIdLogged) {
        case $avaliador1:
            $devolutiva = $devolutiva1;
            $avaliacaoStatus = $avaliador1Status;
            if ($avaliacaoStatus == 'I' and $devolutiva) {
                $avaliacaoStatus = 'D';
            }
            break;
        case $avaliador2:
            $devolutiva = $devolutiva2;
            $avaliacaoStatus = $avaliador2Status;
            if ($avaliacaoStatus == 'I' and $devolutiva) {
                $avaliacaoStatus = 'D';
            }
            break;
        case $avaliador3:
            $devolutiva = $devolutiva3;
            $avaliacaoStatus = $avaliador3Status;
            if ($avaliacaoStatus == 'I' and $devolutiva) {
                $avaliacaoStatus = 'D';
            }
            break;
    }
    
    /*
    if (!$avaliadorSecundario and $ra) {
        continue;
    }
    */
    
    $devolverAvaliada = '';//$enterprise->getDevolverAvaliada();
    $justificativaDevolver = '';//$enterprise->getJustificativaDevolver();
     
    $scoreGestao = '';//$enterprise->getProgressGestao();
    $fantasyName = $enterprise->getFantasyName();
    $socialName = $enterprise->getSocialName();
    $enterpriseTypeId = '';//$enterprise->getEnterpriseTypeId();
    $CNPJ = trim($enterprise->getCnpj());
    $CPF = trim($enterprise->getCpfUser());
    $enterpriseType = $CPF; //($enterpriseTypeId == '1')?$CNPJ:$CPF;
    $UF = trim($enterprise->getUf());
    $survey = $survey_progress = false;
    //if ($enterprise->getDiagnosticoEligibility()) :
      if ($permissionRespondAll) :
        $survey = $this->baseUrl('/management/avaliacao/index/enterprise-id-key/' 
            . $enterprise->getIdKey());
        $survey_progress = (($scoreGestao) ? ('Gestão: ' . $scoreGestao . '%') : false);
      endif;
      
      if ($avaliacaoStatus == 'C') {
          continue;
      }
      
    $endereco  = ($enterprise->getStreetNameFull())?$enterprise->getStreetNameFull():'';
    $endereco .= ($enterprise->getStreetNumber())?', '.$enterprise->getStreetNumber():'';
    $endereco .= ($enterprise->getStreetCompletion())?', Compl: '.$enterprise->getStreetCompletion():'';;
    $endereco .= ($enterprise->getCep())?', CEP: '.$enterprise->getCep():'';

    $telefone=trim($enterprise->getPhoneUser());
    $email=trim($enterprise->getEmailUser());
      
    //endif;
?>
    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="<?php echo $enterprise->getIdKey(); ?>">
      <td>
          <dl style="text-align: left; margin-left: 5px">
          <dt title="<?php echo $fantasyName; ?>"><b><?php echo (($enterprise->getNameUser() != '') ? substr($enterprise->getNameUser(), 0, 60) : '--'); ?></b></dt>
          <dd class="identity" title="<?php echo $enterpriseType; ?>"><?php echo $enterprise->getCpfUser(); ?></dd>
        </dl>

      </td>
      
        <td style="width: 300px; height: 45px;" title="<?php echo $socialName; ?>">
          <dl style="text-align: left; margin-left: 5px">
            <dt><b><?php echo (($fantasyName != '') ? substr($fantasyName, 0, 60) : '--'); ?></b></dt>
            <dd class="identity"><?php echo $CNPJ; ?></dd>
          </dl>
        </td>
        
      <td class="middle"><i><?php echo $UF; ?></i></td>
      <td class="middle">
        <dl>
          <dt>
            <a href="<?php echo $raa; ?>" title="Baixar RAA" class="download-raa" target="blank">Baixar RAA</a>
          </dt>
        </dl>
      </td>
      <td class="middle">
        <dl>
          <dt>
            <a href="<?php echo $this->baseUrl("management/avaliacao/report/enterprise-id-key/{$enterprise->getIdKey()}"); ?>#report" title="Relatório Interno" class="download-raa" target="blank">Interno</a>
          </dt>
        </dl>
      </td>
      <td class="middle">
        <dl>
            <dt>
                <a href="<?php echo $survey; ?>" title="Avaliar" 
                   class="answer-survey" >Avaliar</a>
            </dt>
        </dl>
      </td>
      
            <td>
          <?php
                echo Vtx_Util_PsmnAvaliacao::statusReport($avaliacaoStatus);
          ?>
      </td>
       <td class="middle" style="width: 300px"> <?php echo $devolutiva; ?> </td>
       
       <td class="middle" style="width: 100px"><?php echo $endereco; ?> </td>
       <td class="middle" style="width: 100px"><?php echo $telefone; ?> </td>
       <td class="middle" style="width: 100px"><?php echo $email; ?> </td>
       
    </tr>
<?php endforeach; ?>
  </tbody>
<?php endif; ?>
</table>
