<h1 class="center">Associação Avaliadores x Empresas</h1>
<a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/appraiser/'); ?>">Voltar</a>
<?php if (isset($this->itemUpdateSuccess)):?>
    <?php if ($this->itemUpdateSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Avaliador (<?php echo $this->name; ?>) editado com sucesso. <br /><br />
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($this->itemInsertSuccess)):?>
    <?php if ($this->itemInsertSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Regional (<?php echo $this->name; ?>) cadastrada com sucesso. <br /><br />
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>