<?php
$this->headScript()
    //->appendFile($this->baseUrl('js/management/role-questionnaire.js'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.metadata.js'))
    ->prependFile($this->baseUrl('js/validation/jquery.validate.min.js'));

include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div id="content" class="pag_role_index">
    <h1 class="center">role-questionnaire</h1>

    <?php if (isset($this->itemInsertSucess)): ?>
        <?php if ($this->itemInsertSucess): ?>
            <div class="notice success">
                <span data-icon="C" class="icon medium"></span>
                        role-questionnaire inserida com sucesso.
                <a data-icon="x" class="icon close" href="#close"></a>
            </div>
        <?php endif; ?>
    <?php endif; ?> 

    <?php if (isset($this->itemUpdateSucess)): ?>
        <?php if ($this->itemUpdateSucess): ?>
            <div class="notice success">
                <span data-icon="C" class="icon medium"></span>
                        role-questionnaire alterada com sucesso.
                <a data-icon="x" class="icon close" href="#close"></a>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if (isset($this->itemDeleteSuccess)): ?>
        <?php if ($this->itemDeleteSuccess): ?>
            <div class="notice success">
                <span data-icon="C" class="icon medium"></span>
                        role-questionnaire excluída com sucesso.
                <a data-icon="x" class="icon close" href="#close"></a>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>
    

    <form action="<?php echo $this->url(array('page' => $this->pageCount, 'format' => 'html')) ?>" id="frm" method="GET">
        <fieldset>

            <label for="Role">Perfil</label> <?php // leia-se: Papel   ?>
                <select tabindex="1" name="filter[role_id]" id="RoleId" class="fnc fancy" style="width: 160px">
                    <option value="">Todos</option>
                    <?php foreach ($this->getAllRoles as $role) : ?>
                        <?php if ($role->getId() == $this->filter['role_id']) : ?>
                            <option value="<?php echo $role->getId();?>" selected="selected"><?php echo $role->getLongDescription();?></option>
                        <?php else :  ?>
                            <option value="<?php echo $role->getId();?>"><?php echo $role->getLongDescription();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />
            
            <label for="Questionnaire">Questionários:</label>
                <select tabindex="2" name="filter[questionnaire_id]" id="QuestionnaireId" class="fnc fancy" style="width: 160px">
                    <option value="">Todos</option>
                    <?php foreach ($this->getAllQuestionnaires as $questionnaire) : ?>
                        <?php if ($questionnaire->getId() == $this->filter['questionnaire_id']) : ?>
                            <option value="<?php echo $questionnaire->getId();?>" selected="selected"><?php echo $questionnaire->getDescription();?></option>
                        <?php else :  ?>
                            <option value="<?php echo $questionnaire->getId();?>"><?php echo $questionnaire->getDescription();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <br class="clear" />
            
            <button tabindex="3" style="float: right" type="submit" class="green small">
                <span class="icon small" style="left: 3px; top: -2px;" data-icon="s"></span>
            </button>
        </fieldset>
    </form> 

    <?php echo $this->paginationControl($this->getAllRoleQuestionnaire); ?>
    <div class="clear"></div>
    <table cellspacing="0" cellpadding="0" border="0" class="striped tight">
        <caption></caption>
        <colgroup>
            <col class="firstCol" style="width: 200px">
            <col>
        </colgroup>
        <thead>
            <tr class="alt first last">
                <th>Papel</th>
                <th>Questionário</th>
                <th>Inicio</th>
                <th>Fim</th>
                <th class="lastTd">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->getAllRoleQuestionnaire as $roleQuestionnaire): ?>
            <tr class="first" >
                <th nowrap><?php echo $roleQuestionnaire->getRoleId();?></th>
                <td><?php echo $roleQuestionnaire->getQuestionnaireId();?></td>
                <td><?php echo $roleQuestionnaire->getStartDate();?></td>
                <td><?php echo $roleQuestionnaire->getEndDate();?></td>
                <td class="center">
                    <a href="<?php echo  $this->baseUrl('/management/role-questionnaire/edit/id/'.$roleQuestionnaire->getId()); ?>" title="Editar role-questionnaire"><span class="ico edit">Editar</span></a>
                    <a href="<?php echo  $this->baseUrl('/management/role-questionnaire/delete/id/'.$roleQuestionnaire->getId()); ?>" title="Excluir role-questionnaire" class="delete"><span class="ico delete">Excluir</span></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="clear"></div>
    <?php echo $this->paginationControl($this->getAllRoleQuestionnaire, null, null); ?>
    <hr class="clear" />
</div>