# encoding: utf-8

class CreateCourse < ActiveRecord::Migration
  def up
    create_course_table
    populate_table
  end

  def create_course_table
    create_table 'Course', primary_key: 'Id' do |t|
      t.integer 'Code'
      t.string 'Name'
      t.integer 'CourseTypeId'
      t.string 'ManagementThemeId'
    end

    add_index 'Course', 'Id'
    add_index 'Course', 'Code'
    add_index 'Course', 'Name'
  end

  def populate_table
    puts "123"

    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('165','GEI - Gestão Empresarial Integrada (On Line)',1,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('146','MEG - Primeiros Passos para a Excelência (On Line)',1,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('149','Sei Empreender (On Line)',1,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('141','AE - Aprender a Empreender',1,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('121','SEI Administrar - Kit educativo Aprender a Empreender',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('124','SEI Empreender',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('132','Consultoria especializada - Empreendedorismo',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('105','Programa SEBRAE Mais - Empretec',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('87','PAS Leite - CIO em APPCC para laticínios - 1 linha de processo',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('88','PAS Leite - CIO em BPF/PPHO para laticínios',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('89','PAS Leite - Curso de Implantação Orientada - Boas Práticas para produtores de Leite',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('90','PAS Mel - CIO para Entrepostos-BPF',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('91','PAS Mel - CIO para Unidades de Extração de Mel',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('92','PAS Mesa - CIO APPCC para Micro e Pequenas - 1 grupo de alimentos',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('93','PAS Mesa - CIO em BP para Quiosques e Barracas',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('94','PAS Mesa - CIO Micro na NBR 15635 - sem Boas Práticas implantadas',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('95','PAS Mesa - CIO Pequenas na NBR 15635 - sem Boas Práticas implantadas',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('96','PAS Mesa - Curso de Implantação Orientada (CIO)',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('97','PAS Mesa - Curso de Implantação Orientada (CIO)',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('98','PAS Mesa - Curso de Implantação Orientada (CIO) em BP Ambulantes',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('99','PAS Uva - CIO BPF e APCC para cantinas',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('58','Jovens Empreendedores Primeiros Passos - JEPP',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('74','PAS Açaí - CIO em BPF e APPCC para agroindústrias',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('38','Gestão Ambiental para o Setor de Calçados',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('3','Aprender a Empreender',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('23','Crescendo e Empreendendo',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('31','Empretec',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('28','Desafio SEBRAE',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('29','Despertar',2,8)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('36','Fundo de Aval à Micro e Pequena Empresa',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('32','Entendendo Custos, Despesas e Preço de Venda',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('25','Custos para produzir no Campo',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('10','Bolsa de Negócios',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('53','Gestão financeira na Medida',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('22','Controlar meu dinheiro no Campo',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('110','Programa SEBRAE Mais - Gestão Financeira do Controle à Decisão',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('135','Consultoria especializada - Finanças',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('123','SEI Controlar Meu Dinheiro',2,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('147','Sei Controlar meu Dinheiro (On Line)',1,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('153','APF - Análise e Planejamento Financeiro (On Line)',1,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('155','FPV - Formação do Preço de Venda (On Line)',1,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('162','Programa Varejo Fácil - Formação do Preço de Venda',1,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('163','Programa Varejo Fácil - Controles Financeiros',1,2)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('173','GI - Gestão da Inovação: Inovar para Competir (On Line)',1,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('138','Consultoria especializada - Inovação',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('118','Roteiros para implantação de ambientes Inovativos',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('131','Workshop de Inovação para as Micro e Pequenas Empresas',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('116','Responsabilidade Social: Passo a Passo',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('104','Programa de Alavancagem tecnológica (PAT)',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('109','Programa SEBRAE Mais - Gestão da Inovação - Inovar para Competir',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('69','Palestra de venda - Gestão da Inovação',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('70','Palestra de venda - Roteiro para a Implantação de Ambientes Inovativos',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('72','Palestra Sustentabilidade',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('57','Internet para Pequenos Negócios',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('55','Inovação como Estratégia Competitiva',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('39','Gestão da Inovação - Inovar para Competir',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('5','Auto-Avaliação em Eficiência Energética',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('6','Auto-Avaliação em Sustentabilidade',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('7','Boas Práticas de Qualidade em Serviços Automotivos',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('24','Curso de Capacitação de Produtores de Uva para processamento',2,5)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('73','Palestra: Empreendedor Individual',2,6)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('67','Os Novos Benefícios da Lei Geral da Micro e Pequena Empresa e do Supersimples',2,6)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('137','Consultoria especializada - Leis e Normas',2,6)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('143','MEI - Microempreendedor Individual',1,6)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('145','MEI - Microempreendedor Individual',1,6)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('166','CG - Compras Governamentais (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('167','CVME - Condições de venda para o mercado externo (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('168','PROEX - Procedimentos para Exportação (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('169','PLAEX - Planejamento para Exportar (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('164','Programa Varejo Fácil - Atendimento ao Cliente',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('157','IPN - Internet para Pequenos Negócios',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('158','AC - Atendimento ao Cliente (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('159','Programa Varejo Fácil - Técnicas de Vendas',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('144','CG - Compras Governamentais',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('154','CVMM - Como Vender Mais e Melhor (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('152','Sei Vender (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('150','Sei Comprar (On Line)',1,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('134','Consultoria especializada - Mercado',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('122','SEI Comprar',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('127','SEI Vender',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('128','Técnicas de Vendas',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('129','Técnicas para Negociações',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('130','Vender para o Governo no Campo',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('102','Plano de marketing na Medida',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('103','Primeiro e-Commerce',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('117','Rodada de Negócios',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('111','Programa SEBRAE Mais - Plano de Marketing Avançado',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('106','Programa SEBRAE Mais - Encontros Empresariais',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('107','Programa SEBRAE Mais - Estratégias Empresariais',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('33','Feira do empreendedor',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('34','Feira do empreendedor online',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('41','Gestão da Qualidade - Parcerias eficazes',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('4','Atender bem no campo',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('1','Acesso a feiras',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('2','Análise de Mercado',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('11','Click Marketing',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('12','Comércio Brasil',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('13','Como Analisar e Escolher uma Franquia (oficina)',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('14','Como Atrair, Conquistar e Manter Clientes',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('15','Como Conquistar e Manter Clientes',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('16','Como construir sua loja virtual',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('17','Como criar um site de sucesso',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('18','Como escolher a franquia mais adequada a seu perfil (curso)',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('19','Como Vender Mais e Melhor',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('20','Compras Governamentais - Como Fornecer para a Administração Pública e Reduzir os Riscos',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('21','Conecte seu negócio',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('47','Gestão do Visual de Loja',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('48','Gestão do Visual de Lojas - Combo',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('56','Inteligência em Feiras',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('52','Gestão Empresarial Integrada',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('66','Oportunidades de Negócios para as MPE nas Compras Governamentais',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('63','O que é e como funciona uma franquia (palestra)',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('61','Negociar no Campo',2,1)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('60','Logística',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('64','Oficina 5 Menos que São Mais',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('65','Oficina Resíduos Sólidos como vantagem competitiva',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('75','PAS Açaí - CIO para batedeiras artesanais',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('76','PAS Distribuição - CIO APPCC para Micro e Pequenas - 1 grupo de alimentos',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('77','PAS Distribuição - Cio Boas Práticas para Feirantes',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('78','PAS Distribuição - CIO Boas Práticas para Micro e Pequenas Empresas - 1 setor - boxes',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('79','PAS Distribuição - CIO Boas Práticas para Micro e Pequenas Empresas - 3 setores',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('80','PAS Distribuição - CIO Boas Práticas para Micro e Pequenas Empresas - mais de 3 setores',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('81','PAS Distribuição - CIO Micro e Pequenas na NBR 15635 - com Boas Práticas implantadas',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('82','PAS Distribuição - CIO Micro na NBR 15635 - sem Boas Práticas implantadas',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('83','PAS Distribuição - CIO Pequenas na NBR 15635 - sem Boas Práticas implantadas',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('84','PAS Indústria - CIO APPCC para Micro e Pequenas - 1 linha de processo',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('85','PAS Indústria - CIO Micro',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('86','PAS Indústria - Curso de Implantação Orientada (CIO)- BPF',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('49','Gestão e Técnicas de Produção',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('50','Gestão e Técnicas de Produção - Têxtil e Confecções',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('40','Gestão da Qualidade - Auditorias internas',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('45','Gestão de estoques',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('8','Boas Práticas nos Serviços de Alimentação - Gestão da Segurança - Internet',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('9','Boas Práticas nos Serviços de Alimentação: Gestão da Segurança - Curso - Segmento: Alimentos',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('42','Gestão da Qualidade: Os processos ',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('43','Gestão da Qualidade: Os requisitos da ISO 9001',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('37','Gerenciando o Fluxo de Caixa com Eficiência',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('35','Fluxo de Caixa',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('26','D’Olho na Qualidade',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('27','D’Olho na Qualidade Total Rural',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('112','Programa SEBRAE Mais - Programa SEBRAE de Gestão da Qualidade',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('114','Qualidade e Produtividade: Conceitos que mudam um Negócio',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('115','Qualidade Total Rural',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('68','Palestra 5 Menos que São Mais',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('71','Palestra Resíduos Sólidos como vantagem competitiva',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('140','Consultoria especializada - Organização',2,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('160','Programa Varejo Fácil - Gestão do Visual de Loja',1,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('156','D-Olho na Qualidade: 5Ss para os pequenos negócios (On Line)',1,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('171','BPSA - Boas práticas nos serviços de alimentação',1,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('172','GQVE - Gestão da Qualidade: Visão Estratégica',1,4)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('161','Programa Varejo Fácil - Gestão de Pessoas',1,3)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('136','Consultoria especializada - Pessoas',2,3)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('120','Segurança e Saúde no Trabalho',2,3)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('46','Gestão de pessoas na Medida',2,3)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('54','Iniciando um Pequeno Grande Negócio',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('62','Negócio Certo Rural',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('30','Determinação Empreendedora',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('44','Gestão da Qualidade: Visão estratégica',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('113','PRÓPRIO',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('108','Programa SEBRAE Mais - Ferramentas de Gestão Avançada',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('100','Planejamento estratégico na Medida',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('101','Planejando para Internacionalizar',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('133','Consultoria especializada - Planejamento',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('125','SEI Planejar',2,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('142','IPGN - Iniciando um Pequeno e Grande Negócio',1,7)"
    execute "insert into Course (Code,Name,CourseTypeId,ManagementThemeId) values ('148','Sei Planejar (On Line)',1,7)"
  end

  def down
    drop_table 'Course'
  end
end
