<?php
    $this->headScript()
        ->appendFile($this->baseUrl('js/management/user.js'))
?>

    <h1 class="title">Usuários</h1>
    
    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>
    
    <?php if (isset($this->itemDeleteSuccess)):?>
        <?php if ($this->itemDeleteSuccess):?>
            <div class="notice success">
                <span data-icon="C" class="icon medium"></span>
                        Usuário deletado com sucesso.
                <a data-icon="x" class="icon close" href="#close"></a>
            </div>
        <?php return; endif; ?>
    <?php endif; ?>
     
    
    <form action="<?php echo $this->url(array('page' => $this->pageCount, 'format' => 'html')) ?>" id="frm" method="GET">
        <fieldset>
            <input type="hidden" id="orderByValue" name="orderBy" value="" />
            <input type="hidden" value="<?php echo $this->orderBy; ?>" />
       </fieldset>
        <fieldset>
          <div class="list-table-20">
            <label class="label-control" for="name">Nome:</label>
            <input tabindex="1" id="name" type="text" name="filter[first_name]" value="<?php if(isset($this->filter['first_name'])) echo $this->filter['first_name'];?>" size="18" value="" class="input list-table-100" />
          </div>

          <div class="list-table-20">
            <label class="label-control" for="Cnpj">Login:</label>
            <input tabindex="1" id="cnpj" type="text" name="filter[login]" value="<?php if(isset($this->filter['login'])) echo $this->filter['login'];?>" size="18" value="" class="input list-table-100" />
          </div>

          <div class="list-table-20">
            <label class="label-control" for="Cnpj">CPF:</label>
            <input tabindex="1" id="Cpf" type="text" name="filter[cpf]" value="<?php if(isset($this->filter['cpf'])) echo $this->filter['cpf'];?>" size="18" value="" class="input list-table-100" />
          </div>

          <div class="list-table-20">
            <label class="label-control" for="RoleId">Perfil:</label>
            <select tabindex="3" name="filter[role_id]" id="RoleId" class="fancy" >
                <option value="">Todos</option>
                <?php foreach ($this->roles as $role) :
                        if ($role->getId() == $this->configRegistry()->acl->roleSupremeAdminId
                                or $role->getId() == $this->configRegistry()->acl->roleEnterpriseId
                                or $role->getId() == $this->configRegistry()->acl->roleGuestId) {
                            continue;
                        }
                    ?>
                    <?php if ($this->filter['role_id'] == $role->getId()): ?>
                        <option value="<?php echo $role->getId();?>" selected="selected"><?php echo $role->getLongDescription();?></option>
                    <?php else:?>
                        <option value="<?php echo $role->getId();?>"><?php echo $role->getLongDescription();?></option>
                    <?php endif;?>
                 <?php endforeach;?>
            </select>
          </div>
        </fieldset>
        <fieldset>

          <div class="list-table-70">
            <label class="label-control" for="RegionalId" class="">Regional:</label>
            <select tabindex="4" name="filter[regional_id]" id="RegionalId" class="fancy">
                <option value="">Todas</option>
                <?php foreach ($this->getAllRegional as $regional) :?>
                    <?php if ( $regional->getId() == $this->filter['regional_id'] ) :?>
                        <option value="<?php echo $regional->getId();?>" selected="selected"><?php echo $regional->getDescription();?></option>
                    <?php else : ?>
                        <option value="<?php echo $regional->getId();?>"><?php echo $regional->getDescription();?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
          </div>
            
          <div class="list-table-20">
            <label class="label-control" for="StatusId" class="">Status:</label>
            <select tabindex="5" name="filter[status]" id="StatusId" class="fancy" style="width: 100px;">
                <option value="">Todas</option>
                    <?php foreach (Vtx_Util_Array::status() as $key => $status) :?>
                        <?php if ( $key == $this->filter['status'] ) :?>
                            <option value="<?php echo $key;?>" selected="selected"><?php echo $status;?></option>
                        <?php else : ?>
                            <option value="<?php echo $key;?>"><?php echo $status;?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
            </select>
          </div>
            
            
        </fieldset>
        <button tabindex="16" style="float: right" type="submit" class="large btn-submit">Buscar</button>
    </form>


    <div class="table-menu header">
<?php
$total = $this->getAllUsers->getTotalItemCount();
$label_total = (($total > 0) ? implode(' ', array(
  $total,
  implode('', array(
    'registro',
    (($total > 1) ? 's' : '')
  ))
)) : 'Nenhum registro encontrado');
?>
      <hgroup>
        <h2>Usuários - <span><?php echo $label_total; ?></span></h2>
        <!-- <h3>Empresas inelegíveis para o Prêmio MPE</h3> -->
      </hgroup>
      <?php echo $this->paginationControl($this->getAllUsers, null, null); ?>
    </div>

    <table id="table-details">
        <caption></caption>
        <colgroup>
            <col class="firstCol">
            <col>
            <col>
            <col class="lastCol">
        </colgroup>
        <thead>
            <tr class="alt first last">
                <th style="width: 230px">Nome</th>
                <th style="width: 130px">Usuário</th>
                <th style="width: 110px">Perfil</th>
                <th style="width: 90px">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($this->getAllUsers) >= 1) : 
                foreach($this->getAllUsers as $user):
                    $roleRow = $user->findParentUserRole()->findParentRole();
                    $role = $roleRow->getLongDescription();
                    $username = $user->getLogin();
            ?>
                <tr class="first">
                    <th><?php echo $user->getFirstName().' '.$user->getSurname(); ?></th>
                    <td><?php if ($username) echo $username; ?></td>
                    <td><?php if ($role) echo $role; ?></td>
                    <td class="center">
                        <?php if ($roleRow->getId() != Zend_Registry::get('config')->acl->roleSupremeAdminId
                                and $roleRow->getId() != Zend_Registry::get('config')->acl->roleEnterpriseId): ?>
                            <?php if ($this->loggedAllowed('edit', 'management:user')): ?>
                                <a href="<?php echo  $this->baseUrl('/management/user/edit/id/'.$user->getId()); ?>" title="Editar usuário"><span class="ico edit">Editar</span></a>
                            <?php endif; ?>
                            <?php if ($this->loggedAllowed('delete', 'management:user')): ?>
                                <a href="<?php echo  $this->baseUrl('/management/user/delete/id/'.$user->getId()); ?>" title="Deletar usuário" class="delete"><span class="ico delete confirm">Excluir</span></a>
                            <?php endif; ?>
                         <?php endif;?>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr>
                    <td width="220" colspan="4">Não existem resultados para a busca realizada.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="table-menu footer">
      <?php echo $this->paginationControl($this->getAllUsers, null, null); ?>
    </div>
