<?php 
$this->headScript()
    ->appendFile($this->baseUrl('js/address/capital.js'))
    ->appendFile($this->baseUrl('js/management/group/edit.js'));
include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
$groupId = $this->groupRow->getId();
?>
<div id="content" class="">
    <h1 class="center">
        Grupo
    </h1>
    <a name="Voltar" id="back" href="<?php echo $this->baseUrl('management/group/'); ?>">Voltar</a>

    <?php if ($this->messageError): ?>
        <div class="notice error">
            <span data-icon="X" class="icon medium"></span>
                <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
       </div>
    <?php endif; ?>

    <form id="frm" autocomplete="on" method="GET" action="">
        <fieldset>
            <input type="hidden" name="id" id="GroupId"  value="<?php if($groupId) echo $groupId;?>">

            <label for="name">Grupo: </label>
            <input tabindex="1" type="text" name="name" readonly="readonly" disable id="GroupName" style="font-weight: bold"
                   value="<?php if ($this->groupRow) { echo $this->groupRow->getName(); } ?>">


            <select class="sortBy hide">
                <option value="">Empresa &nbsp;</option>
                <option value=""<?php echo '$this->orderBy' == 'FinalScore DESC'? ' selected' : ''; ?>>Avaliador &nbsp;</option>
            </select>

            <label>Regional:</label>
            <select name="filter[regional_id]" class="fnc">
                <option value="">Todas</option>
                <?php foreach ($this->getAllRegional as $regional) :?>
                    <?php if ( $regional->getId() == $this->filter['regional_id'] ) :?>
                        <option value="<?php echo $regional->getId();?>" selected="selected"><?php echo $regional->getDescription();?></option>
                    <?php else : ?>
                        <option value="<?php echo $regional->getId();?>"><?php echo $regional->getDescription();?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <hr class="clear" />

            <label for="Cnpj">Empresa:</label>
            <input tabindex="1" id="coopName" type="text" name="filter[coop_name]" size="18" value="<?php echo isset($this->filter['coop_name'])? $this->filter['coop_name'] : ''; ?>"  />


                <label for="Cnpj">CNPJ:</label>
                <input tabindex="1" id="cnpj" type="text" name="filter[cnpj]" size="18" value="<?php echo isset($this->filter['cnpj'])? $this->filter['cnpj'] : ''; ?>" style="padding-right: 0px; " />
            <hr class="clear" />

            <label for="showOnly" class="fnc select">Mostrar:</label>
            <select tabindex="10" id="showOnly" class="fnc" name="filter[show_only]">
                <option value="">Todas</option>
                <option value="groupIsNull" <?php echo (isset($this->filter['show_only']) && $this->filter['show_only'] == 'groupIsNull')? 'selected' : '';?>>Coops. sem grupo</option>
            </select>

                <label for="Uf" class="select">UF:</label>
                <select data-placeholder="" tabindex="10" id="Uf" class="fnc" name="filter[state_id]">
                    <option value="">Todos</option>
                    <?php foreach ($this->getAllStates as $states) : ?>
                        <?php if (isset($this->filter['state_id']) && $states->getId() == $this->filter['state_id']) : 
                        ?>
                            <option value="<?php echo $states->getId();?>" selected><?php echo $states->getUf();?></option>
                        <?php else : ?>
                            <option value="<?php echo $states->getId();?>"><?php echo $states->getUf();?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>

                <hr class="clear" />
                <label for="city" class="select">Cidade:</label>
                <select tabindex="10" id="CityId" class="fnc" name="filter[city_id]">
                    <option value="">Todas</option>
                    <?php if (isset($this->getAllCities)) : ?>
                        <?php foreach ($this->getAllCities as $cities) : ?>
                            <?php if ($cities->getId() == $this->filter['city_id']) : ?>
                                <option value="<?php echo $cities->getId();?>" selected="selected"><?php echo $cities->getName();?></option>
                            <?php else : ?>
                                <option value="<?php echo $cities->getId();?>"><?php echo $cities->getName();?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>

                <label for="Neighborhood" class="select">Bairro:</label>
                <select tabindex="10" id="NeighborhoodId" class="fnc" name="filter[neighborhood_id]">
                    <option value="">Todos</option>
                    <?php if (isset($this->getAllNeighborhoods)) : ?>
                        <?php foreach ($this->getAllNeighborhoods as $neighborhood) : ?>
                            <?php if (isset($this->filter['neighborhood_id']) && $neighborhood->getId() == $this->filter['neighborhood_id']) : ?>
                                <option value="<?php echo $neighborhood->getId();?>" selected="selected"><?php echo $neighborhood->getName();?></option>
                            <?php else : ?>
                                <option value="<?php echo $neighborhood->getId();?>"><?php echo $neighborhood->getName();?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>

                <hr class="clear" />
                <label for="Status" class="">Status:</label>
                <select tabindex="4" name="filter[status]" class="fnc" id="Status">
                    <?php foreach (Vtx_Util_Array::status() as $key => $status) :?>
                        <?php if ( $key == $this->filter['status'] ) :?>
                            <option value="<?php echo $key;?>" selected="selected"><?php echo $status;?></option>
                        <?php else : ?>
                            <option value="<?php echo $key;?>"><?php echo $status;?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <button tabindex="16" style="float: right" type="submit" class="green small">
                <span class="icon small" style="left: 3px; top: -2px;" data-icon="s"></span>
            </button>
        </fieldset>
    </form>
    
    <?php
        echo $this->paginationControl(
            $this->getAllEnterpriseByRegionalServiceArea, null, null, array(/*'link' => $this->baseUrl('/xx')*/ )
        );
    ?>
        
    <div class="clear"></div>
    <table class="striped " border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 200px">Título</th>
                <th class="lastTd">Relacionamento</th>
            </tr>
        </thead>
        <tbody>
        <?php if (count($this->getAllEnterpriseByRegionalServiceArea) >= 1) : ?>
        <?php
            foreach ($this->getAllEnterpriseByRegionalServiceArea as $enterprise) :
            ?>
                <tr>
                    <td><?php echo $enterprise->getSocialName();?></td>
                    <td>
                        <label style="text-align: left; font-size: 1em; width: 100%;">
                            <?php
                                 if ($enterprise->getGroupId() == NULL) {
                                      if ($this->loggedAllowed('set-group-to-enterprise')) {
                                         echo '<input data-enterprise-id="' . $enterprise->getId() . '" name="allowGroup[enterprise_id]['.$enterprise->getId().']" value="0" type="checkbox" class="checkbox" title="Selecionar empresa para o grupo" /><span style="font-size: 1em;color:#505050"></span>';
                                     }
                                 } else {
                                     if ($enterprise->getGroupId() == $groupId) {
                                         if ($this->loggedAllowed('set-group-to-enterprise')) {
                                             echo ' <input data-enterprise-id="' . $enterprise->getId() . '" name="allowGroup[enterprise_id]['.$enterprise->getId().']" value="1" checked="checked" title="Tirar seleção da empresa para o grupo" type="checkbox" class="checkbox"/>';
                                         }
                                     } else {
                                         echo ' <input type="checkbox" class="checkbox" checked disabled> ';
                                     }
                                     echo '<span style="font-size: 1em; color:#505050"> ' . $enterprise->getGroupName() . ' </span>';
                                 }
                             ?>
                        </label>
                        
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
        </tbody>
    </table>
    <?php
        echo $this->paginationControl(
            $this->getAllEnterpriseByRegionalServiceArea, null, null, array(/*'link' => $this->baseUrl('/xx')*/ )
        );
    ?>

        <div class="clear"> </div>
	</form>
</div>