<hr />
<div id="welcome">
    <h3>Edição de Tipo de contato</h3>
    
    <br />
    
    <form method="POST" action="<?php echo $this->baseUrl('contacttype/edit/id/'.$this->data->getId()); ?>">
        <input type="hidden" name="id" value="<?php echo $this->data->getId();?>">
        <label>Descrição </label>
        <input type="text" name="description" value="<?php echo $this->data->getDescription();?>">
        <br />
        <button type="submit" value="salvar">Alterar</button>
    </form>
</div>
<hr />
<?php if ($this->dataRowEdit): ?>
    Tipo de contato [<?php echo $this->data->getDescription(); ?>] editado com sucesso.
<?php endif; ?>
<hr />
<?php
// var_dump($this->data->toArray());
?>
