<?php 
include realpath(dirname(__FILE__) . '/../menus/permission.phtml');
?>
<div id="conteudo">
    <h1>Tipos de contato</h1>
    
    <form method="POST" action="<?php echo $this->baseUrl('contacttype/'); ?>">
        <label>Descrição </label>
        <input type="text" name="description">
        <br />
        <button type="submit" value="salvar">Adicionar Tipo de Contato</button>
    </form>

</div>
<hr />
<?php if ($this->dataRow): ?>
    Sucesso novo: [<?php echo $this->dataRow->getId() ?>] <?php echo $this->dataRow->getDescription(); ?>
<?php endif; ?>
    
<?php if ($this->dataRowDelete): ?>
    Tipo de contato deletado com sucesso.
<?php endif; ?>
<hr />
    <table>
        <tr>
            <th>-</th>
            <th>id</th>
            <th>descrição</th>
            <th>ações</th>
        </tr>
    <?php foreach ($this->geral as $linha): ?>
        <tr style="border: 1px solid #000">
            <td><?php echo ($this->dataRow and $this->dataRow->getId() == $linha->getId())? 'NOVO' : '-'; ?></td>
            <td><?php echo $linha->getId(); ?></td>
            <td><?php echo $linha->getDescription(); ?></td>
            <td>
                <a href="<?php echo $this->baseUrl('contacttype/edit/id/'.$linha->getId()); ?>" alt='editar' tille='editar' >edit</a>
                 / 
                <a href="<?php echo $this->baseUrl('contacttype/delete/id/'.$linha->getId()); ?>" alt='delete' tille='delete' >delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<hr />