<?php $this->headScript()->captureStart() ?>
    var SERVICE_AREA = <?php echo json_encode($this->serviceArea);?>;
<?php $this->headScript()->captureEnd() ?>
    
<?php 
$this->headScript()
    ->appendFile($this->baseUrl('js/address/capital.js'))
    ->appendFile($this->baseUrl('js/management/questionnaire/regional.js'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.metadata.js'))
    ->prependFile($this->baseUrl('js/validation/jquery.validate.min.js'))
    ->prependFile($this->baseUrl('js/validation/lib/jquery.form.js'));

//$this->headLink()->prependStylesheet($this->baseUrl('css/custom-theme/jquery-ui-1.8.23.custom.css'));
?>
<?php 



include realpath(dirname(__FILE__) . '/../menus/admin.phtml');
?>
<div class="pageEditRegional" id="content">
    <h1 class="title">
        Regionais/Perfis de Acesso por Localidade
    </h1>

    <a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/regional'); ?>">Voltar</a>
<?php if (isset($this->itemEditSuccess)):?>
    <?php if ($this->itemEditSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span> Regional alterada com sucesso.
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($this->itemInsertSuccess)):?>
    <?php if ($this->itemInsertSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Regional inserida com sucesso.
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
    
<?php if (isset($this->messageError)):?>
    <?php if ($this->messageError):?>
        <div class="notice error">
            <span data-icon="C" class="icon medium"></span>
                    <?php echo $this->messageError; ?>
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
    
    <form id="frmRegional" class="normal" action="<?php echo $this->baseUrl( ($this->request()->getActionName() == 'insert')? 
                  'management/regional/insert/format/json' : 
                  'management/regional/edit/id/'.$this->regionalRow->getId().'/format/json'); ?>" method="POST" class="normal" autocomplete="on">
         <div id="msgError" class="notice error autoScroll" style="margin-left: 26px; z-index: 9999">
             <span class="icon small" data-icon="X"></span>
             <b></b><a href="#close" class="icon close" data-icon="x"></a>
         </div>
		 <fieldset>        
             
			<label for="description" class="label-control">Nome:</label>
                <input tabindex="1" type="text" name="regional[description]" id="description" class="w220 {required:true} input"
                       value="<?php if (isset($this->regionalRowData['description'])) echo $this->regionalRowData['description'];?>">
            <hr class="clear" />

            <input type="hidden" name="regional[status]" id="status"
                       value="<?php if (isset($this->regionalRowData['status'])) {echo $this->regionalRowData['status']; } else {echo 'A';}?>">

            
            <label for="allUfs" class="label-control">Estados integrantes:</label>
            <select tabindex="3" class="fanc2y" style="width:388px !important;" id="allUfs" name="allUfs">
                <option value="">Todos os Estados</option>
                <option value="s" <?php if (isset($this->allStateId) and !($this->request()->getActionName() == 'insert')) echo 'selected="selected"'; ?>>Seleção de Estado(s)...</option>
            </select>
            
            <div id="areaSelectUfs" class="<?php if (!isset($this->allStateId) or ($this->request()->getActionName() == 'insert') ) echo "hide"; ?>">
                <label>&nbsp;</label>
                <select data-placeholder="Selecione os Estados" multiple tabindex="10" id="ufs" class="fanc2y" style="width:388px !important; height: 130px;" name="serviceArea[states][]">
                    <?php $estados = array(); ?>
                    <?php foreach ($this->allStateId as $value) : ?>
                    <?php $estados[] = $value['StateId']; ?>
                    <?php endforeach; ?>
                    
                        <?php foreach ($this->getAllStates as $state) : ?>
                            <?php if (in_array($state->getId(), $estados) ) : ?>
                                <option value="<?php echo $state->getId();?>" selected="selected"><?php echo $state->getName();?></option>
                            <?php else : ?>
                                <option value="<?php echo $state->getId();?>"><?php echo $state->getName();?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                </select>
                <hr class="clear" />
            </div>

            <label for="allCities" class="label-control">Cidades integrantes:</label>
            <select tabindex="5" class="fanc2y" style="width:388px !important;" name="allCities" id="allCities">
                <option value="">Todas as Cidades</option>
                <option value="s" <?php if (isset($this->allCityId)) echo 'selected="selected"'; ?>>Seleção de Cidade(s)...</option>
            </select>
            
            <div id="areaSelectCities" class="<?php if (!isset($this->allCityId)) echo "hide"; ?>">
                <label for="citys">&nbsp;</label>
                <select data-placeholder="Escolha a(s) cidades" multiple tabindex="11" id="citys" class="fanc2y" style="width:388px !important; height: 150px;" name="serviceArea[cities][]">
                    <?php if (isset($this->allCityId)) : ?>
                            <?php 
                            $cidades = array();
                            foreach ($this->allCityId as $value) : 
                            $cidades[] = $value['CityId'];
                             endforeach; 
                             ?>
                            <?php foreach ($this->getAllCities as $city) : ?>
                                <?php if (in_array($city->getId(), $cidades)) : ?>
                                    <option value="<?php echo $city->getId();?>" selected="selected"><?php echo $city->getName();?></option>
                                <?php else : ?>
                                    <option value="<?php echo $city->getId();?>"><?php echo $city->getName();?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                    <?php endif; ?>
                </select>
                <hr class="clear" />
            </div>
            
            <label for="allNeights" class="label-control">Bairros integrantes:</label>
            
            <select tabindex="7" id="allNeights" class="fanc2y" style="width:388px !important;" name="allNeights">
                <option value="">Todos os Bairros</option>
                <option value="s" <?php if (isset($this->allNeighborhoodId)) echo 'selected="selected"'; ?>>Seleção de bairro(s)...</option>
            </select>
            <div id="areaSelectNeights" class="<?php if (!isset($this->allNeighborhoodId)) echo "hide"; ?>">
                <label for="neights" class="xnoWidth">&nbsp;</label>
                <select data-placeholder="Escolha o(s) bairro(s)" multiple tabindex="11" id="neights" class="fanc2y" style="width:388px !important; height: 150px;" name="serviceArea[neighborhoods][]">
                    <?php if (isset($this->allNeighborhoodId)) : ?>
                            <?php 
                            $bairros = array();
                            foreach ($this->allNeighborhoodId as $value) : 
                            $bairros[] = $value['NeighborhoodId'];
                            endforeach; 
                            ?>
                            <?php foreach ($this->getAllNeighborhoods as $neighborhood) : ?>
                                <?php if ( in_array($neighborhood->getId(), $bairros) ) : ?>
                                    <option value="<?php echo $neighborhood->getId();?>" selected="selected"><?php echo $neighborhood->getName();?></option>
                                <?php else : ?>
                                    <option value="<?php echo $neighborhood->getId();?>"><?php echo $neighborhood->getName();?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>

                    <?php endif; ?>
                </select>

            </div>
                            
                <?php  if (!$this->loggedAllowed('edit', 'management:regional')): ?><p></p>
                    <strong style="text-align: center; margin: 0 auto; padding-bottom: 10px; float: right">

                    “A inclusão, exclusão e manutenção de regionais deve ser feita pelo gestor estadual 
                   do Prêmio MPE, através do PSMN é possível apenas visualizar os municípios vinculados”            </strong>
                <?php endif; ?>
            <hr class="clear">
            
            <?php  if ($this->loggedAllowed('edit', 'management:regional')): ?>
            
                <button class="large green" type="submit" style="float: right" tabindex="9">
                    <span class="icon" data-icon="C"></span> Salvar
                </button>
            <?php endif; ?>
        </fieldset>
	</form>
</div>