<h1 class="center">Regional</h1>
<a title="Voltar" id="back" href="<?php echo $this->baseUrl('management/regional/'); ?>">Voltar</a>
<?php if (isset($this->itemUpdateSuccess)):?>
    <?php if ($this->itemUpdateSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Regional/Perfil de acesso (<?php echo $this->description; ?>) editada com sucesso. <br /><br />
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($this->itemInsertSuccess)):?>
    <?php if ($this->itemInsertSuccess):?>
        <div class="notice success">
            <span data-icon="C" class="icon medium"></span>
                    Regional/perfil de acesso (<?php echo $this->description; ?>) cadastrada com sucesso. <br /><br />
            <a data-icon="x" class="icon close" href="#close"></a>
        </div>
    <?php endif; ?>
<?php endif; ?>