<?php include_once 'includes/portal-head.phtml'; ?>
<?php
switch ($action) {
    case 'index': $corInscreva = 'txtroxo'; break;
    case 'premio': $corInscreva = 'txtbranco'; break;
    case 'participar': $corInscreva = 'txtroxo'; break;
    case 'premiacao': $corInscreva = 'txtbranco'; break;
    case 'regulamento': $corInscreva = 'txtbranco'; break;
    case 'historia': $corInscreva = 'txtbranco'; break;
    case 'fale': $corInscreva = 'txtroxo'; break;
    case 'cronograma': $corInscreva = 'txtroxo'; break;
    default: $corInscreva = 'txtroxo'; break;
}
?>
<main role="main" class="main" style="background-image:url('<?php echo $this->baseUrl('portal-assets/images/bgs/' . ($action=='index'? 'home' : $action) . '.png'); ?>')">
    <div class="wrapper cf" >
        <div id="content-area">
            <header role="banner" class="cell-3">
                <h1 class="logo ir">Mulher de Negócios - Prêmio Sebrae</h1>
                <nav role="navigation">
                    <ul class="menu">
                        <li <?php echo ($action=='index')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                        <li <?php echo ($action=='premio')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/premio'); ?>">O que é o Prêmio?</a></li>
                        <li <?php echo ($action=='participar')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/participar'); ?>">Como participar</a></li>
                        <li <?php echo ($action=='premiadas')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/premiadas'); ?>">Premiadas</a></li>
                        <li <?php echo ($action=='premiacao')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/premiacao'); ?>">Premiação</a></li>
                        <li <?php echo ($action=='regulamento')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/regulamento'); ?>">Regulamento</a></li>
                        <li <?php echo ($action=='historia')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/historia'); ?>">Como escrever a história</a></li>
                        <li <?php echo ($action=='fale')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/fale'); ?>">Fale conosco</a></li>
                        <li <?php echo ($action=='cronograma')? 'class="current"' : ''; ?>><a href="<?php echo $this->baseUrl('site/cronograma'); ?>">Cronograma</a></li>
                    </ul>
                </nav>
            </header>

            <?php if (!Zend_Auth::getInstance()->hasIdentity()): ?>
                <section class="auth">
                    <form method="post" class="frm inline" id="frmLogin" action="<?php echo $this->baseUrl('site/index/'); ?>" style="margin: 0 auto;" autocomplete="off">
                        <input type="hidden" name="uri" value="<?php echo $this->originalRequest? str_replace($this->baseUrl(), '', $this->originalRequest['uri']) : '' ?>">
                        <label for="auth_login">CPF</label>
                        <input title="Login" type="text" name="username" id="auth_login" placeholder="Informe seu CPF ou login" required autocomplete="off">
                        <label for="auth_senha" class="senha">Senha</label>
                        <input title="Senha" class="senha" type="password" name="password" id="auth_senha" autocomplete="off">
                        <button type="submit" class="bt-enviar-login">Entrar</button>
                        <!--a href="#" class="<?php echo $corInscreva; ?>" >Inscreva-se <i class="seta ir">seta</i></a-->
                    </form>
                    <a href="<?php echo $this->baseUrl('/login/lost'); ?>" class="senha" id="link-forgot-password" style="
    display: none;    clear: both;    white-space: nowrap;    top: 34px;    font-size: 10px;    text-transform: none;    left: 406px;    color: #7a4f66;    text-decoration: underline;
">Esqueci minha senha</a>
                </section>
            <?php else: ?>
            <?php endif; ?>
            <div class="cell-8 customPad">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </div>
</main>

<?php include_once 'includes/portal-footer.phtml'; ?>